---
sidebar: sidebar 
permalink: integrations/dashboard-overview.html 
keywords: Keystone, Digital Advisor, keystone-aiq, aiq, BlueXP, Keystone dashboard, NetApp Console, Console 
summary: Als NetApp Keystone STaaS-Abonnent können Sie sich über die NetApp Console oder den Digital Advisor einen Überblick über Ihre Abonnements verschaffen. 
---
= Erfahren Sie mehr über das Keystone-Dashboard
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Das Keystone-Dashboard ist Ihre Lösung für die effiziente Überwachung, Analyse und Verwaltung Ihrer Keystone-Abonnements. Mit dem Keystone-Dashboard erreichen Sie folgende Ziele:

* *Abonnementdetails überwachen*: Sehen Sie detaillierte Informationen zu Ihren Keystone-Abonnements ein, einschließlich der Leistungs-Servicelevel (Basis- und Zusatzdienste wie erweiterter Datenschutz und Data Infrastructure Insights), Kapazitätsnutzung, Assets und Warnmeldungen.
* *Kapazitätsnutzung verfolgen und Berichte erstellen*: Behalten Sie die aktuelle und historische Kapazitätsnutzung im Auge und erstellen Sie Berichte, um Abonnementdaten zu analysieren und fundierte Entscheidungen zu treffen.
* *Abonnement-Zeitleiste anzeigen*: Bleiben Sie über wichtige Termine und Ereignisse informiert, indem Sie die Zeitleiste Ihrer Abonnements überwachen.
* *Abonnements verwalten*: Senden Sie Anfragen zum Ändern der Leistungsservicelevel oder anderer Abonnementparameter, wenn sich Ihre Anforderungen ändern.
* *Volumes und Objekte analysieren*: Erhalten Sie detaillierte Einblicke in die Volumes und Objekte Ihrer Abonnements, einschließlich ihrer Kapazität auf Volume- und Objektebene.




== Greifen Sie auf das Keystone-Dashboard zu

Sie können auf das Keystone-Dashboard wie folgt zugreifen:

* * NetApp Konsole*: Greifen Sie über *Storage > Keystone > Übersicht* in der Konsole auf das Dashboard zu. Weitere Informationen finden Sie unterlink:../integrations/keystone-console.html["Keystone -Dashboard in der NetApp -Konsole"^] .
* *Active IQ Digital Advisor* (auch bekannt als Digital Advisor): Greifen Sie über *Allgemein > Keystone-Abonnements* im Digital Advisor auf das Dashboard zu. Weitere Informationen finden Sie unter link:../integrations/keystone-aiq.html["Keystone-Dashboard im Digital Advisor"^].




== Informationen zur NetApp Konsole

Auf Keystone kann über die NetApp Konsole zugegriffen werden.

Die NetApp Konsole ermöglicht die zentrale Verwaltung von NetApp -Speicher- und Datendiensten in lokalen und Cloud-Umgebungen im Unternehmensmaßstab. Die Konsole ist für den Zugriff auf und die Nutzung der NetApp -Datendienste erforderlich. Als Verwaltungsschnittstelle ermöglicht es Ihnen, viele Speicherressourcen über eine Schnittstelle zu verwalten. Konsolenadministratoren können den Zugriff auf Speicher und Dienste für alle Systeme innerhalb des Unternehmens steuern.

Sie benötigen weder eine Lizenz noch ein Abonnement, um die Konsole zu verwenden. Es fallen nur dann Kosten an, wenn Sie Konsolenagenten in Ihrer Cloud bereitstellen müssen, um die Konnektivität zu Ihren Speichersystemen oder NetApp Datendiensten sicherzustellen. Einige NetApp -Datendienste, auf die über die Konsole zugegriffen werden kann, sind jedoch lizenz- oder abonnementbasiert.

Erfahren Sie mehr über dielink:https://docs.netapp.com/us-en/bluexp-setup-admin/concept-overview.html["NetApp Konsole"^] .

Beachten Sie Folgendes:

* Während die Console und der Digital Advisor einige exklusive Funktionen bieten, stellt die Console administrative Funktionen für Keystone bereit, mit denen Sie Abonnements verwalten und notwendige Anpassungen vornehmen können. Weitere Informationen finden Sie unter link:https://docs.netapp.com/us-en/console-setup-admin/reference-iam-keystone-roles.html["Keystone -Zugriffsrollen in der NetApp Console"^]Die
* Digital Advisor ist in die Konsole integriert, sodass Sie direkt von der Konsole aus auf alle Funktionen von Digital Advisor zugreifen können, einschließlich des Keystone -Dashboards. Weitere Informationen finden Sie unterlink:https://docs.netapp.com/us-en/active-iq/digital-advisor-integration-with-console.html#netapp-console["Digital Advisor Integration mit der NetApp Konsole"^] .




== Keystone -Funktionen in NetApp Console und Digital Advisor

Die folgende Tabelle zeigt die Verfügbarkeit von Funktionen in der NetApp Konsole und im Digital Advisor und hilft Ihnen, schnell die richtige Plattform für Ihre Anforderungen zu finden:

|===


| *Funktion* | * NetApp Konsole* | *Digitaler Berater* 


 a| 
link:../integrations/subscriptions-tab.html["Zeigen Sie Ihre Abonnementdetails an"]
| Ja. | Ja. 


 a| 
link:../integrations/current-usage-tab.html["Überwachen Sie die aktuelle und historische Kapazitätsnutzung"]
| Ja. | Ja. 


 a| 
link:../integrations/subscription-timeline.html["Verfolgen Sie den Abonnementzeitplan"]
| Ja. | Nein 


 a| 
link:../integrations/assets-tab.html["Anzeigen von Assets, die mit einem Keystone-Abonnement verknüpft sind"]
| Ja. | Ja. 


| link:../integrations/assets.html["Anzeigen von Assets über mehrere Keystone-Abonnements hinweg"] | Ja. | Nein 


 a| 
link:../integrations/monitoring-alerts.html["Anzeigen und Verwalten von Warnungen und Monitoren"]
| Ja. | Nein 


 a| 
link:../integrations/options.html#generate-reports-from-netapp-console-or-digital-advisor["Berichte generieren"]
| Ja. | Ja. 


 a| 
link:../integrations/volumes-objects-tab.html["Zeigen Sie Volumes und Objektdetails an"]
| Ja. | Ja. 


 a| 
link:../integrations/adp-tab.html["Anzeigen des MetroCluster-Verbrauchs und -Status"]
| Ja (einschließlich Gesundheitsstatus, Topologieansicht und Synchronisierungsüberwachung) | Ja (nur Verbrauchsdaten) 


 a| 
link:../integrations/performance-tab.html["Performance-Metriken anzeigen"]
| Nein | Ja. 
|===
*Verwandte Informationen*

* link:../integrations/dashboard-access.html["Erste Schritte mit dem Keystone-Dashboard"]
* link:../integrations/keystone-console.html["Keystone -Dashboard in der NetApp -Konsole"]
* link:..//integrations/keystone-aiq.html["Keystone-Dashboard im Digital Advisor"]

