---
sidebar: sidebar 
permalink: integrations/keystone-cm.html 
keywords: Keystone-BlueXP 
summary: Keystone und BlueXP 
---
= Keystone und BlueXP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Wenn Sie einen Cloud-Service über Ihr Keystone Abonnement erwerben, können Sie diese Services über BlueXP nutzen und verwalten.

Wenn Sie Keystone Kunden über ein Cloud Volumes ONTAP-Abonnement verfügen, können Sie mit den Keystone Services Ihre Cloud Volumes ONTAP-Nutzung berechnen und sich Ihre Rechnungs- und Nutzungsdetails über BlueXP anzeigen lassen.

Dazu sollten Sie ein oder mehrere BlueXP Accounts erstellen und sie mit Ihrem Keystone Konto verknüpfen. Während Sie einen Cloud-Service über Keystone erwerben, müssen Sie Ihrem Keystone Success Manager (KSM) alle Einzelheiten Ihres BlueXP Kontos angeben. So können Sie Ihre Cloud-Service-Nutzung über Ihr Keystone Abonnement richtig Messung und Abrechnung ausführen.

Weitere Informationen finden Sie unter den folgenden Links in den BlueXP-Dokumenten:

* https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/concept-licensing.html#keystone-flex-subscription["Keystone Abonnement"^]
* https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-manage-keystone.html["Keystone Abonnements Managen"^]

