---
sidebar: sidebar 
permalink: integrations/keystone-cm.html 
keywords: Keystone-BlueXP 
summary: Keystone und BlueXP 
---
= Keystone und BlueXP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NetApp BlueXP ist eine umfassende Plattform für das Monitoring hunderter Datenquellen mit einem eigenen interaktiven VisualisierungsDashboard. Wenn Sie einen Cloud-Service in Ihrem NetApp Keystone Abonnement erwerben, können Sie über BlueXP auf diese Services zugreifen und diese managen.

Das BlueXP Digital Advisor Dashboard bietet Ihnen eine grafische Ansicht und detaillierte Funktionen, um die Nutzung Ihrer Keystone Abonnements zu überwachen und Berichte zu erstellen. Weitere Informationen zum Digital Advisor Dashboard und zu Keystone finden Sie unter link:../integrations/aiq-keystone-details.html["Keystone Abonnement-Dashboard und Berichterstellung"].

Wenn Sie Keystone Kunden über ein Cloud Volumes ONTAP-Abonnement verfügen, können Sie mit den Keystone Services Ihre Cloud Volumes ONTAP-Nutzung berechnen und sich Ihre Rechnungs- und Nutzungsdetails über BlueXP anzeigen lassen.

Dazu sollten Sie ein oder mehrere BlueXP Accounts erstellen und sie mit Ihrem Keystone Konto verknüpfen. Während Sie einen Cloud-Service über Keystone erwerben, müssen Sie Ihrem Keystone Success Manager (KSM) alle Einzelheiten Ihres BlueXP Kontos angeben. So können Sie Ihre Cloud-Service-Nutzung über Ihr Keystone Abonnement richtig Messung und Abrechnung ausführen.

Weitere Informationen zu Keystone und BlueXP erhalten Sie über die folgenden Links in den BlueXP Dokumenten:

* https://["Keystone Abonnement"^]
* https://["Keystone Abonnements Managen"^]

