---
sidebar: sidebar 
permalink: integrations/keystone-aiq.html 
keywords: Keystone, Digital Advisor, keystone-aiq, aiq 
summary: Keystone und Digital Advisor 
---
= Keystone und Digital Advisor
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Wenn Sie NetApp Keystone Services abonniert haben, können Sie Ihre Nutzungsberichte und Diagramme im Active IQ Digital Advisor Dashboard (Digital Advisor) anzeigen.

Digital Advisor ermöglicht Ihnen, Details und Informationen zu Storage-als-Service (STaaS) und zur eigenen NetApp Infrastruktur anzuzeigen. Digital Advisor bietet eine zentrale Konsole mit einer Übersicht über Ihre Abonnements, Service-Level und die Kapazitätsauslastung sowie der Möglichkeit, detaillierte Berichte zu erstellen.

Weitere Informationen über das Widget „Digital Advisor Dashboard“ für Keystone finden Sie unter https://["Digital Advisor Dokumentation"^].

Weitere Informationen zum Keystone Dashboard und Reporting finden Sie unter link:../integrations/aiq-keystone-details.html["Keystone Abonnement-Dashboard und Berichterstellung"].

Weitere Informationen zum Datenfluss finden Sie unter link:../concepts/infra.html["Monitoring-Tools"].
