---
settings:
  name: Keystone
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: de-de,us-en,ja-jp,ko-kr,zh-cn,zh-tw,es-es,fr-fr,it-it
sidebar:
  entries:
  - title: Keystone Dokumentation
    url: "/index.html"
  - title: Willkommen bei Keystone
    url: "/concepts/overview.html"
  - title: Keystone wird eingerichtet und konfiguriert
    entries:
    - title: Was ist Keystone Collector
      url: "/installation/installation-overview.html"
    - title: Voraussetzungen für die Installation von Keystone Collector
      entries:
      - title: Voraussetzungen für VMware vSphere
        url: "/installation/vapp-prereqs.html"
      - title: Linux-Voraussetzungen
        url: "/installation/linux-prereqs.html"
      - title: Spezifische Voraussetzungen für ONTAP und StorageGRID
        url: "/installation/addl-req.html"
    - title: Installationsvorgang
      entries:
      - title: Implementierung von VMware vSphere
        url: "/installation/vapp-installation.html"
      - title: Linux-Installation
        url: "/installation/linux-installation.html"
      - title: Automatische Integritätsprüfung
        url: "/installation/validation.html"
    - title: Konfigurieren Sie Keystone Collector
      url: "/installation/configuration.html"
    - title: Systemzustand überwachen
      url: "/installation/monitor-health.html"
    - title: Aktualisieren Sie Keystone Collector
      url: "/installation/upgrade.html"
    - title: Daten, die zur Abrechnung erfasst werden
      url: "/installation/data-collection.html"
  - title: Weitere Informationen zu Keystone
    entries:
    - title: Unterstützte Storage-Kapazität
      url: "/concepts/supported-storage-capacity.html"
    - title: Metriken und Definitionen
      url: "/concepts/metrics.html"
    - title: Unterstützter Storage in Keystone
      url: "/concepts/supported-storage-services.html"
    - title: Service-Level in Keystone
      url: "/concepts/service-levels.html"
    - title: Add-on-Services
      entries:
      - title: Daten-Tiering
        url: "/concepts/data-tiering.html"
      - title: Erweiterte Datensicherung
        url: "/concepts/adp.html"
      - title: USA Citizen Support (USCS)
        url: "/concepts/uscs.html"
      - title: Non-Returnable, Non-Volatile Komponenten und SnapLock-Compliance
        url: "/concepts/nrnvc.html"
      - title: Keystone und Equinix
        url: "/concepts/equinix.html"
  - title: Weitere Informationen zu Service-Leveln
    entries:
    - title: Quality of Service
      url: "/concepts/qos.html"
    - title: Kapazitätsanforderungen für Service Levels
      url: "/concepts/capacity-requirements.html"
  - title: Abrechnung
    entries:
    - title: Keystone-Preisgestaltung
      url: "/concepts/pricing.html"
    - title: Abrechnung basiert auf der verplante Kapazität
      url: "/concepts/committed-capacity-billing.html"
    - title: Messung basierend auf verbrauchter Kapazität
      url: "/concepts/consumed-capacity-billing.html"
    - title: Abrechnung auf Basis von Burst-Nutzung
      url: "/concepts/burst-consumption-billing.html"
    - title: Die Abrechnung basiert auf verschiedenen Volume-Typen
      url: "/concepts/misc-volume-billing.html"
    - title: Abrechnungszeitpläne
      url: "/concepts/billing-schedules.html"
  - title: Partner- und vom Kunden betriebene Umgebungen zu optimieren
    url: "/concepts/operational-models.html"
  - title: Keystone Infrastruktur
    entries:
    - title: Detaillierte Informationen zur Infrastruktur
      url: "/concepts/infra.html"
    - title: Komponenten
      url: "/concepts/components.html"
    - title: Datenfluss
      url: "/concepts/data-flow.html"
  - title: NetApp Global Services Support Center
    url: "/concepts/gssc.html"
  - title: Mit Keystone Services mehr erreichen
    entries:
    - title: Keystone und BlueXP
      url: "/integrations/keystone-cm.html"
    - title: Keystone und Active IQ Digital Advisor
      url: "/integrations/keystone-aiq.html"
    - title: Active IQ Digital Advisor Reporting für Keystone
      url: "/integrations/aiq-keystone-details.html"
  - title: Rechtliche Hinweise
    url: "/legal-notices.html"
homepage:
  tiles:
  - title: Los geht's
    links:
    - title: Was ist NetApp Keystone?
      url: "/concepts/overview.html"
    - title: Installieren von Keystone Collector auf VMware vSphere
      url: "/installation/vapp-installation.html"
    - title: Installieren von Keystone Collector unter Linux
      url: "/installation/linux-installation.html"
    - title: Was sind die Maßeinheiten?
      url: "/concepts/metrics.html"
    - title: Welcher Basis-Storage wird unterstützt?
      url: "/concepts/supported-storage-services.html"
    - title: Wie kann ich meine Verbrauchsdaten sehen?
      url: "/integrations/keystone-aiq.html"
  - title: Unterstützte Services in Keystone
    links:
    - title: Keystone Service-Level
      url: "/concepts/service-levels.html"
    - title: Servicequalität (QoS)
      url: "/concepts/qos.html"
    - title: Was ist Daten-Tiering?
      url: "/concepts/data-tiering.html"
    - title: Sind meine Keystone-Daten geschützt?
      url: "/concepts/adp.html"
    - title: Wie kann ich meinen Verbrauch je Service Level erkennen?
      url: "/integrations/aiq-keystone-details.html"
  - title: Keystone-Preisgestaltung
    links:
    - title: Informationen zur Keystone Abrechnung
      url: "/concepts/pricing.html"
    - title: Meine Abrechnungspläne
      url: "/concepts/billing-schedules.html"
    - title: Abrechnung basiert auf der verplante Kapazität
      url: "/concepts/committed-capacity-billing.html"
    - title: Messung basierend auf verbrauchter Kapazität
      url: "/concepts/consumed-capacity-billing.html"
    - title: Was geschieht, wenn ich mehr als meine engagierte Kapazität verbraucht
        habe?
      url: "/concepts/burst-consumption-billing.html"
  - title: Mit Keystone Services mehr erreichen
    links:
    - title: Ihr Support-Team kennen (Keystone GSSC)
      url: "/concepts/gssc.html"
    - title: Keystone und BlueXP
      url: "/integrations/keystone-cm.html"
    - title: Keystone und Active IQ Digital Advisor
      url: "/integrations/keystone-aiq.html"
    - title: US Citizen Support
      url: "/concepts/uscs.html"
  - title: Erfahren Sie mehr
    links:
    - title: Keystone Flex Abonnement
      url: https://docs.netapp.com/us-en/keystone/
    - title: Active IQ Digitalberater
      url: https://docs.netapp.com/us-en/active-iq/index.html
    - title: BlueXP
      url: https://docs.netapp.com/us-en/cloud-manager-family/
    - title: Active IQ Unified Manager
      url: https://docs.netapp.com/us-en/active-iq-unified-manager/
