---
settings:
  name: Keystone
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: de-de,us-en,ja-jp,ko-kr,zh-cn,zh-tw,es-es,fr-fr,it-it
sidebar:
  entries:
  - title: Keystone Dokumentation
    url: "/index.html"
  - title: Versionshinweise
    entries:
    - title: Neuerungen bei Keystone STaaS
      url: "/release-notes/whats-new.html"
    - title: Probleme wurden behoben
      url: "/release-notes/fixed-issues.html"
    - title: Bekannte Probleme
      url: "/release-notes/known-issues.html"
    - title: Bekannte Einschränkungen
      url: "/release-notes/known-limitations.html"
  - title: Weitere Informationen zu Keystone
    entries:
    - title: Überblick
      url: "/concepts/overview.html"
    - title: Keystone Infrastruktur
      url: "/concepts/infra.html"
    - title: Keystone Collector
      url: "/installation/installation-overview.html"
    - title: Komponenten
      url: "/concepts/components.html"
    - title: Datenfluss
      url: "/concepts/data-flow.html"
    - title: Betriebsmodelle
      url: "/concepts/operational-models.html"
  - title: Keystone wird eingerichtet und konfiguriert
    entries:
    - title: Anforderungen
      entries:
      - title: Virtuelle Infrastruktur
        url: "/installation/vapp-prereqs.html"
      - title: Linux
        url: "/installation/linux-prereqs.html"
      - title: ONTAP und StorageGRID
        url: "/installation/addl-req.html"
    - title: Installieren Sie Keystone Collector
      entries:
      - title: Implementieren auf VMware vSphere
        url: "/installation/vapp-installation.html"
      - title: Installation unter Linux
        url: "/installation/linux-installation.html"
      - title: Automatische Validierung der Keystone Software
        url: "/installation/validation.html"
    - title: Konfigurieren Sie Keystone Collector
      url: "/installation/configuration.html"
    - title: Konfigurieren Sie AutoSupport
      url: "/installation/asup-config.html"
    - title: Sicherheit mit Keystone Collector
      url: "/installation/security.html"
    - title: Daten, die zur Abrechnung erfasst werden
      url: "/installation/data-collection.html"
  - title: Monitoring und Upgrade
    entries:
    - title: Überwachen Sie den Zustand des Keystone Collectors
      url: "/installation/monitor-health.html"
    - title: Aktualisieren Sie Keystone Collector
      url: "/installation/upgrade.html"
  - title: Keystone Dashboard
    entries:
    - title: Übersicht über Keystone Dashboard
      url: "/integrations/keystone-aiq.html"
    - title: Nutzungsdetails anzeigen und Berichte erstellen
      url: "/integrations/aiq-keystone-details.html"
    - title: Registerkarte Abonnements
      url: "/integrations/subscriptions-tab.html"
    - title: Registerkarte Stromaufnahme
      url: "/integrations/current-usage-tab.html"
    - title: Registerkarte „Verbrauchstrend“
      url: "/integrations/capacity-trend-tab.html"
    - title: Registerkarte „Volumes & Objekte“
      url: "/integrations/volumes-objects-tab.html"
    - title: Registerkarte „Assets“
      url: "/integrations/assets-tab.html"
    - title: Registerkarte „Performance“
      url: "/integrations/performance-tab.html"
    - title: Erfahren Sie mehr über Keystone und BlueXP
      url: "/integrations/keystone-cm.html"
  - title: Keystone STaaS Services
    entries:
    - title: Metriken und Definitionen
      url: "/concepts/metrics.html"
    - title: Storage-Servicequalität
      url: "/concepts/qos.html"
    - title: Unterstützter Storage
      url: "/concepts/supported-storage-services.html"
    - title: Unterstützte Kapazität
      url: "/concepts/supported-storage-capacity.html"
    - title: Service-Leveln
      url: "/concepts/service-levels.html"
    - title: Kapazitätsanforderungen für Service Levels
      url: "/concepts/capacity-requirements.html"
    - title: Keystone Abonnementservices Version 1
      url: "/subscription-services-v1.html"
    - title: Zusätzliche Services
      entries:
      - title: Erweiterte Datensicherung
        url: "/concepts/adp.html"
      - title: Daten-Tiering
        url: "/concepts/data-tiering.html"
      - title: Equinix-gestützte Services
        url: "/concepts/equinix.html"
      - title: Non-Returnable, nichtflüchtige Komponenten und SnapLock Compliance
        url: "/concepts/nrnvc.html"
      - title: USA Citizen Support (USCS)
        url: "/concepts/uscs.html"
  - title: Keystone STaaS SLA
    entries:
    - title: Gesteigerte
      url: "/concepts/sla-availability.html"
    - title: Leistung
      url: "/concepts/sla-performance.html"
    - title: Nachhaltigkeit
      url: "/concepts/sla-sustainability.html"
    - title: Recovery-Garantie Von Ransomware
      url: "/concepts/sla-ransomware.html"
  - title: Keystone im privaten Modus
    entries:
    - title: Überblick
      url: "/dark-sites/overview.html"
    - title: Installation vorbereiten
      url: "/dark-sites/requirements.html"
    - title: Installieren Sie Keystone Collector
      url: "/dark-sites/install-collector.html"
    - title: Konfigurieren Sie Keystone Collector
      url: "/dark-sites/configure-collector.html"
    - title: Überwachen Sie den Zustand des Keystone Collectors
      url: "/dark-sites/monitor.html"
  - title: Zugriff auf Keystone über die Digital Advisor REST-API
    entries:
    - title: Erste Schritte zum Abrufen von Keystone-Daten über die REST-API von Digital
        Advisor
      url: "/rest-api/retrieve-keystone-data-with-digital-advisor-rest-api.html"
    - title: Erstellen Sie Aktualisierungs- und Zugriffstoken
      url: "/rest-api/generate-tokens.html"
    - title: Eine Liste aller Kunden, die die Digital Advisor REST API verwenden
      url: "/rest-api/get-customer-list.html"
    - title: Kunden-Abonnements über die Digital Advisor REST-API abrufen
      url: "/rest-api/get-customer-subscriptions.html"
    - title: Details zur Kundennutzung erhalten Sie über die REST-API von Digital
        Advisor
      url: "/rest-api/get-customer-consumption.html"
  - title: Abrechnung
    entries:
    - title: Keystone-Preisgestaltung
      url: "/concepts/pricing.html"
    - title: Abrechnung basiert auf der verplante Kapazität
      url: "/concepts/committed-capacity-billing.html"
    - title: Messung basierend auf verbrauchter Kapazität
      url: "/concepts/consumed-capacity-billing.html"
    - title: Abrechnung auf Basis von Burst-Nutzung
      url: "/concepts/burst-consumption-billing.html"
    - title: Verschiedene Szenarien für Keystone Abrechnung
      url: "/concepts/misc-volume-billing.html"
    - title: Abrechnungszeitpläne
      url: "/concepts/billing-schedules.html"
  - title: Keystone hilft Ihnen dabei
    url: "/concepts/gssc.html"
  - title: Rechtliche Hinweise
    url: "/legal-notices.html"
