---
settings:
  name: Keystone
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: de-de,us-en,ja-jp,ko-kr,zh-cn,zh-tw,es-es,fr-fr,it-it
sidebar:
  entries:
  - title: Keystone Dokumentation
    url: "/index.html"
  - title: Versionshinweise
    entries:
    - title: Neuerungen bei Keystone STaaS
      url: "/release-notes/whats-new.html"
    - title: Probleme wurden behoben
      url: "/release-notes/fixed-issues.html"
    - title: Bekannte Probleme
      url: "/release-notes/known-issues.html"
    - title: Bekannte Einschränkungen
      url: "/release-notes/known-limitations.html"
  - title: Willkommen bei Keystone
    url: "/concepts/overview.html"
  - title: Keystone wird eingerichtet und konfiguriert
    entries:
    - title: Was ist Keystone Collector
      url: "/installation/installation-overview.html"
    - title: Bereiten Sie Ihr System vor
      entries:
      - title: Anforderungen für VMware vSphere
        url: "/installation/vapp-prereqs.html"
      - title: Linux-Anforderungen
        url: "/installation/linux-prereqs.html"
      - title: Anforderungen für ONTAP und StorageGRID
        url: "/installation/addl-req.html"
    - title: Installieren Sie Keystone Collector
      entries:
      - title: Implementierung von VMware vSphere
        url: "/installation/vapp-installation.html"
      - title: Linux-Installation
        url: "/installation/linux-installation.html"
      - title: Automatische Integritätsprüfung
        url: "/installation/validation.html"
    - title: Konfigurieren Sie Keystone Collector
      url: "/installation/configuration.html"
    - title: Systemzustand überwachen
      url: "/installation/monitor-health.html"
    - title: Aktualisieren Sie Keystone Collector
      url: "/installation/upgrade.html"
    - title: AutoSupport für Keystone konfigurieren
      url: "/installation/asup-config.html"
    - title: Sicherheit mit Keystone Collector
      url: "/installation/security.html"
    - title: Daten, die zur Abrechnung erfasst werden
      url: "/installation/data-collection.html"
  - title: Keystone Dashboard
    entries:
    - title: Das Keystone Dashboard zeigt es an
      url: "/integrations/keystone-aiq.html"
    - title: Nutzungsdetails anzeigen und Berichte erstellen
      url: "/integrations/aiq-keystone-details.html"
    - title: Registerkarte Abonnements
      url: "/integrations/subscriptions-tab.html"
    - title: Registerkarte „Aktuelle Nutzung“
      url: "/integrations/current-usage-tab.html"
    - title: Registerkarte „Kapazitätstrend“
      url: "/integrations/capacity-trend-tab.html"
    - title: Registerkarte „Volumes & Objekte“
      url: "/integrations/volumes-objects-tab.html"
    - title: Registerkarte „Performance“
      url: "/integrations/performance-tab.html"
    - title: Registerkarte „Assets“
      url: "/integrations/assets-tab.html"
    - title: Keystone Abonnements von BlueXP managen und
      url: "/integrations/keystone-cm.html"
  - title: Keystone STaaS Services
    entries:
    - title: Metriken und Definitionen
      url: "/concepts/metrics.html"
    - title: Quality of Service
      url: "/concepts/qos.html"
    - title: Unterstützter Storage
      url: "/concepts/supported-storage-services.html"
    - title: Unterstützte Kapazität
      url: "/concepts/supported-storage-capacity.html"
    - title: Service-Leveln
      url: "/concepts/service-levels.html"
    - title: Unterstützte Kapazität für Service-Level
      url: "/concepts/capacity-requirements.html"
    - title: Keystone Abonnementservices Version 1
      url: "/subscription-services-v1.html"
    - title: Zusätzliche Services
      entries:
      - title: Erweiterte Datensicherung
        url: "/concepts/adp.html"
      - title: Daten-Tiering
        url: "/concepts/data-tiering.html"
      - title: Equinix-gestützte Services
        url: "/concepts/equinix.html"
      - title: Non-Returnable, Non-Volatile Komponenten und SnapLock-Compliance
        url: "/concepts/nrnvc.html"
      - title: USA Citizen Support (USCS)
        url: "/concepts/uscs.html"
  - title: Abrechnung
    entries:
    - title: Keystone-Preisgestaltung
      url: "/concepts/pricing.html"
    - title: Abrechnung basiert auf der verplante Kapazität
      url: "/concepts/committed-capacity-billing.html"
    - title: Messung basierend auf verbrauchter Kapazität
      url: "/concepts/consumed-capacity-billing.html"
    - title: Abrechnung auf Basis von Burst-Nutzung
      url: "/concepts/burst-consumption-billing.html"
    - title: Die Abrechnung basiert auf verschiedenen Volume-Typen
      url: "/concepts/misc-volume-billing.html"
    - title: Abrechnungszeitpläne
      url: "/concepts/billing-schedules.html"
  - title: Partner- und vom Kunden betriebene Umgebungen zu optimieren
    url: "/concepts/operational-models.html"
  - title: Keystone Infrastruktur
    entries:
    - title: Detaillierte Informationen zur Infrastruktur
      url: "/concepts/infra.html"
    - title: Komponenten
      url: "/concepts/components.html"
    - title: Datenfluss
      url: "/concepts/data-flow.html"
  - title: NetApp Global Services Support Center
    url: "/concepts/gssc.html"
  - title: Rechtliche Hinweise
    url: "/legal-notices.html"
