---
settings:
  name: Keystone
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  versions:
  - version-number: '3.0'
    url: "/keystone-staas"
  - version-number: '2.0'
    url: "/keystone-staas-2"
  langs: de-de,us-en,es-es,fr-fr,it-it,pt-br,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Keystone Dokumentation
    url: "/index.html"
  - title: Versionshinweise
    entries:
    - title: Neuerungen bei Keystone STaaS
      url: "/whats-new.html"
    - title: Probleme wurden behoben
      url: "/release-notes/fixed-issues.html"
    - title: Bekannte Probleme
      url: "/release-notes/known-issues.html"
    - title: Bekannte Einschränkungen
      url: "/release-notes/known-limitations.html"
  - title: Los geht's
    entries:
    - title: Erfahren Sie mehr über Keystone STaaS
      url: "/concepts/overview.html"
    - title: Keystone Infrastruktur
      url: "/concepts/infra.html"
    - title: Keystone Collector
      url: "/installation/installation-overview.html"
    - title: Komponenten
      url: "/concepts/components.html"
    - title: Datenfluss
      url: "/concepts/data-flow.html"
    - title: Betriebsmodelle
      url: "/concepts/operational-models.html"
  - title: Keystone wird eingerichtet und konfiguriert
    entries:
    - title: Anforderungen
      entries:
      - title: Virtuelle Infrastruktur
        url: "/installation/vapp-prereqs.html"
      - title: Linux
        url: "/installation/linux-prereqs.html"
      - title: ONTAP und StorageGRID
        url: "/installation/addl-req.html"
    - title: Installieren Sie Keystone Collector
      entries:
      - title: Implementieren auf VMware vSphere
        url: "/installation/vapp-installation.html"
      - title: Installation unter Linux
        url: "/installation/linux-installation.html"
      - title: Automatische Validierung der Keystone Software
        url: "/installation/validation.html"
    - title: Konfigurieren Sie Keystone Collector
      url: "/installation/configuration.html"
    - title: Installieren Sie ITOM Collector
      entries:
      - title: Installation vorbereiten
        url: "/installation/itom-prereqs.html"
      - title: Installation unter Linux
        url: "/installation/install-itom-linux.html"
      - title: Unter Windows installieren
        url: "/installation/install-itom-windows.html"
    - title: Konfigurieren Sie AutoSupport
      url: "/installation/asup-config.html"
    - title: Monitoring und Upgrade
      entries:
      - title: Überwachen Sie den Zustand des Keystone Collectors
        url: "/installation/monitor-health.html"
      - title: Aktualisieren Sie Keystone Collector
        url: "/installation/upgrade.html"
    - title: Sicherheit mit Keystone Collector
      url: "/installation/security.html"
    - title: Daten, die zur Abrechnung erfasst werden
      url: "/installation/data-collection.html"
    - title: Keystone im privaten Modus
      entries:
      - title: Überblick
        url: "/dark-sites/overview.html"
      - title: Installation vorbereiten
        url: "/dark-sites/requirements.html"
      - title: Installieren Sie Keystone Collector
        url: "/dark-sites/install-collector.html"
      - title: Konfigurieren Sie Keystone Collector
        url: "/dark-sites/configure-collector.html"
      - title: Überwachen Sie den Zustand des Keystone Collectors
        url: "/dark-sites/monitor.html"
  - title: Verwalten und Überwachen von Keystone-Abonnements
    entries:
    - title: Das Keystone-Dashboard verstehen
      entries:
      - title: Erfahren Sie mehr über das Keystone-Dashboard
        url: "/integrations/dashboard-overview.html"
      - title: Erste Schritte mit dem Keystone-Dashboard
        url: "/integrations/dashboard-access.html"
      - title: Keystone -Dashboard in der NetApp -Konsole
        url: "/integrations/keystone-console.html"
      - title: Keystone-Dashboard im Digital Advisor
        url: "/integrations/keystone-aiq.html"
      - title: Daten durchsuchen, Berichte erstellen und Warnmeldungen anzeigen
        url: "/integrations/options.html"
    - title: Abonnementinformationen anzeigen
      entries:
      - title: Zeigen Sie Ihre Abonnementdetails an
        url: "/integrations/subscriptions-tab.html"
      - title: Sehen Sie sich Ihre aktuellen Verbrauchsdetails an
        url: "/integrations/current-usage-tab.html"
      - title: Verbrauchstrends anzeigen
        url: "/integrations/consumption-tab.html"
      - title: Zeigen Sie die Zeitleiste Ihres Abonnements an
        url: "/integrations/subscription-timeline.html"
    - title: Assets anzeigen
      entries:
      - title: Anzeigen von Assets, die mit einem Abonnement verknüpft sind
        url: "/integrations/assets-tab.html"
      - title: Anzeigen von Assets über mehrere Abonnements hinweg
        url: "/integrations/assets.html"
    - title: Anzeigen und Verwalten von Warnungen und Monitoren
      entries:
      - title: Anzeigen und Verwalten von Warnungen
        url: "/integrations/monitoring-alerts.html"
      - title: Anzeigen und Erstellen von Warnmonitoren
        url: "/integrations/monitoring-alert-monitors.html"
    - title: Ändern Sie Ihre Abonnements
      url: "/integrations/modify-subscription.html"
    - title: Zeigen Sie Ihre Serviceanfrage an
      url: "/integrations/administration-tab.html"
    - title: Anzeigen von Volumes und Objektspeicherdetails
      url: "/integrations/volumes-objects-tab.html"
    - title: Performance-Metriken anzeigen
      url: "/integrations/performance-tab.html"
  - title: Konzepte
    entries:
    - title: Keystone STaaS Services
      entries:
      - title: Metriken und Definitionen
        url: "/concepts/metrics.html"
      - title: Unterstützter Storage
        url: "/concepts/supported-storage-services.html"
      - title: Unterstützte Kapazität
        url: "/concepts/supported-storage-capacity.html"
      - title: Leistungsservicelevel
        url: "/concepts/service-levels.html"
      - title: Kapazitätsanforderungen für Performance-Service-Levels
        url: "/concepts/capacity-requirements.html"
    - title: Zusätzliche Services
      entries:
      - title: Burst-Kapazitätsoptionen
        url: "/concepts/burst-capacity.html"
      - title: Einblicke In Die Dateninfrastruktur
        url: "/concepts/data-infra-insights.html"
      - title: Daten-Tiering
        url: "/concepts/data-tiering.html"
      - title: Non-Returnable, nichtflüchtige Komponenten und SnapLock Compliance
        url: "/concepts/nrnvc.html"
      - title: US Protected Support (USPS)
        url: "/concepts/usps.html"
    - title: Keystone STaaS SLO
      entries:
      - title: Gesteigerte
        url: "/concepts/sla-availability.html"
      - title: Leistung
        url: "/concepts/sla-performance.html"
      - title: Nachhaltigkeit
        url: "/concepts/sla-sustainability.html"
      - title: Recovery-Garantie Von Ransomware
        url: "/concepts/sla-ransomware.html"
    - title: Abrechnung
      entries:
      - title: Keystone-Preisgestaltung
        url: "/concepts/pricing.html"
      - title: Abrechnung basiert auf der verplante Kapazität
        url: "/concepts/committed-capacity-billing.html"
      - title: Messung basierend auf verbrauchter Kapazität
        url: "/concepts/consumed-capacity-billing.html"
      - title: Abrechnung auf Basis von Burst-Nutzung
        url: "/concepts/burst-consumption-billing.html"
      - title: Verschiedene Szenarien für Keystone Abrechnung
        url: "/concepts/misc-volume-billing.html"
      - title: Abrechnungszeitpläne
        url: "/concepts/billing-schedules.html"
  - title: Zugriff auf Keystone über die Digital Advisor REST-API
    entries:
    - title: Erste Schritte zum Abrufen von Keystone-Daten über die REST-API von Digital
        Advisor
      url: "/rest-api/retrieve-keystone-data-with-digital-advisor-rest-api.html"
    - title: Erstellen Sie Aktualisierungs- und Zugriffstoken
      url: "/rest-api/generate-tokens.html"
    - title: Eine Liste aller Kunden, die die Digital Advisor REST API verwenden
      url: "/rest-api/get-customer-list.html"
    - title: Kunden-Abonnements über die Digital Advisor REST-API abrufen
      url: "/rest-api/get-customer-subscriptions.html"
    - title: Details zur Kundennutzung erhalten Sie über die REST-API von Digital
        Advisor
      url: "/rest-api/get-customer-consumption.html"
  - title: Keystone Abonnementservices Version 1
    url: "/subscription-services-v1.html"
  - title: Keystone hilft Ihnen dabei
    url: "/concepts/gssc.html"
  - title: Rechtliche Hinweise
    url: "/legal-notices.html"
