---
settings:
  name: Keystone
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: de-de,us-en,ja-jp,ko-kr,zh-cn,zh-tw,es-es,fr-fr,it-it
sidebar:
  entries:
  - title: Keystone Dokumentation
    url: "/index.html"
  - title: Versionshinweise
    entries:
    - title: Neuerungen bei Keystone STaaS
      url: "/release-notes/whats-new.html"
    - title: Probleme wurden behoben
      url: "/release-notes/fixed-issues.html"
    - title: Bekannte Einschränkungen
      url: "/release-notes/known-limitations.html"
    - title: Bekannte Probleme
      url: "/release-notes/known-issues.html"
  - title: Willkommen bei Keystone
    url: "/concepts/overview.html"
  - title: Keystone wird eingerichtet und konfiguriert
    entries:
    - title: Was ist Keystone Collector
      url: "/installation/installation-overview.html"
    - title: Bereiten Sie Ihr System für die Installation von Keystone Collector vor
      entries:
      - title: Anforderungen für VMware vSphere
        url: "/installation/vapp-prereqs.html"
      - title: Linux-Anforderungen
        url: "/installation/linux-prereqs.html"
      - title: Anforderungen für ONTAP und StorageGRID
        url: "/installation/addl-req.html"
    - title: Installieren Sie Keystone Collector
      entries:
      - title: Implementierung von VMware vSphere
        url: "/installation/vapp-installation.html"
      - title: Linux-Installation
        url: "/installation/linux-installation.html"
      - title: Automatische Integritätsprüfung
        url: "/installation/validation.html"
    - title: Konfigurieren Sie Keystone Collector
      url: "/installation/configuration.html"
    - title: Systemzustand überwachen
      url: "/installation/monitor-health.html"
    - title: Aktualisieren Sie Keystone Collector
      url: "/installation/upgrade.html"
    - title: AutoSupport für Keystone konfigurieren
      url: "/installation/asup-config.html"
    - title: Daten, die zur Abrechnung erfasst werden
      url: "/installation/data-collection.html"
  - title: Hier können Sie das Keystone Dashboard anzeigen und Abonnements managen
    entries:
    - title: Das Keystone Dashboard finden Sie im Active IQ Digital Advisor
      url: "/integrations/keystone-aiq.html"
    - title: Verbrauchsdetails anzeigen und Berichte erstellen
      url: "/integrations/aiq-keystone-details.html"
    - title: Keystone Abonnements von BlueXP managen und
      url: "/integrations/keystone-cm.html"
  - title: Weitere Informationen zu Keystone
    entries:
    - title: Unterstützte Storage-Kapazität
      url: "/concepts/supported-storage-capacity.html"
    - title: Metriken und Definitionen
      url: "/concepts/metrics.html"
    - title: Unterstützter Storage in Keystone
      url: "/concepts/supported-storage-services.html"
    - title: Service-Level bei Keystone
      url: "/concepts/service-levels.html"
    - title: Add-on-Services
      entries:
      - title: Zusätzliche Services in Keystone STaaS
        url: "/concepts/add-on.html"
      - title: Daten-Tiering
        url: "/concepts/data-tiering.html"
      - title: Erweiterte Datensicherung
        url: "/concepts/adp.html"
      - title: USA Citizen Support (USCS)
        url: "/concepts/uscs.html"
      - title: Non-Returnable, Non-Volatile Komponenten und SnapLock-Compliance
        url: "/concepts/nrnvc.html"
      - title: Keystone und Equinix
        url: "/concepts/equinix.html"
  - title: Weitere Informationen zu Service-Leveln
    entries:
    - title: Quality of Service
      url: "/concepts/qos.html"
    - title: Kapazitätsanforderungen für Service Levels
      url: "/concepts/capacity-requirements.html"
    - title: SLA für Nachhaltigkeit
      url: "/concepts/sla-sustainability.html"
  - title: Abrechnung
    entries:
    - title: Keystone-Preisgestaltung
      url: "/concepts/pricing.html"
    - title: Abrechnung basiert auf der verplante Kapazität
      url: "/concepts/committed-capacity-billing.html"
    - title: Messung basierend auf verbrauchter Kapazität
      url: "/concepts/consumed-capacity-billing.html"
    - title: Abrechnung auf Basis von Burst-Nutzung
      url: "/concepts/burst-consumption-billing.html"
    - title: Die Abrechnung basiert auf verschiedenen Volume-Typen
      url: "/concepts/misc-volume-billing.html"
    - title: Abrechnungszeitpläne
      url: "/concepts/billing-schedules.html"
  - title: Partner- und vom Kunden betriebene Umgebungen zu optimieren
    url: "/concepts/operational-models.html"
  - title: Keystone Infrastruktur
    entries:
    - title: Detaillierte Informationen zur Infrastruktur
      url: "/concepts/infra.html"
    - title: Komponenten
      url: "/concepts/components.html"
    - title: Datenfluss
      url: "/concepts/data-flow.html"
  - title: NetApp Global Services Support Center
    url: "/concepts/gssc.html"
  - title: Rechtliche Hinweise
    url: "/legal-notices.html"
homepage:
  tiles:
  - title: Los geht's
    links:
    - title: Was ist NetApp Keystone?
      url: "/concepts/overview.html"
    - title: Installieren von Keystone Collector auf VMware vSphere
      url: "/installation/vapp-installation.html"
    - title: Installieren von Keystone Collector unter Linux
      url: "/installation/linux-installation.html"
    - title: Zeigen Sie Ihre Nutzung auf Digital Advisor an
      url: "/integrations/keystone-aiq.html"
    - title: Erstellen Sie Berichte über Ihre Nutzung
      url: "/integrations/aiq-keystone-details.html"
  - title: Unterstützte Services in Keystone
    links:
    - title: Keystone Service-Level
      url: "/concepts/service-levels.html"
    - title: Servicequalität (QoS)
      url: "/concepts/qos.html"
    - title: Was sind die Maßeinheiten?
      url: "/concepts/metrics.html"
    - title: Welcher Basis-Storage wird unterstützt?
      url: "/concepts/supported-storage-services.html"
    - title: Kann ich meine Ausgaben aus On-Premises-Umgebungen in die Cloud umverteilen?
      url: "/concepts/capacity-requirements.html#capacity-adjustments"
  - title: Keystone Preisgestaltung und Abrechnung
    links:
    - title: Informieren Sie sich über die Preise für Keystone
      url: "/concepts/pricing.html"
    - title: Meine Abrechnungspläne
      url: "/concepts/billing-schedules.html"
    - title: Abrechnung basiert auf der verplante Kapazität
      url: "/concepts/committed-capacity-billing.html"
    - title: Messung basierend auf verbrauchter Kapazität
      url: "/concepts/consumed-capacity-billing.html"
    - title: Was geschieht, wenn ich mehr als meine engagierte Kapazität verbraucht
        habe?
      url: "/concepts/burst-consumption-billing.html"
  - title: Mit Keystone Services mehr erreichen
    links:
    - title: Ihr Support-Team kennen (Keystone GSSC)
      url: "/concepts/gssc.html"
    - title: Was kann ich mit meinen kalten oder weniger genutzten Daten tun?
      url: "/concepts/data-tiering.html"
    - title: Wie kann ich meine Keystone Daten schützen?
      url: "/concepts/adp.html"
    - title: Keystone und BlueXP
      url: "/integrations/keystone-cm.html"
    - title: US Citizen Support
      url: "/concepts/uscs.html"
  - title: Erfahren Sie mehr
    links:
    - title: Keystone Abonnements in Version 1 (zuvor Keystone Flex Abonnements)
      url: https://docs.netapp.com/us-en/keystone/
    - title: Active IQ Digitalberater
      url: https://docs.netapp.com/us-en/active-iq/index.html
    - title: BlueXP
      url: https://docs.netapp.com/us-en/cloud-manager-family/
    - title: Active IQ Unified Manager
      url: https://docs.netapp.com/us-en/active-iq-unified-manager/
