---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'new features, release notes, enhancements, what"s new' 
summary: NetApp bietet Ihnen neue und erweiterte Funktionen in jeder neuen Version der Keystone STaaS Services. 
---
= Neuerungen bei Keystone STaaS
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp bietet Ihnen neue und erweiterte Funktionen in jeder neuen Version der Keystone STaaS Services.



== 30 Juni 2025



=== Veröffentlichung von Keystone Version 3 (v3).

Sie können jetzt Keystone Version 3 (v3), die neueste Version des NetApp Keystone STaaS-Angebots, abonnieren. Diese Version bietet zahlreiche Verbesserungen, darunter vereinfachte Performance-Service-Levels, zusätzliche Burst-Kapazitätsoptionen und flexible Abrechnungsintervalle. Diese Verbesserungen vereinfachen die Verwaltung, Optimierung und Skalierung von Speicherlösungen. Weitere Informationen finden Sie unter link:./concepts/metrics.html["Keystone STaaS-Dienste für v3"].



== 19 Juni 2025



=== Keystone-Dashboard in BlueXP

Sie können jetzt direkt von BlueXP auf das Keystone-Dashboard zugreifen. Dank dieser Integration können Sie alle Ihre Keystone-Abonnements und Ihre anderen NetApp-Dienste zentral überwachen, verwalten und im Auge behalten.

Mit dem Keystone-Dashboard in BlueXP können Sie:

* Zeigen Sie alle Ihre Abonnementdetails, Kapazitätsnutzung und Assets an einem Ort an.
* Verwalten Sie Abonnements ganz einfach und fordern Sie Änderungen an, wenn sich Ihre Anforderungen ändern.
* Bleiben Sie mit den neuesten Informationen zu Ihrer Speicherumgebung auf dem Laufenden.


Um zu beginnen, gehen Sie im linken Navigationsmenü von BlueXP zu *Speicher > Keystone*. Weitere Informationen finden Sie unter link:https://docs.netapp.com/us-en/keystone-staas/integrations/dashboard-overview.html["Übersicht über Keystone Dashboard"].



== 08 Januar 2025



=== Hinzufügen von Anzeigeoptionen für die tägliche aufgelaufene Datennutzung

Sie können jetzt die tägliche anrechenbare Burst-Datennutzung für einen monatlichen oder vierteljährlichen Abrechnungszeitraum im Diagramm- oder Tabellenformat anzeigen, indem Sie auf den Balken klicken, in dem die Rechnungsdaten angezeigt werden. Weitere Informationen finden Sie unter link:./integrations/consumption-tab.html#view-daily-accrued-burst-data-usage["Anzeige der täglichen angesammelten Burst-Datennutzung"].



== Bis 12. Dezember 2024



=== Umbenannte logische verwendete Spalte

Die Spalte *Logical used* im Register *Volume Details* innerhalb von *Volumes & Objects* wird nun in *Keystone Logical used* umbenannt.



=== Registerkarte „Enhanced Assets“

Die Registerkarte *Assets* im Fenster *Keystone Abonnements* hat nun zwei neue Unterregisterkarten: *ONTAP* und *StorageGRID*. Diese Unterregisterkarten bieten basierend auf Ihren Abonnements detaillierte Einblicke auf Cluster-Ebene für ONTAP und Informationen zur Grid-Ebene für StorageGRID. Weitere Informationen finden Sie unter link:./integrations/assets-tab.html["Registerkarte „Assets“"^].



=== Neue Option „Spalten ausblenden/einblenden“

Die Registerkarte *Volume Details* in *Volumes & Objects* enthält nun eine Option *Spalten ausblenden/einblenden*. Mit dieser Option können Sie Spalten auswählen oder abwählen, um die tabellarische Liste der Volumes Ihren Wünschen entsprechend anzupassen. Weitere Informationen finden Sie unter link:./integrations/volumes-objects-tab.html["Registerkarte Volumes  Objekte"^].



== 21. November 2024



=== Verbesserte aufgelaufene Burst-Kapazität in Rechnung gestellt

Sie können nun über die Option *fakturierte aufgelaufene Burst-Kapazität* quartalsweise aufgelaufene Burst-Nutzungsdaten anzeigen, wenn Sie sich für einen vierteljährlichen Abrechnungszeitraum entschieden haben. Weitere Informationen finden Sie unter link:./integrations/consumption-tab.html#view-accrued-burst["Anzeigen der angefallenen Burst-Rechnung"^].



=== Neue Spalten auf der Registerkarte „Volumendetails“

Um die Berechnung der logischen Nutzung noch übersichtlicher zu gestalten, wurden der Registerkarte *Volume Details* auf der Registerkarte *Volumes & Objekte* zwei neue Spalten hinzugefügt:

* *Logical AFS*: Zeigt die logische Kapazität an, die vom aktiven Dateisystem des Volumes verwendet wird.
* *Physischer Snapshot*: Zeigt den von den Snapshots verwendeten physischen Speicherplatz an.


Diese Spalten bieten eine bessere Übersichtlichkeit in der Spalte *Logical Used*, die die kombinierte logische Kapazität des aktiven Dateisystems des Volumes und den von Snapshots verwendeten physischen Speicherplatz anzeigt.



== Bis 11. November 2024



=== Verbesserte Berichterstellung

Mit der Funktion „Bericht“ in Digital Advisor können Sie jetzt einen konsolidierten Bericht erstellen, um die Details Ihrer Keystone-Daten anzuzeigen. Weitere Informationen finden Sie unter link:./integrations/options.html#generate-consolidated-report-from-digital-advisor["Erstellen Sie einen konsolidierten Bericht"^] .



== 10 Juli 2024



=== Änderungen an den Etiketten

Die Bezeichnung *Aktuelle Nutzung* wird in *Aktueller Verbrauch* geändert, und *Kapazitätstrend* wird in *Verbrauchstrend* geändert.



=== Suchleiste für Abonnements

Die Dropdown-Liste *Abonnements* über alle Registerkarten im Fenster *Keystone Abonnements* enthält jetzt eine Suchleiste. Sie können nach bestimmten Abonnements suchen, die in der Dropdown-Liste *Abonnements* aufgeführt sind.



== 27 Juni 2024



=== Konsistente Anzeige des Abonnements

Der Bildschirm *Keystone Subscriptions* wird aktualisiert, um die ausgewählte Abonnementnummer auf allen Registerkarten anzuzeigen.

* Wenn eine Registerkarte im Fenster *Keystone Abonnements* aktualisiert wird, navigiert der Bildschirm automatisch zur Registerkarte *Abonnements* und setzt alle Registerkarten auf das erste Abonnement zurück, das im Dropdown *Abonnement* aufgeführt ist.
* Wenn das ausgewählte Abonnement nicht für Leistungskennzahlen abonniert ist, wird auf der Registerkarte *Leistung* das erste Abonnement angezeigt, das im *Abonnement*-Dropdown bei der Navigation aufgeführt wird.




== 29 Mai 2024



=== Erweiterte Burst-Anzeige

Der *Burst*-Indikator im Nutzungsindex wird erweitert, um den prozentualen Wert für die Burst-Grenze anzuzeigen. Dieser Wert ändert sich je nach dem vereinbarten Burst-Limit für ein Abonnement. Sie können den Burst-Grenzwert auch auf der Registerkarte *Abonnements* anzeigen, indem Sie in der Spalte *Nutzungsstatus* den Mauszeiger über die Anzeige *Burst-Verwendung* bewegen.



=== Hinzufügen von Service-Leveln

Die Service-Level *CVO Primary* und *CVO Secondary* unterstützen Cloud Volumes ONTAP für Abonnements, die Ratenpläne mit Null gebuchter Kapazität oder solche mit einem Metro-Cluster konfiguriert haben.

* Sie können die Kapazitätsauslastungsgrafik für diese Service-Levels vom alten Dashboard des Widgets *Keystone Abonnements* und der Registerkarte *Kapazitätstrend* sowie detaillierte Nutzungsinformationen aus der Registerkarte *Aktuelle Nutzung* anzeigen.
* Auf der Registerkarte *Abonnements* werden diese Servicelevel als angezeigt `CVO (v2)` In der Spalte *Usage Type*, die die Identifizierung der Abrechnung nach diesen Service Levels ermöglicht.




=== Zoom-Funktion für kurzfristige Bursts

Die Registerkarte *Capacity Trend* enthält jetzt eine Zoom-in-Funktion, um die Details von kurzfristigen Bursts in den Nutzungdiagrammen anzuzeigen. Weitere Informationen finden Sie unter link:./integrations/consumption-tab.html["Registerkarte „Kapazitätstrend“"^].



=== Verbesserte Anzeige von Abonnements

Die Standardanzeige der Abonnements wird erweitert, um nach Tracking-ID zu sortieren. Die Abonnements auf der Registerkarte *Abonnements*, auch in den Dropdown-Menüs *Abonnement* und den CSV-Berichten, werden nun nach der alphabetischen Reihenfolge der Tracking-IDs in der Reihenfolge a, A, b, B usw. angezeigt.



=== Verbesserte Anzeige der aufgelaufenen Burst-Funktion

Die QuickInfo, die angezeigt wird, wenn Sie den Mauszeiger über dem Balkendiagramm für die Kapazitätsnutzung auf der Registerkarte *Kapazitätstrend* bewegen, zeigt nun die Art des aufgelaufenen Burst basierend auf der gebuchten Kapazität an. Es unterscheidet zwischen vorläufigen und fakturierten aufgelaufenen Burst und zeigt *provisorischer aufgelaufener Verbrauch* und *fakturierter aufgelaufener Verbrauch* für Abonnements mit Nulltarifen und *vorläufig aufgelaufener Burst* und *fakturierte aufgelaufene Burst* für diejenigen mit nicht-Null-zugesuchter Kapazität.



== 09 Mai 2024



=== Neue Spalten in CSV-Berichten

Die CSV-Berichte auf der Registerkarte *Capacity Trend* enthalten nun die Spalten *Subscription Number* und *Account Name* für verbesserte Details.



=== Spalte „Enhanced Usage Type“

Die Spalte *Usage Type* auf der Registerkarte *Subscriptions* wird erweitert, um logische und physische Nutzungen als kommagetrennte Werte für Abonnements anzuzeigen, die Service-Level für Datei und Objekt abdecken.



=== Zugriff auf Details zum Objekt-Storage über die Registerkarte „Volume Details“

Die Registerkarte *Volume Details* auf der Registerkarte *Volumes & Objekte* bietet nun Details zum Objektspeicher sowie Volume-Informationen für Abonnements, die Service-Level für Datei und Objekt enthalten. Sie können auf die Schaltfläche *Object Storage Details* im Register *Volume Details* klicken, um die Details anzuzeigen.



== 28 März 2024



=== Verbesserung der QoS-Richtlinienkonformität auf der Registerkarte „Volume Details“

Die Registerkarte *Volume Details* auf der Registerkarte *Volumes & Objekte* bietet jetzt einen besseren Einblick in die Einhaltung der QoS-Richtlinien. Die früher als *AQoS* bekannte Spalte wird in *Compliant* umbenannt, was angibt, ob die QoS-Richtlinie konform ist. Zusätzlich wird eine neue Spalte *QoS Policy Type* hinzugefügt, die angibt, ob die Policy fest oder adaptiv ist. Wenn keines der beiden Werte zutrifft, wird in der Spalte „_Not available_“ angezeigt. Weitere Informationen finden Sie unter link:./integrations/volumes-objects-tab.html["Registerkarte Volumes  Objekte"^].



=== Neue Spalte und vereinfachte Abonnementanzeige auf der Registerkarte „Volume Summary“

* Die Registerkarte *Volume Summary* auf der Registerkarte *Volumes & Objekte* enthält nun eine neue Spalte mit dem Titel *protected*. Diese Spalte enthält eine Anzahl der geschützten Volumes, die Ihren abonnierten Service-Levels zugeordnet sind. Wenn Sie auf die Anzahl der geschützten Volumes klicken, gelangen Sie auf die Registerkarte *Volume Details*, auf der Sie eine gefilterte Liste geschützter Volumes anzeigen können.
* Die Registerkarte *Volume Summary* wird aktualisiert, um nur Basisabonnements anzuzeigen, ohne Add-on-Dienste. Weitere Informationen finden Sie unter link:./integrations/volumes-objects-tab.html["Registerkarte Volumes  Objekte"^].




=== Ändern Sie auf der Registerkarte „Kapazitätstrend“ die Detailanzeige für aufgelaufene Burst

Die QuickInfo, die angezeigt wird, wenn Sie den Mauszeiger über dem Balkendiagramm für die Kapazitätsnutzung auf der Registerkarte *Kapazitätstrend* bewegen, zeigt die Details der aufgelaufenen Bursts für den aktuellen Monat an. Die Details werden in den vergangenen Monaten nicht verfügbar sein.



=== Verbesserter Zugriff zum Anzeigen historischer Daten für Keystone Abonnements

Sie können sich nun Verlaufsdaten ansehen, wenn ein Keystone Abonnement geändert oder verlängert wird. Sie können das Startdatum eines Abonnements auf ein vorheriges Datum einstellen, um Folgendes anzuzeigen:

* Daten zum Verbrauch und zur aufgelaufenen Burst-Nutzung von der Registerkarte *Kapazitätstrend*.
* Leistungsmetriken von ONTAP-Volumes aus der Registerkarte *Leistung*.


Die Daten werden basierend auf dem ausgewählten Startdatum des Abonnements angezeigt.



== 29 Februar 2024



=== Hinzufügen der Registerkarte „Assets“

Der Bildschirm *Keystone Subscriptions* enthält jetzt die Registerkarte *Assets*. Auf dieser neuen Registerkarte werden basierend auf Ihren Abonnements Informationen auf Cluster-Ebene angezeigt. Weitere Informationen finden Sie unter link:./integrations/assets-tab.html["Registerkarte „Assets“"^].



=== Verbesserungen an der Registerkarte Volumes & Objekte

Um Ihre ONTAP-Systemvolumes besser zu machen, wurden zwei neue Tabulatortasten, *Volume Summary* und *Volume Details*, auf der Registerkarte *Volumes* hinzugefügt. Die Registerkarte *Volume Summary* bietet eine Gesamtanzahl der Volumes, die Ihren abonnierten Service-Levels zugeordnet sind, einschließlich des AQoS-Compliance-Status und der Kapazitätsinformationen. Die Registerkarte *Volume Details* listet alle Volumes und ihre Besonderheiten auf. Weitere Informationen finden Sie unter link:./integrations/volumes-objects-tab.html["Registerkarte Volumes  Objekte"^].



=== Verbesserte Suchfunktionen auf Digital Advisor

Die Suchparameter auf dem *Digital Advisor*-Bildschirm enthalten nun die für Keystone Abonnements erstellten Keystone Abonnementnummern und Watchlisten. Sie können die ersten drei Zeichen einer Abonnementnummer oder eines Watchlist-Namens eingeben. Weitere Informationen finden Sie unter link:./integrations/keystone-aiq.html["Sehen Sie sich das Keystone-Dashboard auf Active IQ Digital Advisor an"^].



=== Zeitstempel der Verbrauchsdaten anzeigen

Sie können den Zeitstempel der Verbrauchsdaten (in UTC) auf dem alten Dashboard des Widgets *Keystone Abonnements* anzeigen.



== 13 Februar 2024



=== Möglichkeit, Abonnements anzuzeigen, die mit einem primären Abonnement verknüpft sind

Bei einigen Ihrer primären Abonnements können sekundäre verknüpfte Abonnements vorhanden sein. In diesem Fall wird die primäre Abonnementnummer weiterhin in der Spalte *Abonnementnummer* angezeigt, während die verknüpften Abonnementnummern in einer neuen Spalte *verknüpfte Abonnements* auf der Registerkarte *Abonnements* aufgeführt werden. Die Spalte *Verknüpfte Abonnements* steht Ihnen nur dann zur Verfügung, wenn Sie mit Abonnements verknüpft sind, und Sie können Informationsmeldungen sehen, die Sie darüber informieren.



== 11 Januar 2024



=== Die Rechnungsdaten wurden für aufgelaufene Burst zurückgegeben

Die Bezeichnungen für *aufgelaufene Burst* werden nun auf der Registerkarte *Kapazitätstrend* in *fakturierte aufgelaufene Burst* geändert. Wenn Sie diese Option auswählen, können Sie die monatlichen Diagramme für die berechneten aufgelaufenen Burst-Daten anzeigen. Weitere Informationen finden Sie unter link:./integrations/consumption-tab.html#view-accrued-burst["Anzeigen der angefallenen Burst-Rechnung"^].



=== Details des aufgelaufenen Verbrauchs für spezifische Tarifpläne

Wenn Sie ein Abonnement mit Tarifen mit _Null_ gebuchter Kapazität haben, können Sie die Details des aufgelaufenen Verbrauchs auf der Registerkarte *Kapazitätstrend* anzeigen. Bei Auswahl der Option *fakturierter aufgelaufener Verbrauch* können Sie die monatlichen Diagramme für die berechneten aufgelaufenen Verbrauchsdaten anzeigen.



== Bis 15. Dezember 2023



=== Möglichkeit zur Suche nach Watchlisten

Die Unterstützung für Watchlisten in Digital Advisor wurde auf Keystone Systeme erweitert. Sie können jetzt die Details der Abonnements für mehrere Kunden anzeigen, indem Sie mit Watchlisten suchen. Weitere Informationen über die Verwendung von Watchlisten in Keystone STaaS finden Sie unter link:./integrations/keystone-aiq.html#search-by-keystone-watchlists["Sie können nach Keystone Watchlisten suchen"^].



=== Datum in UTC-Zeitzone umgewandelt

Die auf den Registerkarten des Bildschirms *Keystone-Abonnements* von Digital Advisor zurückgegebenen Daten werden in UTC-Zeit (Server-Zeitzone) angezeigt. Wenn Sie ein Datum für die Abfrage eingeben, wird es automatisch als UTC-Zeit betrachtet. Weitere Informationen finden Sie unter link:./integrations/keystone-aiq.html["Keystone Abonnement-Dashboard und Berichterstellung"^].
