---
sidebar: sidebar 
permalink: concepts/billing-schedules.html 
keywords: billing schedules, schedule for payment 
summary: Keystone STaaS-Abonnements werden monatlich, vierteljährlich, halbjährlich oder jährlich abgerechnet. 
---
= Abrechnungszeitpläne
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Keystone STaaS-Abonnements werden monatlich, vierteljährlich, halbjährlich oder jährlich abgerechnet.



== Monatliche Abrechnung

Rechnungen werden monatlich versendet. Für den Monat, in dem die Dienstleistungen verfügbar sind, wird im nächsten Monat eine Rechnung verschickt. So wird beispielsweise die Rechnung für die im Januar verwendeten Dienste Anfang Februar zugestellt. Diese Rechnung beinhaltet die Gebühren für die verplante Kapazität und, falls zutreffend, eventuelle Burst-Nutzung.



== Vierteljährliche, halbjährliche und jährliche Abrechnung

Bei der vierteljährlichen, halbjährlichen und jährlichen Abrechnung ist der Ablauf ähnlich, mit leichten Abweichungen im Zeitablauf:

* *Vierteljährliche Abrechnung*: Zu Beginn jedes Abonnementquartals wird eine Rechnung über die Mindestzahlung der zugesagten Kapazität erstellt. Eine weitere Rechnung wird am Quartalsende für die angefallene Burst-Nutzung versandt.
* *Halbjährliche Abrechnung*: Zu Beginn jedes Halbjahres wird eine Rechnung über die Mindestzahlung der zugesagten Kapazität erstellt.  Für die angefallene Burst-Nutzung wird jeweils am Quartalsende eine weitere Rechnung verschickt.
* *Jährliche Abrechnung*: Zu Beginn jedes Abonnementjahres wird eine Rechnung über die Mindestzahlung der zugesagten Kapazität erstellt.  Für die angefallene Burst-Nutzung wird jeweils am Quartalsende eine weitere Rechnung verschickt.


Bei vierteljährlicher, halbjährlicher und jährlicher Abrechnung wird bei einer Änderung der zugesagten Kapazität während eines Abonnements am selben Tag eine Rechnung über die anteiligen Mindestzahlungen für den Rest des Abonnementjahres gesendet.  Die Abrechnung erfolgt ab dem Tag, an dem die Änderung der zugesagten Kapazität wirksam wird.
