---
sidebar: sidebar 
permalink: concepts/billing-schedules.html 
keywords: billing schedules, schedule for payment 
summary: Keystone STaaS Abonnements werden monatlich und jährlich abgerechnet. 
---
= Abrechnungszeitpläne
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Keystone STaaS-Abonnements in Version 3 (v3) werden monatlich, vierteljährlich, halbjährlich oder jährlich abgerechnet.



== Monatliche Abrechnung

Rechnungen werden monatlich versendet. Für den Monat, in dem die Dienstleistungen verfügbar sind, wird im nächsten Monat eine Rechnung verschickt. So wird beispielsweise die Rechnung für die im Januar verwendeten Dienste Anfang Februar zugestellt. Diese Rechnung beinhaltet die Gebühren für die verplante Kapazität und, falls zutreffend, eventuelle Burst-Nutzung.



== Vierteljährliche, halbjährliche und jährliche Abrechnung

Bei der vierteljährlichen, halbjährlichen und jährlichen Abrechnung ist der Prozess ähnlich, mit leichten zeitlichen Abweichungen:

* *Vierteljährliche Abrechnung*: Zu Beginn jedes Abonnementquartals wird eine Rechnung über die Mindestzahlung der zugesagten Kapazität erstellt. Eine weitere Rechnung wird am Quartalsende für die angefallene Burst-Nutzung versandt.
* *Halbjährliche Abrechnung*: Zu Beginn jedes Halbjahres wird eine Rechnung über die Mindestzahlung für die zugesagte Kapazität erstellt. Am Ende jedes Quartals wird eine weitere Rechnung für die angefallene Burst-Nutzung versandt.
* *Jährliche Abrechnung*: Zu Beginn jedes Abonnementjahres wird eine Rechnung über die Mindestzahlung der zugesagten Kapazität erstellt. Eine weitere Rechnung wird am Ende jedes Quartals für die angefallene Burst-Nutzung versandt.


Bei vierteljährlicher, halbjährlicher und jährlicher Abrechnung wird im Falle einer Änderung der zugesagten Kapazität während eines Abonnements am selben Tag eine Rechnung über die anteiligen Mindestzahlungen für den Rest des Abonnementjahres gesendet. Die Abrechnung wird ab dem Tag berechnet, an dem die Änderung der zugesagt Kapazität wirksam ist.
