---
sidebar: sidebar 
permalink: concepts/burst-consumption-billing.html 
keywords: burst consumption billing 
summary: Die Abrechnung von Keystone STaaS basiert auf der Burst-Kapazität – der von Ihnen verbrauchten Kapazität – zusätzlich zur gebuchten Kapazität im Abonnement. 
---
= Abrechnung auf Basis von Burst-Nutzung
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Die Abrechnung von Keystone STaaS basiert auf der „_Burst Capacity_“, d. h. der von Ihnen verbrauchten Kapazität zusätzlich zur gebuchten Kapazität im Abonnement.

Das Burst-Limit wird festgelegt und in Ihrer Keystone Vereinbarung angegeben. Normalerweise liegt er 20 % über der gebuchten Kapazität.

Die zugesagt Kapazität ist die Kapazität, die Ihnen beim Kauf des Abonnements zugesagt wird. Die zugesagte Kapazität und die Burst-Kapazität werden pro Leistungsservicelevel gemessen. Verbrauchte Kapazität ist die Kapazität, die Ihre Workloads tatsächlich nutzen.

Wenn die verbrauchte Kapazität größer ist als die zugesagte Kapazität für ein Leistungsservicelevel, wird der Burst-Verbrauch erfasst und entsprechend berechnet. Normalerweise liegt er 20 % über der gebuchten Kapazität. Der Verbrauch über der Burst-Kapazität wird als „oberhalb der Burst-Grenze“ angegeben.

Dieser Prozess erfolgt für jeden generierten Verbrauchsdatensatz. Der Burst-Verbrauch spiegelt daher sowohl die Höhe als auch die Dauer Ihrer zu verbrauchten Kapazitäten zusätzlich zu Ihren engagierten Kapazitäten wider. Weitere Informationen finden Sie unter link:../integrations/consumption-tab.html["Verbrauchstrends Ihrer Keystone-Abonnements anzeigen"].

Informationen zu verschiedenen in Keystone unterstützten Kapazitäten finden Sie unter link:../concepts/supported-storage-capacity.html["Unterstützte Storage-Kapazitäten in Keystone"].
