---
sidebar: sidebar 
permalink: concepts/burst-capacity.html 
keywords: burst consumption, add-on service, burst capacity, burst limit, NetApp Keystone 
summary: Ermöglicht Kunden, über ihre zugesagte Kapazität hinaus zusätzliche Speicherkapazität zu nutzen. 
---
= Zusatzkapazität für Keystone -Abonnements
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Sie können den Zusatzservice für Burst-Kapazität als Teil Ihres NetApp Keystone-Abonnements wählen. Mit diesem Service können Sie Ihre Burst-Kapazitätsgrenzen auf 40 % oder 60 % über Ihre zugesagte Kapazität erhöhen und so unerwartete Spitzen im Workload-Bedarf flexibel bewältigen.

Die sogenannte Burst-Kapazität bezeichnet die zusätzliche Speicherkapazität, die über die im Abonnement festgelegte Kapazität hinaus genutzt werden kann. Sie wird pro Leistungsservicelevel gemessen und abgerechnet. Standardmäßig ist Ihr Burst-Limit auf 20 % über der festgelegten Kapazität eingestellt. Sie können dieses Limit jedoch auf 40 % oder 60 % erhöhen, allerdings nur für die Datenspeichertypen Unified und Block-Optimized.

Um Ihr Burst-Limit auf 40 % oder 60 % zu ändern, wenden Sie sich an das NetApp Keystone-Supportteam.

Weitere Informationen zur Abrechnung der Burst-Kapazität finden Sie unter link:../concepts/burst-consumption-billing.html["Abrechnung auf Basis von Burst-Nutzung"] .
