---
sidebar: sidebar 
permalink: concepts/committed-capacity-billing.html 
keywords: Billing based on committed capacity, committed capacity billing 
summary: Unterstützte Speicherkapazitäten 
---
= Abrechnung basiert auf der verplante Kapazität
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NetApp Keystone (Keystone) Abrechnung basiert auf der Ihnen als Teil des Keystone Abonnements zugesagt Kapazität.

Bei der Bereitstellung der Kapazität handelt es sich um die Kapazität, die für ein bestimmtes Servicelevel beim Erwerb des Abonnements festgelegt ist. Die zugesagt Kapazität kann die Gesamtkapazität für verschiedene Service Level in einem einzelnen Abonnement sein, wie Sie und NetApp/Partner akzeptiert haben. Diese Kapazität wird in jeder Keystone-Bestellung angegeben und wird unabhängig vom tatsächlichen Kapazitätsverbrauch in Rechnung gestellt.

Informationen zu verschiedenen in Keystone unterstützten Kapazitäten finden Sie unter link:../concepts/supported-storage-capacity.html["Unterstützte Storage-Kapazitäten in Keystone"].
