---
sidebar: sidebar 
permalink: concepts/components.html 
keywords: infrastructure component, deployment requirement, installation requirement 
summary: Infrastrukturkomponenten 
---
= Komponenten für die Implementierung
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
In diesem Abschnitt werden die erforderlichen Komponenten zur Aktivierung von NetApp Keystone STaaS-Services in Ihrer Umgebung aufgeführt.



== Standortanforderungen

Es gibt einige standortspezifische Anforderungen wie Platz, Racks, PDUs, Strom, Und Kühlung mit zusätzlichen Netzwerk- und Sicherheitsanforderungen.



=== Platzbedarf

Stellfläche für das Hosten der Keystone Infrastruktur-Ausrüstung (die von den Kunden bereitgestellt werden) NetApp stellt die Gewichtsspezifikationen auf Basis der endgültigen Konfiguration bereit.



=== Racks

Vier Postregale im kundengesteuerten Angebot (wird vom Kunden bereitgestellt). Beim NetApp Angebot können NetApp oder der Kunde die Racks je nach Anforderungen bereitstellen. NetApp bietet 42 enge Racks.



=== PDUs

Sie sollten die Stromverteiler (PDUs) bereitstellen, die an zwei separate, geschützte Schaltkreise mit ausreichend C13-Steckdosen angeschlossen sind. Im kundengesteuerten Angebot sind in einigen Fällen C19-Steckdosen erforderlich. Beim NetApp Angebot können NetApp oder der Kunde die PDUs je nach Anforderungen bereitstellen.



=== Strom

Sie sollten die erforderliche Stromversorgung angeben. NetApp stellt die Spezifikationen für die Stromversorgung auf Basis der Nennleistung von 200 V bereit (typisch A, max A, typisch W, max W, Netzkabel, Und Menge), basierend auf der endgültigen Konfiguration. Alle Komponenten verfügen über redundante Netzteile. NetApp stellt die Stromkabel im Schrank bereit.



=== Kühlung

NetApp stellt basierend auf der endgültigen Konfiguration und den Anforderungen die Spezifikationen für die Kühlungsanforderungen (BTU, max BTU) bereit.



=== Storage Virtual Machines

Für die Implementierung von Keystone Collector und dem AIOPs-Lösungs-Gateway ist eine Storage Virtual Machine (Storage-VM) erforderlich. Die Voraussetzungen für die Installation von Keystone Collector sind hier verfügbar: link:..//installation/installation-overview.html["Installationsanleitung für Keystone Collector"]. Die anderen Anforderungen werden während der Implementierung gemeinsam genutzt.



=== Implementierungsoptionen

Der Keystone Collector kann auf folgende Weise bereitgestellt werden:

* VMware OVA-Vorlage (VMware vCenter Server 6.7 oder höher erforderlich)
* Der Kunde stellt Red hat Enterprise Linux 7 oder 8 oder CentOS 7 Linux Server zur Verfügung. Die Keystone Software wird über installiert `.rpm` Installationsprozess.


Das Gateway für die AIOPs-Lösung wird in folgender Konfiguration bereitgestellt:

* VMware OVA-Vorlage (VMware vCenter Server 6.7 oder höher erforderlich)
* Bootfähiges .iso-Installationsprogramm für
+
** Citrix XenServer
** Microsoft Hyper-V
** Kernel-Based Virtual Machine (Linux KVM)






=== Netzwerkbetrieb

Für den Betrieb und die Wartung des Keystone Collector und des AIOPs Solution Gateways ist ausgehender Zugriff auf die folgenden Services erforderlich:

* support.netapp.com (Upload der Nutzungsdaten)
* keystone.netapp.com (Software-Updates)
* Hub.Docker.io (Software-Updates)


Je nach Kundenanforderungen und den verwendeten Storage Controllern bietet NetApp am Standort des Kunden Konnektivität mit 10 GB, 40 GB und 100 GB.

NetApp liefert nur die erforderlichen Transceiver für von NetApp zur Verfügung gestellte Infrastrukturgeräte. Sie sollten Transceiver zur Verfügung stellen, die für Kundengeräte und zur Verkabelung zu den von NetApp bereitgestellten Keystone Infrastrukturgeräten erforderlich sind.



== Remote-Zugriff

Zwischen der im Datacenter des Kunden installierten Storage-Infrastruktur oder den Services des Kunden, die sich im Besitz des Kunden befinden, und dem Keystone Operations Center ist Netzwerkkonnektivität erforderlich. Der Kunde ist verantwortlich für die Bereitstellung der Computing- und Virtual Machines sowie der Internetservices. Das Netzwerk-Design sollte über ein sicheres Protokoll verfügen und Firewall-Richtlinien werden sowohl von NetApp als auch von Kunden genehmigt.

NetApp muss auf die Hardware- und Softwarekomponenten zugreifen, die für Monitoring und Management installiert sind, um Services wie Monitoring und Abrechnung für Keystone Kunden bereitzustellen. Die häufigste Methode ist die Einrichtung einer VPN-Verbindung (Virtual Private Network) zum Kundennetzwerk und der Zugriff auf die erforderlichen Daten. Um die von Kunden vermeintliche Komplexität durch das Öffnen von Firewall-Ports zu neuen Services zu überwinden, initiieren die Überwachungstools eine externe Verbindung. NetApp Cloud-Applikationen, wie AIOPs Solution und Zuora, nutzen diese Verbindung, um ihre jeweiligen Services auszuführen. Diese Methode erfüllt die Kundenanforderung, keine Firewall-Ports zu öffnen, obwohl sie Zugriff auf die Überwachungskomponenten bietet, die Teil dieses Services sind.
