---
sidebar: sidebar 
permalink: concepts/components.html 
keywords: infrastructure component, deployment requirement, installation requirement 
summary: Erfahren Sie mehr über die Komponenten, die für die Aktivierung von NetApp Keystone STaaS Services in Ihrer Umgebung erforderlich sind. 
---
= Für die Implementierung erforderliche Komponenten
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Für die Aktivierung von NetApp Keystone STaaS Services in Ihrer Umgebung sind mehrere Komponenten erforderlich. Bevor Sie beginnen, sollten Sie sich die Details zu diesen Komponenten ansehen.



== Standortanforderungen

Es gibt einige standortspezifische Anforderungen wie Platz, Racks, PDUs, Strom, Und Kühlung mit zusätzlichen Netzwerk- und Sicherheitsanforderungen.



=== Platzbedarf

Stellfläche für das Hosten der Keystone Infrastruktur-Ausrüstung (die von den Kunden bereitgestellt werden) NetApp stellt die Gewichtsspezifikationen auf Basis der endgültigen Konfiguration bereit.



=== Racks

Vier Postregale im kundengesteuerten Angebot (wird vom Kunden bereitgestellt). Beim NetApp Angebot können NetApp oder der Kunde die Racks je nach Anforderungen bereitstellen. NetApp bietet 42 enge Racks.



=== PDUs

Sie sollten die Stromverteiler (PDUs) bereitstellen, die an zwei separate, geschützte Schaltkreise mit ausreichend C13-Steckdosen angeschlossen sind. Im kundengesteuerten Angebot sind in einigen Fällen C19-Steckdosen erforderlich. Beim NetApp Angebot können NetApp oder der Kunde die PDUs je nach Anforderungen bereitstellen.



=== Strom

Sie sollten die erforderliche Stromversorgung angeben. NetApp stellt die Spezifikationen für die Stromversorgung auf Basis der Nennleistung von 200 V bereit (typisch A, max A, typisch W, max W, Netzkabel, Und Menge), basierend auf der endgültigen Konfiguration. Alle Komponenten verfügen über redundante Netzteile. NetApp stellt die Stromkabel im Schrank bereit.



=== Kühlung

NetApp stellt basierend auf der endgültigen Konfiguration und den Anforderungen die Spezifikationen für die Kühlungsanforderungen (BTU, max BTU) bereit.



=== Virtual Machines

Virtual Machines sind für die Implementierung von Keystone Collector und ITOM Collector erforderlich. Informationen zu Installationsvoraussetzungen finden Sie unter link:../installation/installation-overview.html["Installationsanleitung für Keystone Collector"] und link:../installation/itom-prereqs.html["Installationsanforderungen für ITOM Collector"]. Die anderen Anforderungen werden während der Implementierung gemeinsam genutzt.



=== Implementierungsoptionen

Keystone Collector kann durch die folgenden Methoden implementiert werden:

* VMware OVA-Vorlage (VMware vCenter Server 6.7 oder höher erforderlich)
* Der Kunde stellt einen Linux-Server bereit, der auf einem der folgenden Betriebssysteme läuft: Debian 12, Red hat Enterprise Linux 8.6 oder höher 8.x-Versionen oder CentOS 7 (nur für bestehende Umgebungen). Die Keystone Software wird je nach Linux Distribution mit dem Paket oder `.rpm` installiert `.deb`.


ITOM Collector kann über die folgenden Methoden bereitgestellt werden:

* Der Kunde stellt einen Linux-Server bereit, der unter Debian 12, Ubuntu 20.04 LTS, Red hat Enterprise Linux (RHEL) 8.x, Amazon Linux 2023 oder neueren Versionen läuft.
* Der Kunde stellt einen Windows-Server bereit, auf dem Windows Server 2016 oder neuere Versionen ausgeführt werden.
+

TIP: Die empfohlenen Betriebssysteme sind Debian 12, Windows Server 2016 oder neuere Versionen.





=== Netzwerkbetrieb

Der ausgehende Zugriff auf _Keystone.NetApp.com_ ist für Softwareupdates und Uploads von Nutzungsdaten erforderlich, die für den Betrieb und die Wartung des Keystone Collectors und AIOps Solution Gateways unerlässlich sind.

Je nach Kundenanforderungen und den verwendeten Storage Controllern bietet NetApp am Standort des Kunden Konnektivität mit 10 GB, 40 GB und 100 GB.

NetApp liefert nur die erforderlichen Transceiver für von NetApp zur Verfügung gestellte Infrastrukturgeräte. Sie sollten Transceiver zur Verfügung stellen, die für Kundengeräte und zur Verkabelung zu den von NetApp bereitgestellten Keystone Infrastrukturgeräten erforderlich sind.



== Remote-Zugriff

Zwischen der im Datacenter des Kunden installierten Storage-Infrastruktur oder den Services des Kunden, die sich im Besitz des Kunden befinden, und dem Keystone Operations Center ist Netzwerkkonnektivität erforderlich. Der Kunde ist verantwortlich für die Bereitstellung der Computing- und Virtual Machines sowie der Internetservices. Der Kunde ist auch für OS-Patches (nicht-OVA-basierte Bereitstellungen) und Sicherheitshärtungen auf der Grundlage interner Sicherheitsrichtlinien verantwortlich. Das Netzwerk-Design sollte über ein sicheres Protokoll verfügen und Firewall-Richtlinien werden sowohl von NetApp als auch von Kunden genehmigt.

NetApp muss auf die Hardware- und Softwarekomponenten zugreifen, die für Monitoring und Management installiert sind, um Services wie Monitoring und Abrechnung für Keystone Kunden bereitzustellen. Die häufigste Methode ist die Einrichtung einer VPN-Verbindung (Virtual Private Network) zum Kundennetzwerk und der Zugriff auf die erforderlichen Daten. Um die von Kunden vermeintliche Komplexität durch das Öffnen von Firewall-Ports zu neuen Services zu überwinden, initiieren die Überwachungstools eine externe Verbindung. NetApp Cloud-Anwendungen, wie ITOM Monitoring Solution und Zuora, nutzen diese Verbindung, um ihre jeweiligen Services auszuführen. Diese Methode erfüllt die Kundenanforderung, keine Firewall-Ports zu öffnen, obwohl sie Zugriff auf die Überwachungskomponenten bietet, die Teil dieses Services sind.
