---
sidebar: sidebar 
permalink: concepts/consumed-capacity-billing.html 
keywords: consumed capacity billing, billing and consumed capacity 
summary: Abrechnung basiert auf verbrauchter Kapazität 
---
= Messung basierend auf verbrauchter Kapazität
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Keystone bietet außerdem eine Nutzungsmessung basierend auf der Kapazität, die Sie während der Service-Nutzung verbraucht haben.

Im Rahmen der Keystone-Serviceimplementierung überwacht und misst NetApp fortlaufend die Nutzung des Service. Alle fünf Minuten wird ein Verbrauchsdatensatz durch das System generiert, in dem die aktuelle verbrauchte Kapazität für Ihr Abonnement detailliert aufgeführt wird. Diese Daten werden über den Abrechnungszeitraum hinweg aggregiert, um Rechnungen und Nutzungsberichte zu erstellen.

Informationen zu verschiedenen in Keystone unterstützten Kapazitäten finden Sie unter link:../concepts/supported-storage-capacity.html["Unterstützte Storage-Kapazitäten in Keystone"].
