---
sidebar: sidebar 
permalink: concepts/consumed-capacity-billing-v2.html 
keywords: consumed capacity billing, billing and consumed capacity 
summary: Verbrauchte Kapazität ist die Kapazität, die Workloads während der Service-Nutzung tatsächlich nutzen. 
---
= Messung basierend auf verbrauchter Kapazität
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Keystone STaaS bietet eine Messung basierend auf der Kapazität, die Sie während der Service-Nutzung verbraucht. Verbrauchte Kapazität ist die Kapazität, die Ihre Workloads tatsächlich nutzen.

Im Rahmen der Keystone-Serviceimplementierung überwacht und misst NetApp fortlaufend die Nutzung des Service. Mindestens einmal alle fünf Minuten wird vom System ein Verbrauchsdatensatz erstellt, in dem die aktuell verbrauchte Kapazität für Ihr Abonnement detailliert aufgeführt wird. Diese Daten werden über den Abrechnungszeitraum hinweg aggregiert, um Rechnungen und Nutzungsberichte zu erstellen.

Informationen zu den verschiedenen in Keystone unterstützten Kapazitäten finden Sie unter link:../concepts/supported-storage-capacity-v2.html["Unterstützte Storage-Kapazitäten in Keystone"] .
