---
sidebar: sidebar 
permalink: concepts/data-tiering.html 
keywords: add-on services, add-on, data tiering 
summary: Der Daten-Tiering Add-on Service identifiziert selten genutzte Daten und führt sie auf unterstützten Storage zu. 
---
= Mehr über Daten-Tiering erfahren
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Die Keystone STaaS-Standardservices für File- und Block-Storage umfassen Tiering-Funktionen zur Identifizierung seltener genutzter Daten und Tiering-Stufen auf von Keystone STaaS unterstützter NetApp Cold-Storage. Daten-Tiering kann als Add-on-Service genutzt werden, um kalte Daten auf jeden von Keystone STaaS unterstützten Storage anderer Anbieter zu verschieben.

unter link:../concepts/service-levels.html["Leistungsservicelevel in Keystone"] .


NOTE: Der Tiering-Add-On-Dienst ist nur erforderlich, wenn Daten auf Nicht- NetApp -Speicher wie Amazon Web Services (AWS) S3, Azure Blob, Google Cloud Platform (GCP) und andere von Keystone STaaS unterstützte, S3-kompatible Objektspeicher von Drittanbietern gestaffelt werden.

Die Tiering-Funktion nutzt die NetApp FabricPool-Technologie, die ein automatisiertes Tiering von selten genutzten Daten auf Objekt-Storage-Tiers vor Ort und an anderen Standorten ermöglicht.

Der zusätzliche Daten-Tiering-Dienst ermöglicht das Tiering von den Tiers Extreme, Premium, Performance, Standard und Value zu einem Objektspeicherziel. Das Verhältnis zwischen den zu stufenden heißen und kalten Daten ist nicht festgelegt und jede Stufe wird separat gemessen und in Rechnung gestellt.

Wenn das Ziel für Cold-Storage Tier beispielsweise lautet:

* Keystone STaaS Value Tier, Keystone STaaS StorageGRID Object Tier oder vorhandenes StorageGRID Webscale (SGWS)-Grid (im Besitz des Kunden) – Es fallen keine zusätzlichen Kosten an; es ist Teil des Standarddienstes.
* Public Cloud (AWS, Azure, Google) oder von Keystone STaaS unterstützter Objekt-Storage von Drittanbietern – Es gibt eine zusätzliche Gebühr für Datenkapazität, die auf Cold-Storage-Ziel verschoben wird.


Die Gebühren für zusätzliche Tiering-Services gelten für die gesamte Abonnementlaufzeit.


NOTE: Die von Cloud Volumes ONTAP benötigten Hyperscaler-basierten Rechen-, Speicher- und Netzwerkdienste werden von NetApp nicht als Teil der Keystone STaaS-Abonnements bereitgestellt. Diese Dienste müssen direkt von Hyperscaler-Cloud-Service-Anbietern bezogen werden.

*Verwandte Informationen*

link:https://kb.netapp.com/hybrid/Keystone/AIQ_Dashboard/How_to_approximate_Keystone_Consumption_with_Data_Tiering_(FabricPool)_through_the_ONTAP_cli["Ungefähre Angaben zur Keystone Nutzung mit Daten-Tiering (FabricPool) mithilfe der ONTAP CLI"^]
