---
sidebar: sidebar 
permalink: concepts/data-tiering.html 
keywords: add-on services, add-on, data tiering 
summary: Add-on, zusätzliche Service-Details, Daten-Tiering 
---
= Daten-Tiering
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Die Keystone STaaS-Standardservices für File- und Block-Storage umfassen Tiering-Funktionen zur Identifizierung seltener genutzter Daten und Tiering-Stufen auf von Keystone STaaS unterstützter NetApp Cold-Storage. Sie können Daten-Tiering als Add-on-Service nutzen, wenn Sie Ihre kalten Daten auf einen beliebigen Keystone STaaS-unterstützten Storage anderer Anbieter verschieben möchten.

Informationen zu Standard- und Add-on-Services finden Sie unter link:../concepts/supported-storage-services.html["Keystone STaaS Services"]. Informationen zu Service-Levels finden Sie unter link:../concepts/service-levels.html["Service-Level in Keystone"].

Der Tiering-Add-on Service ist nur erforderlich, wenn Daten über Tiering auf Drittanbieter-Storage verschoben werden, z. B. Amazon Web Services (AWS) S3, Azure Blob, Google Cloud Platform (GCP) und andere, von Keystone STaaS unterstützte, S3-kompatible Objekt-Storage von Drittanbietern.

Die Tiering-Funktion nutzt die NetApp FabricPool-Technologie, die ein automatisiertes Tiering von selten genutzten Daten auf Objekt-Storage-Tiers vor Ort und an anderen Standorten ermöglicht.

Der Daten-Tiering-Service mit Add-on ermöglicht das Tiering von Extreme-, Premium-, Performance-, Standard- und Value-Tier zu einem Objekt-Storage-Ziel. Das Verhältnis der „Hot:Cold Data“-Tiers ist nicht fest festgelegt und jede Tier wird separat gemessen und in Rechnung gestellt.

Wenn das Ziel für Cold-Storage Tier beispielsweise lautet:

* Keystone STaaS-Objekt-Tier, Keystone STaaS-StorageGRID-Objekt-Tier oder vorhandenes SGWS-Grid (Eigentum des Kunden) – Es fallen keine zusätzlichen Kosten an und es ist Teil des Standard-Service.
* Public Cloud (AWS, Azure, Google) oder von Keystone STaaS unterstützter Objekt-Storage von Drittanbietern – Es gibt eine zusätzliche Gebühr für Datenkapazität, die auf Cold-Storage-Ziel verschoben wird.


Die Gebühren für zusätzliche Tiering-Services gelten für die gesamte Abonnementlaufzeit.


NOTE: Die von Cloud Volumes ONTAP benötigten Hyperscale-basierten Computing-, Storage- und Netzwerk-Services werden von NetApp nicht als Bestandteil der Keystone STaaS-Abonnements bereitgestellt. Diese Services müssen direkt von Hyperscale-Cloud-Service-Providern in Anspruch genommen werden.
