---
sidebar: sidebar 
permalink: concepts/gssc.html 
keywords: Global Services Support Center, GSSC, Keystone support, service request, support ticket 
summary: NetApp Global Services Support Center GSSC 
---
= NetApp Global Services Support Center
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Das NetApp Global Services and Support Center (GSSC) und der NetApp Keystone Success Manager (KSM) stellen Services für Keystone Abonnements bereit.



== NetApp Global Services und Support Center (GSSC)

NetApp bietet NetApp Keystone Kunden Remote operative Services. Diese Services umfassen Betriebsdisziplinen zu Storage Management-Aktivitäten. Zu diesen Services gehören Asset- und Konfigurationsmanagement, Kapazitäts- und Performance-Management, Änderungsmanagement, Ereignisse, Vorfall- und Problemmanagement, Bearbeitung von Serviceanfragen und Berichterstellung. NetApp weist nach Bedarf einen Kontrollstatus auf und weist entsprechende Nachweise auf.



== Kontakt für weitere Informationen und Support

Das NetApp Global Services and Support Center (GSSC) Team unterstützt die Services hauptsächlich für NetApp Keystone Kunden. Mithilfe der folgenden Informationen können Sie sich an das Support-Team wenden.

* Ansprechpartner für den weltweiten Service:https://www.netapp.com/us/contact-us/support.aspx[]
* Falls Sie über einen offenen Fall/ein Ticket verfügen, der eskaliert werden muss, senden Sie eine E-Mail an eine der folgenden Adressen: keystone.services@netapp.com keystone.escalations@netapp.com
* NetApp nutzt OpsRamp, eine Cloud-basierte Remote-Gateway-Lösung, um proaktiv zu überwachen und eine Verbindung zur NetApp Keystone-Umgebung zur Fehlerbehebung herzustellen. Informationen zu OpsRamp finden Sie unter https://www.opsramp.com/#[].



NOTE: In einem von Partnern betriebenen Modell werden die Service-Anfragen des Mandanten und des Submandanten dem Service-Desk des Partners zugewiesen. Das Support-Tool des Partners kann mit OpsRamp- und GSSC-Applikationen integriert werden. Es werden nur L3-Probleme über GSSC an NetApp eskaliert.

Weitere Informationen zu Keystone Services finden Sie unter:

* NetApp Keystonehttps://www.netapp.com/us/solutions/keystone/index.aspx["https://www.netapp.com/us/solutions/keystone/index.aspx"^]
* NetApp Produktdokumentationhttps://docs.netapp.com["https://docs.netapp.com"^]




== GSSC-Überwachung

Das NetApp Global Services and Support Center (GSSC) überwacht den Zustand Ihrer Produkte und abonnierten Services, bietet Remote-Support und arbeitet mit Ihrem Keystone Success Manager zusammen. Alle Mitarbeiter, die die Produkte im Zusammenhang mit den entsprechenden Keystone Abonnement-Bestellungen überwachen, sind US-Bürger, die in den USA tätig sind Bereitgestellt.

.Keystone Success Manager
Der Keystone Success Manager (KSM) arbeitet eng mit Ihnen zusammen, um Ihre Keystone-Services zu nutzen. Er aktualisiert Sie auf wöchentlichen bzw. monatlichen Abrechnungen und Betriebsberichten. Die Verantwortlichkeiten werden in Ihrer NetApp Keystone-Vereinbarung festgelegt.



== Serviceanforderungen werden erstellt

Wenn Sie während des Onboarding Zugangsdaten für den Zugriff auf NetApp Keystone ServiceNow und die Verwendung von erhalten haben, können Sie über das Portal Serviceanfragen bei Problemen Ihrer Keystone Abonnements generieren:

https://netappgssc.service-now.com/csm[]

Stellen Sie sicher, dass Sie die Systemdetails, Protokolle und zugehörigen Informationen bereit haben, bevor Sie die Serviceanfrage senden. Wenn Sie eine Service-Anfrage stellen, erhält das GSSC Team das Support-Ticket und greift auf die Informationen zur Fehlerbehebung zu. Sie können Ihr ServiceNow-Ticket verfolgen, um den Status und die Lösung zu kennen.

Informationen zum Hinzufügen von Supportpaketen finden Sie unter link:../installation/monitor-health.html["Support Bundle generieren und sammeln"].
