---
sidebar: sidebar 
permalink: concepts/metrics.html 
keywords: metrics, GiB, IOPS, latency, durability 
summary: Berechnungen von Kennzahlen und Definitionen der Keystone Services 
---
= Metriken und Definitionen für Keystone Services
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Die folgenden Begriffe und Definitionen werden im NetApp Keystone (Keystone) STaaS Service zur Messung von Kennzahlen verwendet:

* Kapazität Maßeinheiten: Gib, tib und PiB
* I/O-Dichte: IOPS/tib: Anzahl der pro Sekunde verarbeiteten Input/Output-Vorgänge basierend auf dem gesamten Speicherplatz, der vom Workload in Tebibyte verbraucht wird.
* Service-Verfügbarkeit
* Datenaufbewahrung bei präzisen Datenzugriffs
* Latenz und Geschwindigkeit




== Kennzahlenmessung

* *Kapazitätsmessung in gib, tib und PiB*: Messungen der Datenspeicherkapazität mit Basis von 1024 (1 gib = 1024^3^ Byte, 1 tib = 1024^4^ Byte und 1 PiB = 1024^5^ Byte).
* *Operations Zählerdiagramm in IOPS/tib*: Die Protokollvorgänge pro Sekunde, angefordert von der Applikation, geteilt durch die Größe des von Workloads verwendeten Volumes.
* *Verfügbarkeit*: Gemessen als Prozentsatz der vom Dienst erfolgreich beantworteten E/A-Anfragen, geteilt durch die Gesamtzahl der an den Dienst gestellten I/O-Anfragen. Dies wird bei der Serviceeingrenzung in einem Monat gemessen und schließt nicht die geplante Ausfallzeit oder Nichtverfügbarkeit der vom Kunden bereitgestellten Einrichtungen, Netzwerke oder sonstigen Dienste ein.
* *Langlebigkeit*: Prozentsatz der Daten, auf die ohne Verlust der Treue zugegriffen wird, ausgenommen vom Kunden verursachte Löschung oder Beschädigung.
* *Latenz*: Zeit zur Bedienung einer von einem Client erhaltenen I/O-Anfrage, gemessen an der Serviceeingrenzung (Storage-Controller-I/O-Port).




=== Metriken für Durchsatz-Performance

Kennzahlen für Durchsatz gelten nur für Datei- und Block-Services, die auf folgenden Kriterien basieren:

* Blockgrößen von 32 KB
* 70 % Lese-/30 % Schreib-I/O-Kombination




=== Variationen in der I/O-Dichte

Die in IOPS/tib und/oder MB/s/tib berechnete I/O-Dichte variiert basierend auf den folgenden Faktoren:

* Workload-Merkmale
* Latenz, ohne Folgendes:
+
** Applikationslatenz
** Host-Latenz
** Latenz im Kundennetzwerk bei Übertragung der Daten an und von den Controller-Ports
** Overheadlatenz im Zusammenhang mit der Datenübertragung an den Objektspeicher im Fall von FabricPool
** Die durch die QoS automatisch angewandte Latenz wird I/O-Prozesse innerhalb der maximalen Service-Level-Maximalwerte beibehalten


* Daten der Benutzer- und Snapshot-Kopie, die als Teil der genutzten Kapazität gezählt werden
* Das zugewiesene absolute Minimum an IOPS auf jedem ONTAP Volume, unabhängig von der Datenmenge im Volume:
+
** Extrem: 1,000 IOPS
** Premium: 500 IOPS
** Performance, Standard und Wert: 75 IOPS


* Bei Nutzung der Add-on-Services für Advanced Data Protection gilt die Ziellatenz nur für die Bearbeitung von I/O-Anfragen vom lokalen Storage.




=== Volume AQoS

Für jedes ONTAP Volume sollte eine entsprechende adaptive Quality of Service (AQoS)-Richtlinie angewendet werden. Andernfalls wird die Kapazität in jedem Volume, auf das keine AQoS-Richtlinie angewendet wird, mit der Rate des höchsten Service-Level abgerechnet.
