---
sidebar: sidebar 
permalink: concepts/metrics.html 
keywords: metrics, GiB, IOPS, latency, durability, v3, version 3 
summary: Der NetApp Keystone STaaS Service verwendet mehrere Begriffe zur Messung von Kennzahlen. Möglicherweise möchten Sie mehr über diese Bedingungen erfahren, wenn Sie Keystone für Version 3 des Dienstes verwenden. 
---
= Speichermetriken und Definitionen in Keystone verstehen
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Lernen Sie die wichtigsten Begriffe kennen, die Keystone STaaS zur Messung und Berichterstattung über Ihr Speicherabonnement verwendet, einschließlich Kapazitätseinheiten, Leistungskennzahlen und Verfügbarkeitsdefinitionen.



== Kennzahlenmessung

* *Kapazitätsmessung in GiB, TiB und PiB*: Messungen der Datenspeicherkapazität auf Basis von 1024 (1 GiB = 1024^3^ Bytes, 1 TiB = 1024^4^ Bytes und 1 PiB = 1024^5^ Bytes).
* *Operationszählerdiagramm in IOPS*: Die von der Anwendung angeforderten Protokolloperationen pro Sekunde.
* *Verfügbarkeit*: Gemessen als Prozentsatz der vom Dienst erfolgreich beantworteten E/A-Anfragen, geteilt durch die Gesamtzahl der an den Dienst gestellten I/O-Anfragen. Dies wird an der Service-Abgrenzung in einem Monat gemessen und schließt nicht die geplante Ausfallzeit oder Nichtverfügbarkeit der vom Kunden bereitgestellten Einrichtungen, Netzwerke oder anderen Services ein.
* *Langlebigkeit*: Prozentsatz der Daten, auf die ohne Verlust der Treue zugegriffen wird, ausgenommen vom Kunden verursachte Löschung oder Beschädigung.
* *Latenz*: Zeit zur Bedienung einer von einem Client erhaltenen I/O-Anfrage, gemessen an der Serviceeingrenzung (Storage-Controller-I/O-Port).

