---
sidebar: sidebar 
permalink: concepts/misc-volume-billing.html 
keywords: Billing and miscellaneous scenarios 
summary: Informieren Sie sich über die Keystone Abrechnung für spezifische Konfigurationen, darunter geklonte Volumes, erweiterte Datensicherung und mehr. 
---
= Verschiedene Szenarien für Keystone Abrechnung
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Mit den Informationen zur Keystone Abrechnung für bestimmte Konfigurationen können Sie die Servicenutzung optimieren und Kosten managen. Zu den Szenarien zählen geklonte Volumes, erweiterte Datensicherung, temporäre Volumes, QoS-Richtlinien, SnapMirror Ziele, LUNs und System-/Root-Volumes.



== Abrechnung für geklonte Volumes

Wenn Volumes in ONTAP geklont werden und Sie sie zum Backup und zur Wiederherstellung Ihrer Daten verwenden, können Sie die Klone ohne zusätzliche Zahlungen weiterhin verwenden. Geklonte Volumes, die für andere Zwecke in Ihrem Unternehmen für einen hohen Zeitraum genutzt werden, werden jedoch in Rechnung gestellt.

Beachten Sie Folgendes:

* Klon-Volumes berechnen keine Kosten, solange ihre Größe weniger als 10 % des übergeordneten Volume beträgt (die physische Kapazität, die im Klon-Volume im Vergleich mit der im übergeordneten Volume genutzten physischen Kapazität verwendet wird).
* Für geklonte Volumes gibt es keine 24-Stunden-Frist, es wird nur die Größe des Klons berücksichtigt.
* Sobald das Klon-Volume 10 % der physischen Größe des übergeordneten Volume überschreitet, wird der Klon als Standard-Volume abgerechnet (genutzte logische Kapazität).




== Die Kosten für die erweiterte Datensicherung werden abgerechnet

Die erweiterte Datensicherung verwendet NetApp MetroCluster, um Daten zwischen zwei physisch getrennten Clustern zu spiegeln. Bei MetroCluster gespiegelten Aggregaten werden die Daten zweimal pro Cluster geschrieben. Der Keystone-Service berechnet unabhängig vom Verbrauch auf jeder Seite und führt zu zwei identischen Verbrauchsdatensätzen. Die Zusatzgebühren werden auf alle Kapazitäten im Abonnement angewendet, unabhängig davon, ob sich die Daten an der Quelle befinden, oder ob sie gespiegelt oder unverspiegelte Daten sind.

Wenn Sie Ihre Cluster über ONTAP System Manager (System Manager) oder Active IQ Unified Manager (Unified Manager) überwachen, kann es zu Abweichungen zwischen dem Verbrauch über diese Tools und Keystone kommen. System Manager und Unified Manager melden keine Volumes auf dem gespiegelten (Remote-) Cluster und melden so die Hälfte der Verbrauchsmetriken, die der Keystone-Service meldet.

.Beispiel:
Standort A und Standort B werden in einer MetroCluster-Konfiguration eingerichtet. Wenn ein Benutzer ein Volume von 10 TB in Standort A erstellt, wird in Standort B ein identisches Volume mit 10 TB erstellt Keystone erkennt 10 TB des Verbrauchs an jedem Standort, was einer Erhöhung der Gesamtzahl um 20 TB ergibt. System Manager und Unified Manager melden ein 10-TB-Volume, das auf Standort A erstellt wurde, melden Sie jedoch kein 10-TB-Volume an Standort B.

Darüber hinaus zählen alle auf einem Keystone System mit erweiterter Datensicherung erstellten Volumes auf die Nutzung der erweiterten Datensicherung, unabhängig davon, ob diese Volumes gespiegelt wurden oder nicht.



== Abrechnung für temporäre Volumes

Gelegentlich werden durch ONTAP temporäre Volumes (TMP) beim Verschieben von Volumes erstellt. Diese temporären Volumen sind kurzlebig, und der Verbrauch auf diesen Volumen wird nicht für die Abrechnung gemessen.



== Abrechnung und anpassungsfähige QoS-Richtlinien

Keystone misst den Verbrauch anhand von Service-Leveln. Jedes Service-Level ist mit einer bestimmten QoS-Richtlinie (Quality of Service) verknüpft. Während der Implementierung werden Sie über die Details der einzelnen anpassungsfähigen QoS-Richtlinien für die abonnierten Keystone Services informiert. Stellen Sie während des Storage-Managements sicher, dass Ihren Volumes die entsprechenden anpassungsfähigen QoS-Richtlinien gemäß den abonnierten Service-Leveln zugewiesen sind, um unerwartete Abrechnungsvorgänge zu vermeiden. Weitere Informationen zu QoS-Richtlinien in ONTAP finden Sie unter link:https://docs.netapp.com/us-en/ontap/performance-admin/guarantee-throughput-qos-task.html["Durchsatz garantieren mit QoS-Übersicht"^].



== Abrechnung für SnapMirror Ziele

Das Preismodell für das SnapMirror Ziel-Volume unterliegt der anpassungsfähigen QoS-Richtlinie für das Service-Level, das auf dem Quell-Volume zugewiesen ist. Wenn der Quelle jedoch keine Adaptive QoS-Richtlinie zugeordnet ist, wird das Ziel auf der Grundlage des niedrigsten verfügbaren Service-Levels abgerechnet.



== Abrechnung für LUNs

Bei LUNs wird dasselbe Abrechnungsmuster befolgt wie für Volumes, die durch anpassungsfähige QoS-Richtlinien gesteuert werden. Wenn separate anpassungsfähige QoS-Richtlinien auf LUNs festgelegt werden, dann:

* Die LUN-Größe wird gemäß dem zugehörigen Service-Level der LUN für den Verbrauch gezählt.
* Der restliche Speicherplatz im Volume, falls vorhanden, wird gemäß der anpassungsfähigen QoS-Richtlinie des für das Volume festgelegten Service-Levels abgerechnet.




== System- und Root-Volumes

System- und Root-Volumes werden als Teil der Gesamtüberwachung des Keystone Service überwacht, jedoch nicht gezählt oder abgerechnet. Der Verbrauch auf diesen Mengen ist für die Abrechnung ausgenommen.
