---
sidebar: sidebar 
permalink: concepts/misc-volume-billing.html 
keywords: Billing and miscellaneous scenarios 
summary: Informieren Sie sich über die Keystone Abrechnung für spezifische Konfigurationen, darunter geklonte Volumes, erweiterte Datensicherung und mehr. 
---
= Verschiedene Szenarien für Keystone Abrechnung
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Wenn Sie die Keystone -Abrechnung für bestimmte Konfigurationen in Version 3 (v3) verstehen, können Sie die Servicenutzung optimieren und die Kosten verwalten.  Die Konfigurationen umfassen geklonte Volumes, temporäre Volumes, SnapMirror -Ziele, LUNs und System-/Root-Volumes.



== Abrechnung für geklonte Volumes

Wenn Volumes in ONTAP geklont werden und Sie sie zum Backup und zur Wiederherstellung Ihrer Daten verwenden, können Sie die Klone ohne zusätzliche Zahlungen weiterhin verwenden. Geklonte Volumes, die für andere Zwecke in Ihrem Unternehmen für einen hohen Zeitraum genutzt werden, werden jedoch in Rechnung gestellt.

Beachten Sie Folgendes:

* Klon-Volumes berechnen keine Kosten, solange ihre Größe weniger als 10 % des übergeordneten Volume beträgt (die physische Kapazität, die im Klon-Volume im Vergleich mit der im übergeordneten Volume genutzten physischen Kapazität verwendet wird).
* Für geklonte Volumes gibt es keine 24-stündige Karenzzeit. Es wird nur die Größe des Klons berücksichtigt.
* Sobald das Klon-Volume 10 % der physischen Größe des übergeordneten Volume überschreitet, wird der Klon als Standard-Volume abgerechnet (genutzte logische Kapazität).




== Abrechnung für temporäre Volumes

Gelegentlich werden durch ONTAP temporäre Volumes (TMP) beim Verschieben von Volumes erstellt. Diese temporären Volumen sind kurzlebig, und der Verbrauch auf diesen Volumen wird nicht für die Abrechnung gemessen.



== Abrechnung für SnapMirror Ziele

Die Preise für SnapMirror-Zielvolumes, egal ob für die Notfallwiederherstellung oder die langfristige Datenaufbewahrung, richten sich nach dem dem Ziel zugewiesenen Leistungsservicelevel. Für den Datenschutz fallen keine zusätzlichen Gebühren an.



== Abrechnung für LUNs

Bei LUNs erfolgt die Abrechnung auf Basis der Leistungsservicelevel des Volumes.



== System- und Root-Volumes

System- und Root-Volumes werden als Teil der Gesamtüberwachung des Keystone Service überwacht, jedoch nicht gezählt oder abgerechnet. Der Verbrauch auf diesen Mengen ist für die Abrechnung ausgenommen.



== Abrechnung für SnapMirror Ziele

Das Preismodell für das SnapMirror Ziel-Volume unterliegt der anpassungsfähigen QoS-Richtlinie für das Service-Level, das auf dem Quell-Volume zugewiesen ist. Wenn der Quelle jedoch keine Adaptive QoS-Richtlinie zugeordnet ist, wird das Ziel auf der Grundlage des niedrigsten verfügbaren Service-Levels abgerechnet.



== Abrechnung für LUNs

Bei LUNs wird dasselbe Abrechnungsmuster befolgt wie für Volumes, die durch anpassungsfähige QoS-Richtlinien gesteuert werden. Wenn separate anpassungsfähige QoS-Richtlinien auf LUNs festgelegt werden, dann:

* Die LUN-Größe wird gemäß dem zugehörigen Service-Level der LUN für den Verbrauch gezählt.
* Der restliche Speicherplatz im Volume, falls vorhanden, wird gemäß der anpassungsfähigen QoS-Richtlinie des für das Volume festgelegten Service-Levels abgerechnet.




== System- und Root-Volumes

System- und Root-Volumes werden als Teil der Gesamtüberwachung des Keystone Service überwacht, jedoch nicht gezählt oder abgerechnet. Der Verbrauch auf diesen Mengen ist für die Abrechnung ausgenommen.
