---
sidebar: sidebar 
permalink: concepts/pricing.html 
keywords: pricing, billing introduction, Keystone billing 
summary: Keystone bietet ein Pay-as-you-grow-Modell für Ihren flexiblen und skalierbaren Nutzungsbedarf. 
---
= Keystone-Preisgestaltung
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Der nutzungsbasierte Abonnementdienst NetApp Keystone STaaS bietet flexiblen und skalierbaren Verbrauch mit vorhersehbaren und im Voraus festgelegten Preisen für Ihren Speicherbedarf.

Keystone für Version 3 (v3) bietet Ihnen die folgenden Abrechnungsmöglichkeiten:

* Die Bezahlung basiert auf der Festlegung von IOPS und der Latenz-Kapazität, um verschiedene Workload-Anforderungen zu erfüllen. Die verschiedenen Leistungsservicestufen – Extreme, Premium, Standard, Value, Object und Cloud Volumes ONTAP – ermöglichen Ihnen die Verwaltung Ihres Speichers basierend auf dem von Ihnen erworbenen Servicelevel.
* Sie bietet planbare Abrechnung für die verplante Kapazität und „Pay-per-use“-Funktion für die variable (Burst) Kapazitätsauslastung.
* Sie können einen Paketpreis für Hardware, Betriebssystem und Support für ein US-Dollar/tib-Preis auswählen. Sie erhalten für jeden Speichertyp (vereinheitlichte, Block-, optimierte, Objekt- oder Cloud-Speicherdienste) eine einzige Rechnung.
* Sie können die Laufzeit der Dienste und die Zahlungsoptionen flexibel auswählen, beispielsweise monatlich, vierteljährlich, halbjährlich oder jährlich.


Die Keystone-Abrechnung basiert auf engagierter Kapazität und variabler Burst-Nutzung.

Informationen zu verschiedenen in Keystone unterstützten Kapazitäten finden Sie unter link:../concepts/supported-storage-capacity.html["Unterstützte Storage-Kapazitäten in Keystone"].

*Verwandte Informationen*

* link:../concepts/committed-capacity-billing.html["Abrechnung basiert auf der verplante Kapazität"]
* link:../concepts/consumed-capacity-billing.html["Messung basierend auf verbrauchter Kapazität"]
* link:../concepts/burst-consumption-billing.html["Abrechnung auf Basis von Burst-Nutzung"]
* link:../concepts/misc-volume-billing.html["Die Abrechnung basiert auf verschiedenen Volume-Typen"]
* link:../concepts/billing-schedules.html["Abrechnungszeitpläne"]

