---
sidebar: sidebar 
permalink: concepts/qos.html 
keywords: PSL and QoS, service level quality of service 
summary: Quality of Service in Keystone 
---
= Quality of Service (QoS) in Keystone
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Bei Storage Quality of Service (QoS) handelt es sich um eine entscheidende Technologie, mit der sichergestellt wird, dass Applikationen eine konsistente und vorhersehbare Performance erhalten. Ohne QoS verbrauchen bestimmte Workloads, beispielsweise beim Booten mehrerer Systeme, die meisten oder alle Ressourcen eines bestimmten Zeitraums und wirken sich auf andere Workloads aus. Informationen zur QoS finden Sie unter https://["Durchsatz garantieren mit QoS-Übersicht"^].



== Anpassungsfähige QoS

Adaptive QoS (AQoS) wird von Keystone Services verwendet, um das IOPS-/tib-Verhältnis basierend auf der Volume-Größe dynamisch beizubehalten. Informationen zu AQoS-Richtlinien finden Sie unter https://["Allgemeines zur anpassungsfähigen QoS"^].

Keystone stellt Ihnen AQoS-Richtlinien zur Verfügung, die Sie einrichten können, sobald Ihr Cluster in Betrieb ist. Sie sollten sicherstellen, dass alle Ihre Volumes mit den richtigen AQoS-Richtlinien verknüpft sind, die bereits erstellt und in Ihrem System verfügbar sind.

Ein ONTAP-Volume ist nicht konform, wenn keine AQoS-Richtlinie angewendet wird. Ein Volume ohne QoS-Richtlinie stellt als letztes in der Prioritätenliste jedes System verfügbare Input/Output-Operationen zur Verfügung. Wenn jedoch Input/Output-Vorgänge verfügbar sind, könnte das Volume alle verfügbaren I/O-Vorgänge verbrauchen.


NOTE: Wenn Sie keine AQoS-Richtlinien auf Ihre Volumes angewendet haben, werden diese Volumes auf dem höchsten Service-Level gemäß Ihrem Abonnement gemessen und abgerechnet. Dies kann zu unbeabsichtigten Burst-Gebühren führen.



== Adaptive QoS-Einstellungen

Die AQoS-Einstellungen (Adaptive QoS) variieren je nach Service-Level.

|===


| *Name der Richtlinie* | *Extreme* | *Premium* | *Leistung* | *Standard* | *Wert* 


| *Erwartete IOPS* | 6,144 | 2,048 | 1,024 | 256 | 64 


| *Erwartete IOPS-Zuweisung* 5+| Zugewiesener Speicherplatz 


| *Spitzen-IOPS* | 12,288 | 4,096 | 2,048 | 512 | 128 


| *Maximale IOPS-Zuweisung* 5+| Genutzter Speicherplatz 


| *Blockgröße* 5+| 32K 
|===


== Konfiguration der adaptiven QoS-Richtliniengruppe

Sie können AQoS-Richtlinien (Adaptive QoS) so konfigurieren, dass eine Durchsatzobergrenze oder -Größe automatisch von der Größe des Volumes bis zur Höhe skaliert werden kann. Nicht alle Keystone Service-Level sind mit den standardmäßigen QoS-Richtlinien von ONTAP abgestimmt. Sie können für diese benutzerdefinierte QoS-Richtlinien erstellen. Beim Konfigurieren einer Richtlinie sollten Sie Folgendes beachten:

* *Policy Group Name*: Der Name der AQoS Policy Group. Beispiel: `Keystone_extreme`.
* *Vserver*: Der Name des Vservers oder der Storage VM (Storage Virtual Machine).
* *Erwartete IOPS*: Mindestzahl an IOPS pro zugewiesenem tib pro Volume, die das System zu liefern versucht, wenn genügend System-IOPS verfügbar sind.
* *Peak IOPS*: Die maximale Anzahl an IOPS pro verwendetes tib und Volume, das das System dem Volume ermöglichen kann, bevor es die IOPS durch Injektion von Latenz drosselt.
* *Erwartete IOPS-Zuweisung*: Dieser Parameter steuert, ob die erwarteten für das Volume verfügbaren IOPS auf der zugewiesenen oder genutzten Größe des Volumes basieren. In Keystone basiert die Zuordnung des Speicherplatzes.
* *Spitzenwerte-IOPS-Zuweisung*: Dieser Parameter steuert, ob die für das Volume verfügbaren Spitzenwerte-IOPS auf der zugewiesenen oder genutzten Größe des Volumes basieren. In Keystone basiert dies auf dem verwendeten Speicherplatz.
* *Absolute IOPS-Minimum*: Die niedrigste Anzahl der erwarteten IOPS, die auf ein Volume angewendet wird, wenn die Volume-Größe sehr klein ist und ansonsten eine inakzeptable Anzahl von IOPS zur Folge hätte. Dieser Wert liegt standardmäßig bei 1,000 für `Extreme`, 500 für `Premium`, Und 250 für `Performance`, Und 75 für `Standard` Und `Value` Service-Leveln.
+

NOTE: Dies ist keine IOPS-Dichte (z. B. 75 IOPS/tib), sondern eine absolute Mindestanzahl an IOPS.



Informationen zur I/O-Dichte finden Sie unter link:../concepts/metrics.html["Metriken und Definitionen für Keystone Services"]. Weitere Informationen zu AQoS-Richtliniengruppen finden Sie unter https://["Verwendung von adaptiven QoS-Richtliniengruppen"^].



== Einstellungen anpassungsfähiger QoS-Richtlinien

Die Einstellungen für AQoS-Richtlinien (Adaptive QoS) für jedes Service-Level werden in den folgenden Abschnitten beschrieben. Die Minimum- und Höchstgrößen für jedes hier angegebene Service Level ermöglichen optimale IOPS- und Latenzwerte für ein Volume. Wenn zu viele Volumes außerhalb dieser Richtlinien erstellt werden, kann dies negative Auswirkungen auf die Performance dieser Volumes haben.



=== Einstellungen für Extreme Service Level

Einstellungen und Befehle für den Extreme Service Level:

* Beispielbefehl:


....
qos adaptive-policy-group create -policy-group <Keystone_extreme> -vserver <SVM_name> -expected-iops 6144 -peak-iops 12288 -expected-iops-allocation allocated-space -peak-iops-allocation used-space -block-size 32K -absolute-min-iops 1000
....
* Minimale Volume-Größe: 100 gib, 0,1 tib
* Maximale Volume-Größe: 10 tib




=== Einstellungen für Premium-Service-Level

Einstellungen und Befehle für den Premium Service Level:

* Beispielbefehl:


....
qos adaptive-policy-group create -policy-group <Keystone_premium> -vserver <SVM_name> -expected-iops 2048 -peak-iops 4096 -expected-iops-allocation allocated-space -peak-iops-allocation used-space -block-size 32K -absolute-min-iops 500
....
* Minimale Volume-Größe: 500 gib, 0,5 tib
* Maximale Volume-Größe: 50 tib




=== Einstellungen für Leistungsstufen

Einstellungen und Befehle für das Performance Service Level:

* Beispielbefehl:


....
qos adaptive-policy-group create -policy-group <Keystone_performance> -vserver <SVM_name> -expected-iops 1024 -peak-iops 2048 -expected-iops-allocation allocated-space -peak-iops-allocation used-space -block-size 32K -absolute-min-iops 250
....
* Minimale Volume-Größe: 500 gib, 0,5 tib
* Maximale Volume-Größe: 80 tib




=== Einstellungen für Standard-Service-Level

Einstellungen und Befehle für Standard-Service-Level:

* Beispielbefehl:


....
qos adaptive-policy-group create -policy-group <Keystone_standard> -vserver <SVM_name> -expected-iops 256 -peak-iops 512 -expected-iops-allocation allocated-space -peak-iops-allocation used-space -block-size 32K -absolute-min-iops 75
....
* Minimale Volume-Größe: 1 tib
* Maximale Volume-Größe: 100 tib




=== Einstellungen für Service-Level Wert

Einstellungen und Befehle für die Service-Ebene Wert:

* Beispielbefehl:


....
qos adaptive-policy-group create -policy-group <Keystone_value> -vserver <SVM_name> -expected-iops 64 -peak-iops 128 -expected-iops-allocation allocated-space -peak-iops-allocation used-space -block-size 32K -absolute-min-iops 75
....
* Minimale Volume-Größe: 1 tib
* Maximale Volume-Größe: 100 tib




== Berechnung der Blockgröße

Beachten Sie die folgenden Punkte, bevor Sie die Blockgröße mithilfe der folgenden Einstellungen berechnen:

* IOPS/tib = MB/s/tib geteilt durch (Blockgröße * 1024)
* Blockgröße ist in KB/IO
* TIB = 1024 gib; gib = 1024 MiB; MiB = 1024 KiB; KiB = 1024 Byte; gemäß Basis 2
* TB = 1.000 GB; GB = 1000 MB; MB = 1.000 KB; KB = 1000 Bytes; Stand 10


.Berechnung der Größe des Probenblocks
Um den Durchsatz für das A-Service-Level zu berechnen, z. B. `Extreme` Service Level:

* Maximale IOPS: 12,288
* Block-Größe pro I/O: 32 KB
* Maximaler Durchsatz = (12288 * 32 * 1024) / (1024*1024) = 384 MBps/tib


Wenn ein Volume über 700 gib der logischen Daten verfügt, beträgt der verfügbare Durchsatz:

`mAximumdurchsatz = 384 * 0.7 = 268,8 MB`
