---
sidebar: sidebar 
permalink: concepts/service-levels-v2.html 
keywords: service levels, service level, rate plan or service level 
summary: Keystone STaaS bietet Storage-Kapazität auf vordefinierten Service-Leveln. Jedes von Keystone gemanagte Volume ist einem Service-Level zugeordnet. 
---
= Leistungsservicelevel in Keystone
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Keystone STaaS für Version 2 (v2) bietet Datenspeicherkapazität auf vordefinierten Leistungsserviceleveln. Jedem von Keystone-Diensten verwalteten Datenträger ist ein Leistungsdienstlevel zugeordnet.

Ein Abonnement kann mehrere Tarifpläne umfassen, und jeder Tarifplan entspricht einem Leistungsservicelevel. Jeder Tarifplan verfügt über eine zugesicherte Kapazität pro Leistungsservicelevel.

Jedes Leistungsservicelevel wird durch seine E/A-Dichte definiert, d. h. IOPS/TiB/Volume. Dies ist das Verhältnis der Performance (IOPS) (Input/Output Operations per Second) und der genutzten Storage-Kapazität (tib). Dies ist IOPS/tib bei einer durchschnittlichen Latenz pro Volume.

Sie wählen die Leistungsservicelevel basierend auf Ihrer Speicherumgebung sowie Ihren Speicher- und Verbrauchsanforderungen aus. Die Basis-Leistungsservicelevel stehen Ihnen standardmäßig zur Verfügung. Spezifische Leistungsservicelevel sind zusätzlich verfügbar, wenn Sie sich für Zusatzdienste entschieden haben. Beispielsweise ist Ihrem Abonnement für den Zusatzdienst „Erweiterter Datenschutz“ das Leistungsservicelevel „Advanced Data-Protect“ zugewiesen.


TIP: Eine detaillierte Servicebeschreibung für die Performance-Service-Levels von NetApp Keystone STaaS ist verfügbar  https://www.netapp.com/services/keystone/terms-and-conditions/["Hier"^] .

Die grundlegenden Leistungsservicelevel für die unterstützten Speichertypen, Datei-, Block-, Objekt- und Clouddienste werden in den folgenden Abschnitten beschrieben:



== Leistungsservicelevel für Datei- und Blockspeicher

* Unterstützte Protokolle*: NFS, CIFS, iSCSI und FC

|===


| *Leistungsservicelevel* | *Extreme* | *Premium* | *Leistung* | *Standard* | *Wert* 


| *Workload-Typen der Probe* | Analytics, Datenbanken, geschäftskritische Applikationen | VDI, VSI, Softwareentwicklung | OLTP, OLAP, Container, Softwareentwicklung | Dateifreigaben, Webserver | Backup 


| *Maximale IOPS/logische TIBS gespeichert pro Volumen* | 12,288 | 4,096 | 2,048 | 512 | 128 


| *Maximale Anzahl an IOPS/logischem TIBS pro Volume* | 6,144 | 2,048 | 1,024 | 256 | 64 


| *Maximale MB/s/logische TIBS gespeichert pro Volume @ 32K B/S* | 384 | 128 | 64 | 16 | 4 


| *Ziel: 90^th^ Perzentillatenz* | <1 ms | <2 ms | <4 ms | <4 ms | <17 ms 


| *Blockgröße* 5+| 32K 


| *Art der gebuchten und gemessenen Kapazität* 5+| Logisch 
|===


=== Mehr zu Performance-Service-Levels für Datei- und Blockspeicher

Die grundlegenden Service-Level-Metriken für die Leistung hängen von den folgenden Bedingungen ab:

* Die Leistungsservicelevel für Datei- und Blockspeicher unterstützen ONTAP 9.7 und höher.
* IOPS/TiB/Volume, MBps/TiB/Volume und Latenzwerte für Leistungsservicelevel basieren auf der im Volume gespeicherten Datenmenge, einer Blockgröße von 32 KB und einer zufälligen Kombination aus 70 % Lese- und 30 % Schreib-E/A-Operationen.
* Der tatsächliche IOPS-/tib-/Volume-Wert und MB/s-/tib-Volume können basierend auf der tatsächlichen oder angenommenen Blockgröße, der Parallelität des System-Workloads oder Input/Output-Operationen variieren.
* Die Latenz umfasst nicht Folgendes:
+
** Applikations- oder Host-Latenz erzielt
** Netzwerklatenz des Kunden zu bzw. von den Controller-Ports
** Gemeinkosten für die Datenübertragung an den Objektspeicher bei FabricPool
** Latenz wird automatisch durch QoS angewendet, um die IO innerhalb der maximalen Service-Level-Leistung zu halten


* Latenzwerte gelten nicht für MetroCluster-Schreibvorgänge. Diese Schreibvorgänge sind von der Entfernung von Remote-Systemen abhängig.
* Wenn einem oder mehreren Volumes auf einem Speichersystem keine AQoS-Richtlinie zugewiesen ist, werden diese Volumes als nicht konforme Volumes betrachtet und es gelten für diese Systeme keine Zielleistungs-Servicelevel.
* _Expected IOPS_ wird nur für FabricPool angestrebt, wenn die Tiering-Richtlinie auf „keine“ gesetzt ist und sich keine Blöcke in der Cloud befinden. _Expected IOPS_ ist für Volumes bestimmt, die sich nicht in einer synchronen SnapMirror-Beziehung befinden.
* Workload-I/O-Vorgänge müssen gemäß der Keystone Reihenfolge über alle implementierten Controller hinweg ausgeglichen werden.




== Objekt-Storage

*unterstütztes Protokoll*: S3

|===


| *Leistungs-Service-Level* | Objekt 


| * Workload-Typ* | Medien-Repository, Archivierung 


| *Maximale IOPS/logische tib gespeichert pro Volume* | K. A. 


| *Maximale Mbps/logische tib gespeichert pro Volume* | K. A. 


| * Durchschnittliche Latenz* | K. A. 


| *Art der gebuchten und gemessenen Kapazität* | Physisch 
|===

NOTE: Die Latenz umfasst keine Overhead-Köpfe, die im Zusammenhang mit dem Datentransfer zum Objektspeicher im Falle von FabricPool Storage stehen.



== Cloud-Storage

*Unterstütztes Protokoll*: NFS, CIFS, iSCSI und S3 (nur AWS und Azure)

|===


| *Leistungs-Service-Level* | Cloud Volumes ONTAP 


| * Workload-Typ* | Disaster Recovery, Softwareentwicklung/Test, Business-Applikationen 


| *Maximale IOPS/logische tib gespeichert pro Volume* | K. A. 


| *Maximale Mbps/logische tib gespeichert pro Volume* | K. A. 


| * Durchschnittliche Latenz* | K. A. 
|===
[NOTE]
====
* Cloud-native Services wie Computing, Storage, Netzwerk werden von Cloud-Providern in Rechnung gestellt.
* Diese Services hängen von Cloud-Storage- und Computing-Merkmalen ab.


====
*Verwandte Informationen*

* link:../concepts/supported-storage-capacity-v2.html["Unterstützte Speicherkapazitäten"]
* link:..//concepts/metrics-v2.html["Metriken und Definitionen für Keystone Services"]
* link:../concepts/qos.html["Quality of Service (QoS) in Keystone"]
* link:../concepts/pricing-v2.html["Keystone-Preisgestaltung"]

