---
sidebar: sidebar 
permalink: concepts/service-levels.html 
keywords: service levels, service level, rate plan or service level 
summary: Keystone STaaS für Version 3 bietet Speicherkapazität auf vordefinierten Serviceleveln. Jedes von Keystone gemanagte Volume ist einem Service-Level zugeordnet. 
---
= Leistungsservicelevel in Keystone
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Keystone STaaS für Version 3 (v3) bietet Datenspeicherkapazität auf vordefinierten Leistungsserviceleveln. Jedem von Keystone-Diensten verwalteten Datenträger ist ein Leistungsdienstlevel zugeordnet.

Ein Abonnement kann mehrere Tarifpläne umfassen, und jeder Tarifplan entspricht einem Leistungsservicelevel. Jeder Tarifplan verfügt über eine zugesicherte Kapazität pro Leistungsservicelevel.

Ein Performance-Servicelevel kann mehrere Instanzen umfassen, wobei jede Instanz ein separates Speicherarray darstellt, das diesem Performance-Servicelevel in der Kundenumgebung zugewiesen ist. Jedes Performance-Servicelevel wird durch Eingabe-/Ausgabevorgänge pro Sekunde (IOPS), Durchsatz (GBps) und Latenz (ms) definiert. Diese Kennzahlen werden pro Performance-Servicelevel-Instanz gemessen und angewendet.

Sie wählen Leistungsservicelevel basierend auf Ihrer Speicherumgebung und Ihren Speicher- und Verbrauchsanforderungen aus. Die Basis-Performance-Service-Levels stehen Ihnen standardmäßig zur Verfügung. Wenn Sie sich für Zusatzdienste entschieden haben, stehen Ihnen zusätzlich bestimmte Leistungsservice-Level zur Verfügung.


TIP: Eine detaillierte Servicebeschreibung für die Performance-Service-Levels von NetApp Keystone STaaS ist verfügbar  https://www.netapp.com/services/keystone/terms-and-conditions/["Hier"^] .

Die grundlegenden Leistungsservicelevel für die unterstützten Speichertypen (vereinheitlichte, blockoptimierte, Objekt- und Cloud-Dienste) werden in den folgenden Abschnitten beschrieben:



== Leistungsservicelevel für Unified Storage

*Unterstützte Protokolle*: FC, iSCSI, NFS, NFSv4/RDMA, NVMe/FC, NVMe/TCP, SMB, S3

|===


| *Performance-Servicelevel* (alle Angaben pro Performance-Servicelevel-Instanz) | *Extreme* | *Premium* | *Standard* | *Wert* 


| *Workload-Typen der Probe* | KI/ML, HPC, InMem-DB | Analytik, EDA, OLTP | OLAP, IoT, Container | Backup, Archiv 


| *Maximale IOPS*^1^ | 1M | 550K | 500K | NA 


| *Maximale GBps* | 40 | 20 | 20 | NA 


| *Ziel: 90^th^ Perzentillatenz* | <=1 ms | <=1 ms | <=4 ms | >4 ms 


| *Mindestkapazität* | 50 tib | 50 tib | 100 tib | 100 tib 


| *Inkrementelle Erhöhung der zugesagten Kapazität* 4+| 25TiB 


| *Art der gebuchten und gemessenen Kapazität* 4+| Logisch oder physisch 
|===


== Leistungsservicelevel für blockoptimierten Speicher

*Unterstützte Protokolle*: NVMe/TCP, NVMe/FC, FC, iSCSI

|===


| *Performance-Servicelevel* (alle Angaben pro Performance-Servicelevel-Instanz) | *Extreme* | *Premium* 


| *Workload-Typen der Probe* 2+| SAP HANA, Oracle, MS SQL Server, EPIC 


| *Maximale IOPS*^1^ | 850K | 450K 


| *Maximale GBps* | 65 | 25 


| *Ziel: 90^th^ Perzentillatenz* | <=1 ms | <=1 ms 


| *Mindestkapazität* | 50 tib | 50 tib 


| *Inkrementelle Erhöhung der zugesagten Kapazität* 2+| 25TiB 


| *Art der gebuchten und gemessenen Kapazität* 2+| Logisch oder physisch 
|===

NOTE: ^1^Sich gegenseitig ausschließende Ziele. Die tatsächliche Leistung kann je nach verschiedenen Faktoren, einschließlich Betriebssystemversion, Hardware, Workload-Typ und Anzahl gleichzeitiger Vorgänge, abweichen.



=== Mehr zu Performance-Service-Levels für einheitlichen und blockoptimierten Speicher

Die grundlegenden Service-Level-Metriken für die Leistung hängen von den folgenden Bedingungen ab:

* Die Performance-Service-Levels unterstützen ONTAP 9.8 und höher.
* Für einheitlichen Speicher,
+
** *IOPS*: Für ONTAP 9.16.1 mit NFS unterstützt jede Instanz der Leistungsstufe wahlfreien Zugriff mit einem Leseverhältnis von 70 % und 30 % Schreibverhältnis, einer Blockgröße von 8 KB und einer Latenz von 1 ms (4 ms für Standard).
** *Durchsatz*: Bei ONTAP 9.16.1 mit NFS unterstützt jede Instanz der Leistungsstufe sequentiellen Zugriff mit 100 % Lesen und einer Blockgröße von 32 KB.


* Für blockoptimierte Speicherung,
+
** *IOPS*: Bei ONTAP 9.16.1 mit FCP unterstützt jede Performance-Level-Instanz wahlfreien Zugriff mit einem Leseverhältnis von 70 % und 30 % Schreibverhältnis, einer Blockgröße von 8 KB und einer Latenz von 1 ms.
** *Durchsatz*: Bei ONTAP 9.16.1 mit FCP unterstützt jede Instanz der Leistungsstufe sequentiellen Zugriff mit 100 % Lesen und einer Blockgröße von 64 KB.


* Die Latenz umfasst nicht Folgendes:
+
** Applikations- oder Host-Latenz erzielt
** Netzwerklatenz des Kunden zu bzw. von den Controller-Ports
** Gemeinkosten für die Datenübertragung an den Objektspeicher bei FabricPool


* Latenzwerte gelten nicht für MetroCluster-Schreibvorgänge. Diese Schreibvorgänge sind von der Entfernung von Remote-Systemen abhängig.
* _Expected IOPS_ wird nur für FabricPool angestrebt, wenn die Tiering-Richtlinie auf „keine“ gesetzt ist und sich keine Blöcke in der Cloud befinden. _Expected IOPS_ ist für Volumes bestimmt, die sich nicht in einer synchronen SnapMirror-Beziehung befinden.




== Leistungsservicelevel für Objektspeicher

*unterstütztes Protokoll*: S3

|===


| *Leistungs-Service-Level* | *Standard* | *Wert* 


| *Mindestkapazität pro Bestellung* | 200 tib | 500 tib 


| *Inkrementelle Erhöhung der zugesagten Kapazität* | 25 tib | 100 tib 


| *Art der gebuchten und gemessenen Kapazität* 2+| Physisch 
|===


== Cloud-Storage

*Unterstützte Protokolle*: NFS, CIFS, iSCSI und S3 (nur AWS und Azure)

|===


| *Leistungs-Service-Level* | Cloud Volumes ONTAP 


| *Mindestkapazität pro Bestellung* | 4 tib 


| *Inkrementelle Erhöhung der zugesagten Kapazität* | 1 tib 


| *Art der gebuchten und gemessenen Kapazität* | Logisch 
|===
[NOTE]
====
* Cloud-native Services wie Computing, Storage, Netzwerk werden von Cloud-Providern in Rechnung gestellt.
* Diese Services hängen von Cloud-Storage- und Computing-Merkmalen ab.


====
*Verwandte Informationen*

* link:../concepts/supported-storage-capacity.html["Unterstützte Speicherkapazitäten"]
* link:..//concepts/metrics.html["Metriken und Definitionen für Keystone Services"]
* link:../concepts/pricing.html["Keystone-Preisgestaltung"]

