---
sidebar: sidebar 
permalink: concepts/service-levels.html 
keywords: service levels, service level, rate plan or service level 
summary: Keystone STaaS bietet Storage-Kapazität auf vordefinierten Service-Leveln. Jedes von Keystone gemanagte Volume ist einem Service-Level zugeordnet. 
---
= Service-Level bei Keystone
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Keystone STaaS bietet Storage-Kapazität auf vordefinierten Performance-Service-Leveln. Jedes von Keystone Services gemanagte Volume ist einem Service-Level zugeordnet.

Ein Abonnement kann mehrere Tarifpläne haben, und jeder Tarifplan entspricht einem Service-Level. Für jeden Preisplan ist eine bestimmte Kapazität je Service-Level vorgesehen.

Die einzelnen Service-Levels werden durch ihre I/O-Dichte definiert, die IOPS/tib/Volume entspricht. Dies ist das Verhältnis der Performance (IOPS) (Input/Output Operations per Second) und der genutzten Storage-Kapazität (tib). Dies ist IOPS/tib bei einer durchschnittlichen Latenz pro Volume.

Sie wählen Service-Level basierend auf Ihrer Storage-Umgebung sowie Ihren Storage- und Verbrauchsanforderungen aus. Die Basis-Service-Level stehen Ihnen standardmäßig zur Verfügung. Wenn Sie sich für zusätzliche Services entschieden haben, stehen Ihnen zusätzlich bestimmte Service-Level zur Verfügung. Für den erweiterten Datenschutz-Add-on-Service wird Ihrem Abonnement beispielsweise der Service _Advanced Data-Protect_ zugewiesen.


TIP: Eine detaillierte Servicebeschreibung für die Service-Level von NetApp Keystone STaaS ist verfügbar https://www.netapp.com/services/keystone/terms-and-conditions/["Hier"^].

Die Basis-Service-Level für die unterstützten Storage-Typen, File-, Block-, Objekt- und Cloud-Services werden in den folgenden Abschnitten beschrieben:



== Service-Level für File- und Block-Storage

* Unterstützte Protokolle*: NFS, CIFS, iSCSI und FC

|===


| *Service Level* | *Extreme* | *Premium* | *Leistung* | *Standard* | *Wert* 


| *Workload-Typen der Probe* | Analytics, Datenbanken, geschäftskritische Applikationen | VDI, VSI, Softwareentwicklung | OLTP, OLAP, Container, Softwareentwicklung | Dateifreigaben, Webserver | Backup 


| *Maximale IOPS/logische TIBS gespeichert pro Volumen* | 12,288 | 4,096 | 2,048 | 512 | 128 


| *Maximale Anzahl an IOPS/logischem TIBS pro Volume* | 6,144 | 2,048 | 1,024 | 256 | 64 


| *Maximale MB/s/logische TIBS gespeichert pro Volume @ 32K B/S* | 384 | 128 | 64 | 16 | 4 


| *Ziel: 90^th^ Perzentillatenz* | <1 ms | <2 ms | <4 ms | <4 ms | <17 ms 


| *Blockgröße* 5+| 32K 


| *Art der gebuchten und gemessenen Kapazität* 5+| Logisch 
|===


=== Mehr auf Service-Levels für File- und Block-Storage

Die Basis-Service-Level-Kennzahlen hängen von den folgenden Bedingungen ab:

* Die Service-Level für File- und Block-Storage unterstützen ONTAP 9.7 und höher.
* IOPS/tib/Volume, MB/s/tib/Volume und Latenzwerte für Service-Level basieren auf der Menge der im Volume gespeicherten Daten, der Blockgröße von 32 KB sowie einer zufälligen Kombination von I/O-Vorgängen mit 70 % Lesevorgängen und 30 % Schreibzugriffen.
* Der tatsächliche IOPS-/tib-/Volume-Wert und MB/s-/tib-Volume können basierend auf der tatsächlichen oder angenommenen Blockgröße, der Parallelität des System-Workloads oder Input/Output-Operationen variieren.
* Die Latenz umfasst nicht Folgendes:
+
** Applikations- oder Host-Latenz erzielt
** Netzwerklatenz des Kunden zu bzw. von den Controller-Ports
** Gemeinkosten für die Datenübertragung an den Objektspeicher bei FabricPool
** Automatische Anwendung der Latenz durch QoS, um den I/O-Wert innerhalb der maximalen Service-Level zu halten


* Latenzwerte gelten nicht für MetroCluster-Schreibvorgänge. Diese Schreibvorgänge sind von der Entfernung von Remote-Systemen abhängig.
* Wenn einem oder mehreren Volumes auf einem Storage-System keine AQoS-Richtlinie zugewiesen ist, werden diese Volumes als nicht konforme Volumes betrachtet und für diese Systeme gelten keine Service-Ziellevel.
* _Expected IOPS_ wird nur für FabricPool angestrebt, wenn die Tiering-Richtlinie auf „keine“ gesetzt ist und sich keine Blöcke in der Cloud befinden. _Expected IOPS_ ist für Volumes bestimmt, die sich nicht in einer synchronen SnapMirror-Beziehung befinden.
* Workload-I/O-Vorgänge müssen gemäß der Keystone Reihenfolge über alle implementierten Controller hinweg ausgeglichen werden.




== Objekt-Storage

*unterstütztes Protokoll*: S3

|===


| *Service Level* | Objekt 


| * Workload-Typ* | Medien-Repository, Archivierung 


| *Maximale IOPS/logische tib gespeichert pro Volume* | K. A. 


| *Maximale Mbps/logische tib gespeichert pro Volume* | K. A. 


| * Durchschnittliche Latenz* | K. A. 


| *Art der gebuchten und gemessenen Kapazität* | Physisch 
|===

NOTE: Die Latenz umfasst keine Overhead-Köpfe, die im Zusammenhang mit dem Datentransfer zum Objektspeicher im Falle von FabricPool Storage stehen.



== Cloud-Storage

*Unterstütztes Protokoll*: NFS, CIFS, iSCSI und S3 (nur AWS und Azure)

|===


| *Service Level* | Cloud Volumes ONTAP 


| * Workload-Typ* | Disaster Recovery, Softwareentwicklung/Test, Business-Applikationen 


| *Maximale IOPS/logische tib gespeichert pro Volume* | K. A. 


| *Maximale Mbps/logische tib gespeichert pro Volume* | K. A. 


| * Durchschnittliche Latenz* | K. A. 
|===
[NOTE]
====
* Cloud-native Services wie Computing, Storage, Netzwerk werden von Cloud-Providern in Rechnung gestellt.
* Diese Services hängen von Cloud-Storage- und Computing-Merkmalen ab.


====
*Verwandte Informationen*

* link:../concepts/supported-storage-capacity.html["Unterstützte Speicherkapazitäten"]
* link:..//concepts/metrics.html["Metriken und Definitionen für Keystone Services"]
* link:../concepts/qos.html["Quality of Service (QoS) in Keystone"]
* link:../concepts/pricing.html["Keystone-Preisgestaltung"]

