---
sidebar: sidebar 
permalink: concepts/service-levels.html 
keywords: service levels, service level 
summary: Unterstützte Service-Level 
---
= Service-Level in Keystone
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Keystone STaaS bietet Storage-Kapazität zu vordefinierten Performance-Service-Leveln (Service-Level) im Abonnement.

Service Levels werden definiert durch:

* Durchschnittliche Latenz
* Maximale IOPS pro logischem tib gespeichert pro Volume


Ein Volume muss einem Service Level zugewiesen werden.



== Service Levels für unterstützten Storage

Hier sind die Service Level für Datei-, Block-, Objekt- und Cloud-Services aufgeführt.



=== Datei- und Block-Storage

* Unterstützte Protokolle*: NFS, CIFS, iSCSI und FC

|===


| *Service Level* | *Extreme* | *Premium* | *Leistung* | *Standard* | *Wert* 


| *Workload-Typen der Probe* | Analytics, Datenbanken, geschäftskritische Applikationen | VDI, VSI, Softwareentwicklung | OLTP, OLAP, Container, Softwareentwicklung | Dateifreigaben, Webserver | Backup 


| *Maximale IOPS/logische TIBS gespeichert pro Volumen* | 12,288 | 4,096 | 2,048 | 512 | 128 


| *Maximale Mbps/logische TIBS gespeichert pro Volumen* | 384 | 128 | 64 | 16 | 4 


| *Latenz* | <1 ms | <2 ms | <4 ms | <17 ms | <17 ms 
|===

NOTE: Beachten Sie die folgenden Punkte für Durchsatz-Performance-Kennzahlen (gilt nur für Datei- und Block-Services):

* Datei- und Block-Service-Level basieren auf ONTAP 9.7 und höher.
* IOPS/tib und Latenzwerte für Service-Level basieren auf der Menge der logischen Daten, die im Volume gespeichert sind, auf der Blockgröße von 32 KB und einer zufälligen Mischung aus 70 % Lese- und /30 % Schreib-I/O.
* Die tatsächlichen IOPS/tib und/oder MB/s/tib variieren je nach Workload-Parallelität und -Nutzungsmustern.
* Die Latenz umfasst nicht Folgendes:
+
** Die Applikations-, Hosts- oder Netzwerklatenz des Kunden zu den Controller-Ports bzw. von diesen aus.
** Durch QoS wird die Latenz automatisch angewendet, um die I/O-Vorgänge innerhalb der maximalen Service-Level-Maximalwerte zu halten.


* Beim Einsatz des Add-on Service Advanced Data Protection wird die Ziellatenz nur für die Bearbeitung von I/O-Anfragen von lokalen Keystone Produkten angewendet.




=== Objekt-Storage

*unterstütztes Protokoll*: S3

|===


| *Service Level* | Objekt 


| * Workload-Typ* | Medien-Repository, Archivierung 


| *Maximale IOPS/logische tib gespeichert pro Volume* | K. A. 


| *Maximale Mbps/logische tib gespeichert pro Volume* | K. A. 


| * Durchschnittliche Latenz* | K. A. 
|===

NOTE: Die Latenz umfasst keine Overhead-Köpfe, die im Zusammenhang mit dem Datentransfer zum Objektspeicher im Falle von FabricPool Storage stehen.



=== Cloud-Storage

*Unterstütztes Protokoll*: NFS, CIFS, iSCSI und S3 (nur AWS und Azure)

|===


| *Service Level* | Cloud Volumes ONTAP 


| * Workload-Typ* | Disaster Recovery, Softwareentwicklung/Test, Business-Applikationen 


| *Maximale IOPS/logische tib gespeichert pro Volume* | K. A. 


| *Maximale Mbps/logische tib gespeichert pro Volume* | K. A. 


| * Durchschnittliche Latenz* | K. A. 
|===

NOTE: Hinweis:

* Cloud-native Services wie Computing, Storage und Netzwerk werden von Cloud-Providern in Rechnung gestellt.
* Diese Services hängen von den Cloud-Storage- und Computing-Merkmalen ab.

