---
sidebar: sidebar 
permalink: concepts/service-levels.html 
keywords: service levels, service level, rate plan or service level 
summary: Keystone STaaS für Version 3 bietet Speicherkapazität auf vordefinierten Serviceleveln. Jedes von Keystone gemanagte Volume ist einem Service-Level zugeordnet. 
---
= Leistungsservicelevel in Keystone
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Keystone STaaS bietet vordefinierte Leistungs-Servicelevel (PSLs) für jeden Speichertyp. Jeder PSL legt die Leistungsziele (IOPS, Durchsatz und Latenz), die unterstützten Protokolle, die Plattform und die Mindestkapazitätsanforderungen fest. Prüfen Sie die verfügbaren PSLs, um den passenden Servicelevel für Ihre Workload auszuwählen und Ihr Abonnement zu planen.

Ein Keystone-Abonnement kann mehrere PSLs über einen oder mehrere Speichertypen hinweg umfassen. Jeder PSL verfügt über eine zugesicherte Kapazität, die der Mindestkapazität entspricht, die während der Abonnementlaufzeit für dieses Servicelevel abgerechnet wird.


NOTE: Ein AFX-Abonnement ist auf den AFX-Speichertyp beschränkt und bietet derzeit nur einen PSL, Extreme.



== Leistungs-Servicelevel-Instanzen

Ein Performance Service Level (PSL) kann mehrere Instanzen, sogenannte Performance Service Level Instances (PSLIs), in Ihrer Umgebung umfassen. Jede PSLI ist ein separates Speichersystem, das diesem Performance Service Level zugeordnet ist, wobei die zugesicherte Kapazität pro PSLI gemessen wird.

* Bei einheitlicher oder blockoptimierter Speicherung ist ein PSLI ein Speicherarray, das aus zwei Speichercontrollern in einem HA-Paar mit intern oder extern angeschlossenen Speichermedien besteht.
* Bei AFX-Speicher entspricht ein PSLI einem einzelnen AFX-Speichercontroller. AFX verwendet eine disaggregierte Architektur, in der Controller (Compute) und Laufwerksschächte (Storage) unabhängig voneinander sind und separat skaliert werden können. IOPS- und Durchsatzziele gelten pro Controller; die zugesicherte Kapazität wird auf AFX-Clusterebene gemessen, die alle Controller und Laufwerksschächte im Cluster umfasst.


Leistungskennzahlen wie IOPS, Durchsatz (GB/s) und Latenz (ms) werden pro PSLI gemessen.


TIP: Eine detaillierte Servicebeschreibung für die Performance-Service-Levels von NetApp Keystone STaaS ist verfügbar  https://www.netapp.com/services/keystone/terms-and-conditions/["Hier"^] .

Die grundlegenden Leistungs-Servicelevel für die unterstützten Datenspeichertypen: Unified, Block-Optimized, AFX, Objekt- und Cloud-Dienste werden in den folgenden Abschnitten beschrieben:



== Leistungsservicelevel für Unified Storage

|===


| *Leistungsdienstleistungsebene* (alle Spezifikationen pro Leistungsdienstleistungsebeneninstanz [HA pair]) | *Extreme* | *Premium* | *Standard* | *Wert* 


| *Unterstützte Protokolle* 4+| FC, iSCSI, NFS, NFSv4/RDMA, NVMe/FC, NVMe/TCP, SMB, S3 


| *Workload-Typen der Probe* | KI/ML, HPC, InMem-DB | Analytik, EDA, OLTP | OLAP, IoT, Container | Backup, Archiv 


| *Ziel: 90^th^ Perzentillatenz* | <=1 ms | <=1 ms | <=4 ms | >4 ms 


| *Maximale Ziel-IOPS*^1^ | 1M | 550K | 250.000 | NA 


| *Maximale Ziel-GB/s*^1^ | 40 | 20 | 10 | NA 


| * Plattform* | AFF A-Serie | AFF A-Serie | AFF C-Series | FAS 


| *Mindestkapazität* | 50 tib | 50 tib | 100 tib | 100 tib 


| *Inkrementelle Erhöhung der zugesagten Kapazität* 4+| 25 tib 


| *Art der gebuchten und gemessenen Kapazität* 4+| Logisch oder physisch 
|===


== Leistungsservicelevel für blockoptimierten Speicher

|===


| *Leistungsdienstleistungsebene* (alle Spezifikationen pro Leistungsdienstleistungsebeneninstanz [HA pair]) | *Extreme* | *Premium* | *Standard* 


| *Unterstützte Protokolle* 3+| NVMe/TCP, NVMe/FC, FC, iSCSI 


| *Workload-Typen der Probe* 3+| SAP HANA, Oracle, MS SQL Server, EPIC 


| *Ziel: 90^th^ Perzentillatenz* | <=1 ms | <=1 ms | <=4 ms 


| *Maximale Ziel-IOPS*^1^ | 850K | 450K | 120K 


| *Maximale Zielgeschwindigkeit GB/s* | 65 | 25 | 6 


| * Plattform* | ASA A-Series | ASA A-Series | ASA C-Series 


| *Mindestkapazität* | 50 tib | 50 tib | 100 tib 


| *Inkrementelle Erhöhung der zugesagten Kapazität* 3+| 25TiB 


| *Art der gebuchten und gemessenen Kapazität* 3+| Logisch oder physisch 
|===


== Leistungs-Servicelevels für AFX-Speicher

|===


| *Leistungsdienstleistungsebene* (alle Spezifikationen pro Leistungsdienstleistungsebeneninstanz [ein AFX-Speichercontroller]) | *Extreme* 


| *Unterstützte Protokolle* | NFSv3, NFSv4/RDMA, pNFS, SMB, S3 


| *Workload-Typen der Probe* | KI/ML, HPC, InMem-DB 


| *Ziel: 90^th^ Perzentillatenz* | <=1 ms 


| *Maximale Ziel-IOPS*^1^ | 625K 


| *Maximale Zielgeschwindigkeit GB/s* | 20 


| * Plattform* | AFX 


| *Mindestkapazität pro AFX-Cluster*^2^ | 200 tib 


| *Inkrementelle Erhöhung der zugesagten Kapazität* | 100 tib 


| *Art der gebuchten und gemessenen Kapazität* | Physisch 
|===
[NOTE]
====
* ^1^Sich gegenseitig ausschließende Ziele. Die tatsächliche Leistung kann je nach verschiedenen Faktoren, einschließlich Betriebssystemversion, Hardware, Workload-Typ und Anzahl gleichzeitiger Vorgänge, abweichen.
* ^2^In einem AFX-Cluster gelten die Leistungsziele pro Speichercontroller. Jeder dem Cluster hinzugefügte Controller trägt dieselbe IOPS-Zahl und denselben Durchsatz bei. Die zugesicherte Kapazität und inkrementelle Erweiterungen beziehen sich auf die gesamte Laufwerksschachtkapazität des Clusters.


====


== Leistungsmessbedingungen für einheitlichen, blockoptimierten und AFX-Speicher

Die grundlegenden Service-Level-Metriken für die Leistung hängen von den folgenden Bedingungen ab:

* Die Performance-Service-Levels unterstützen ONTAP 9.8 und höher.
* Für einheitlichen Speicher,
+
** *IOPS*: Für ONTAP 9.16.1 mit NFS unterstützt jede Instanz der Leistungsstufe wahlfreien Zugriff mit einem Leseverhältnis von 70 % und 30 % Schreibverhältnis, einer Blockgröße von 8 KB und einer Latenz von 1 ms (4 ms für Standard).
** *Durchsatz*: Bei ONTAP 9.16.1 mit NFS unterstützt jede Instanz der Leistungsstufe sequentiellen Zugriff mit 100 % Lesen und einer Blockgröße von 32 KB.


* Für blockoptimierte Speicherung,
+
** *IOPS*: Bei ONTAP 9.16.1 mit FCP unterstützt jede Performance-Level-Instanz wahlfreien Zugriff mit einem Leseverhältnis von 70 % und 30 % Schreibverhältnis, einer Blockgröße von 8 KB und einer Latenz von 1 ms.
** *Durchsatz*: Bei ONTAP 9.16.1 mit FCP unterstützt jede Instanz der Leistungsstufe sequentiellen Zugriff mit 100 % Lesen und einer Blockgröße von 64 KB.


* Für AFX-Speicher,
+
** *IOPS*: Bei ONTAP 9.18.1 mit NFSv4 unterstützt jede Performance-Level-Instanz den wahlfreien Zugriff mit einem Verhältnis von 70 % Lesen und 30 % Schreiben sowie einer Blockgröße von 4 KB.
** *Durchsatz*: Bei ONTAP 9.18.1 mit NFSv4 unterstützt jede Performance-Level-Instanz sequenziellen Zugriff mit 100 % Lesezugriff und einer Blockgröße von 64 KB.


* Die Latenz umfasst nicht Folgendes:
+
** Applikations- oder Host-Latenz erzielt
** Netzwerklatenz des Kunden zu bzw. von den Controller-Ports
** Gemeinkosten für die Datenübertragung an den Objektspeicher bei FabricPool


* Latenzwerte gelten nicht für MetroCluster-Schreibvorgänge. Diese Schreibvorgänge sind von der Entfernung von Remote-Systemen abhängig.
* _Expected IOPS_ wird nur für FabricPool angestrebt, wenn die Tiering-Richtlinie auf „keine“ gesetzt ist und sich keine Blöcke in der Cloud befinden. _Expected IOPS_ ist für Volumes bestimmt, die sich nicht in einer synchronen SnapMirror-Beziehung befinden.




== Leistungsservicelevel für Objektspeicher

|===


| *Leistungs-Service-Level* | *Standard* | *Wert* 


| *Unterstütztes Protokoll* 2+| S3 


| * Plattform* | SGF6112 | SG6160 


| *Mindestkapazität pro Bestellung* | 200 tib | 500 tib 


| *Inkrementelle Erhöhung der zugesagten Kapazität* | 25 tib | 100 tib 


| *Art der gebuchten und gemessenen Kapazität* 2+| Physisch 
|===


== Cloud-Storage

|===


| *Leistungs-Service-Level* | *Cloud Volumes ONTAP* 


| *Unterstützte Protokolle* | NFS, CIFS, iSCSI und S3 (nur AWS und Azure) 


| * Plattform* | Cloud Volumes ONTAP 


| *Mindestkapazität pro Bestellung* | 4 tib 


| *Inkrementelle Erhöhung der zugesagten Kapazität* | 1 tib 


| *Art der gebuchten und gemessenen Kapazität* | Logisch 
|===
[NOTE]
====
* Cloud-native Services wie Computing, Storage, Netzwerk werden von Cloud-Providern in Rechnung gestellt.
* Diese Services hängen von Cloud-Storage- und Computing-Merkmalen ab.


====
*Verwandte Informationen*

* link:../concepts/supported-storage-capacity.html["Speicherkapazitätstypen in Keystone"]
* link:..//concepts/metrics.html["Metriken und Definitionen für Keystone Services"]
* link:../concepts/pricing.html["Keystone-Preisgestaltung"]

