---
sidebar: sidebar 
permalink: concepts/supported-storage-services.html 
keywords: storage, service, service definition, keystone STaaS services, 
summary: Keystone StaaS-Services unterstützt ONTAP und StorageGRID. 
---
= Unterstützter Storage in Keystone
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Keystone STaaS unterstützt einheitlichen, blockoptimierten, AFX- und Objektspeicher auf NetApp Plattformen sowie Cloud Volumes ONTAP. Jeder Speichertyp ist als Datenspeichertyp (DST) definiert und mit den im Basisabonnement enthaltenen Standarddiensten sowie optionalen Zusatzdiensten verfügbar.



== Keystone STaaS Standard- und Zusatzdienste

Keystone STaaS bietet Standard- und optionale Services für Ihren Storage.

*Keystone STaaS Standard Services*: Standard-Services sind im Basisabonnement inbegriffen und werden nicht separat berechnet.

*Keystone STaaS Add-on-Services*: Diese sind optionale, kostenpflichtige Services, die zusätzlich zu den Standard-Keystone STaaS-Abonnementservices zusätzliche Dienstprogramme und Vorteile bieten.

Sie können mehrere Keystone STaaS-Dienste gleichzeitig abonnieren. Wenn Cloud-Dienste zu einem Abonnement hinzugefügt werden, gilt für sie dieselbe Laufzeit wie für Unified, Block-Optimized und/oder Object Storage. Ein Cloud-Dienst kann jederzeit während eines aktiven Speicherabonnements hinzugefügt werden. Wenn Sie jedoch ein bestehendes Unified-, Block-Optimized- oder Object-Storage-Abonnement nicht verlängern möchten, kann in den letzten 90 Tagen dieses Abonnements kein Cloud-Dienst hinzugefügt werden.


NOTE: Ein AFX-Abonnement ist eigenständig und kann nicht mit einheitlichem, blockoptimiertem oder Objektspeicher im selben Abonnement kombiniert werden. Wenn Sie AFX zusammen mit anderen Speichertypen benötigen, müssen Sie diese als separate Abonnements bestellen.



== Unterstützte Datenspeichertypen

Keystone STaaS-Dienste für einheitlichen, blockoptimierten, objektorientierten und AFX-Speicher unterstützen zahlreiche Funktionen und Protokolle und sind in der folgenden Tabelle beschrieben:

|===
| Datenspeichertyp | Beschreibung | Plattform | Protokolle | Unterstützte Funktionen 


 a| 
Vereinheitlicht
 a| 
Beinhaltet Datei-, Block- und S3-Objektspeicherung
 a| 
ONTAP auf AFF und FAS-Systemen
 a| 
FC, iSCSI, NFS, NFSv4/RDMA, NVMe/FC, NVMe/TCP, SMB, S3
 a| 
Unterstützt alle ONTAP One-Funktionen



 a| 
Blockoptimiert
 a| 
Beinhaltet Blockspeicherung
 a| 
NVMe/TCP, NVMe/FC, FC, iSCSI
 a| 
FC und iSCSI
 a| 
Unterstützt alle ONTAP One for SAN-Funktionen



 a| 
AFX
 a| 
Beinhaltet Datei- und Objektspeicherung auf einer disaggregierten Speicherplattform
 a| 
ONTAP auf AFX-Systemen
 a| 
NFSv3, NFSv4/RDMA, pNFS, SMB, S3
 a| 
Unterstützt alle ONTAP One-Funktionen



 a| 
Objekt
 a| 
Beinhaltet Objektspeicherung
 a| 
StorageGRID
 a| 
S3
 a| 
Unterstützt alle StorageGRID-Funktionen

|===
Weitere Informationen zu ONTAP One finden Sie unter link:https://docs.netapp.com/us-en/ontap/system-admin/manage-licenses-concept.html#licenses-included-with-ontap-one["Übersicht über die ONTAP-Lizenzierung"^] Und link:https://www.netapp.com/blog/ontap-one/["ONTAP One: Die volle Leistung von ONTAP, jetzt alles in einem"^] .



== Services für Cloud Storage

Keystone STaaS bietet Cloud-Storage-Services. Keystone STaaS unterstützt Cloud Volumes ONTAP-Datenmanagementfunktionen auf Amazon Web Services (AWS), Microsoft Azure und Google Cloud Platform.


NOTE: Von Hyperscalern bereitgestellte Compute-, Storage- und Netzwerkservices, die von Cloud Volumes ONTAP benötigt werden, werden nicht von NetApp im Rahmen der Keystone STaaS-Abonnements bereitgestellt; diese Abonnements müssen direkt von Hyperscaler-Cloud-Service-Anbietern bezogen werden.
