---
sidebar: sidebar 
permalink: concepts/supported-storage-services.html 
keywords: storage, service, service definition, keystone STaaS services, 
summary: Keystone StaaS-Services unterstützt ONTAP und StorageGRID. 
---
= Unterstützter Storage in Keystone
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Die Keystone STaaS-Services unterstützen Storage auf Datei- und Block-Ebene von ONTAP, Objekt-Storage der StorageGRID Plattform und die Datenmanagementfunktionen von Cloud Volumes ONTAP.

Keystone STaaS bietet Standard- und optionale Services für Ihren Storage.

*Keystone STaaS Standard Services*: Standard-Services sind im Basisabonnement inbegriffen und werden nicht separat berechnet.

*Keystone STaaS Add-on-Services*: Diese sind optionale, kostenpflichtige Services, die zusätzlich zu den Standard-Keystone STaaS-Abonnementservices zusätzliche Dienstprogramme und Vorteile bieten.

Keystone STaaS Services können nebeneinander bestehen. Ein Cloud-Storage-Abonnement kann beispielsweise neben Datei-, Block- und Objekt-Storage-Abonnements genutzt werden. Während der Servicezeit eines vorhandenen Storage-Abonnements kann ein Cloud-Service an jedem Punkt inbegriffen sein. Wenn Sie jedoch keine Möglichkeit haben, ein vorhandenes Datei-, Block- und Objekt-Abonnement zu verlängern, kann ein Cloud-Storage-Abonnement während der letzten 90 Tage des Abonnements nicht hinzugefügt werden.



== Services für File-, Block- und Objekt-Storage

Keystone STaaS Services für ONTAP-File- und Block-Storage sowie StorageGRID-Objekt-Storage unterstützen zahlreiche Funktionen und Protokolle. Beschreibung in der folgenden Tabelle:

|===
| Storage | Plattform | Protokolle | Unterstützte Funktionen 


 a| 
File-Storage
 a| 
ONTAP
 a| 
NFS und CIFS
 a| 
Unterstützte ONTAP-Funktionen:

* FlexVol
* FlexGroup
* Snapshots
* SnapMirror (asynchron)
* SnapVault
* SnapLock Enterprise
* FabricPool/Cloud Tiering
* SnapRestore
* FlexClone
* SnapCenter (Lizenz ist inbegriffen, ist aber nicht Bestandteil der Keystone Services und das Management ist nicht garantiert.)
* Autonomer Ransomware-Schutz^1^




 a| 
Block-Storage
 a| 
ONTAP
 a| 
FC und iSCSI
 a| 
Unterstützte ONTAP-Funktionen:

* FlexVol
* FlexGroup
* Snapshots
* SnapMirror (asynchron)
* SnapVault
* SnapLock Enterprise
* FabricPool/Cloud Tiering
* SnapRestore
* FlexClone
* SnapCenter (Lizenz ist inbegriffen, ist aber nicht Bestandteil der Keystone Services und das Management ist nicht garantiert.)




 a| 
Objekt-Storage
 a| 
StorageGRID
 a| 
S3
 a| 
Unterstützt mehrere ILM-Richtlinien (Information Lifecycle Management) über mehrere Standorte hinweg^2^

|===

NOTE: ^1^ Informationen zum Ransomware-Schutz in ONTAP finden Sie unter https://docs.netapp.com/us-en/ontap/anti-ransomware/index.html["Autonomer Schutz Durch Ransomware"^].
^2^ für jede Site ist ein separates Abonnement erforderlich.



== Services für Cloud Storage

Keystone STaaS bietet Cloud-Storage-Services. Keystone STaaS unterstützt Cloud Volumes ONTAP-Datenmanagementfunktionen auf Amazon Web Services (AWS), Microsoft Azure und Google Cloud Platform.


NOTE: Die von Cloud Volumes ONTAP benötigten Hyperscale-basierten Computing-, Storage- und Netzwerk-Services werden von NetApp nicht als Bestandteil der Keystone STaaS-Abonnements bereitgestellt. Diese Abonnements müssen direkt von Hyperscale-Cloud-Service-Providern erworben werden.
