---
sidebar: sidebar 
permalink: concepts/supported-storage-capacity.html 
keywords: storage capacity, capacity definition, keystone STaaS storage capacity, 
summary: Informieren Sie sich über die Speicherkapazitätstypen, die vom NetApp Keystone STaaS-Dienst für Version 3 unterstützt werden. 
---
= Speicherkapazitätstypen in Keystone
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Keystone STaaS verwendet verschiedene Kapazitätsbegriffe, um Speicherplatz zu messen, zuzuweisen und abzurechnen. Wenn Sie diese Begriffe verstehen, können Sie Ihr Abonnement planen und Ihre Nutzungsberichte und Rechnungen besser interpretieren.



== Logische Kapazität

Dies ist die Speicherkapazität, die zum Speichern von Benutzerdaten erforderlich ist, bevor die vom Speicherarray bereitgestellten Dateneffizienzen angewendet werden.



== Engagierte Kapazität

Die minimale logische Kapazität, die während des Abonnements monatlich in Rechnung gestellt wird:

* Die Kapazität wird jeder Performance-Service-Level-Instanz für einheitlichen oder blockoptimierten Storage bzw. pro AFX-Cluster zugewiesen.
* Während der Laufzeit können gebundene Kapazitäten und zusätzliche Leistungsservice-Levels hinzugefügt werden.




=== Änderungen der zugesagt Kapazität

Während eines Abonnements können Sie die zugesicherten Kapazitäten unter bestimmten Bedingungen ändern. Ausführliche Informationen zu den Regeln für Kapazitätserhöhungen und -reduzierungen finden Sie unter link:../concepts/capacity-requirements.html["Kapazitätsanforderungen für Keystone Leistungs-Servicelevel"]. Um eine Änderung zu beantragen, wenden Sie sich an Ihren Keystone Success Manager (KSM) oder link:../concepts/support-services.html["NetApp Support"].



== Verbrauchte Kapazität

Die belegte Kapazität bezieht sich auf die Kapazität (in TiB Speicher), die aktuell vom Dienst genutzt wird. Sie wird je nach Datenspeichertyp unterschiedlich berechnet:

* *Einheitlicher oder blockoptimierter Speicher*: Die verbrauchte Kapazität wird basierend auf der Art der Kapazität (entweder logisch oder physisch) berechnet, die während des Bestellvorgangs ausgewählt wurde.  Die Berechnung erfolgt pro Performance-Service-Level-Instanz.
+
.. *Logische Kapazität*: Sie ist die Summe aus:
+
*** Gemessene logische Kapazität vor Dateneffizienz des Speicherarrays zum Speichern aller Instanzen und Typen von Kundendaten, z. B. Kopien, gespiegelte Kopien, Versionen und Klone.
*** Physische Kapazität, die zum Speichern von Metadaten und differenziellen Daten von Snapshots und bestimmten Klonen verwendet wird.
*** Jede physisch bereitgestellte Kapazität mit hoher Kapazität.


.. *Körperliche Leistungsfähigkeit*: Sie ist die Summe aus:
+
*** Gemessene physische Kapazität, nach Berücksichtigung der Dateneffizienz des Storage Arrays, zur Speicherung aller Instanzen und Arten von Kundendaten, wie Kopien, gespiegelte Kopien, Versionen und Klone.
*** Physische Kapazität zum Speichern von Metadaten und differenziellen Daten von Snapshots.
*** Jede physisch bereitgestellte Kapazität mit hoher Kapazität.




* *AFX-Speicher*: Er wird pro AFX-Cluster als Summe folgender Werte berechnet:
+
** Gemessene physische Kapazität, nach Berücksichtigung der Dateneffizienz des Storage Arrays, zur Speicherung aller Instanzen und Arten von Kundendaten, wie Kopien, gespiegelte Kopien, Versionen und Klone.
** Physische Kapazität zum Speichern von Metadaten und differenziellen Daten von Snapshots.
** Jede physisch bereitgestellte Kapazität mit hoher Kapazität.


* *Objektspeicher*: Die verbrauchte Kapazität wird als die gemessene physische Kapazität berechnet, die zum Speichern aller Instanzen und Typen von Kundendaten auf allen Knoten verwendet wird. Diese Berechnung basiert auf den konfigurierten Richtlinien für das Information Lifecycle Management (ILM).
* *Cloud Volumes ONTAP*: Die verbrauchte Kapazität wird als die Menge der gemessenen, bereitgestellten logischen Kapazität aller Cloud Volumes ONTAP Volumes berechnet.




== Burst-Kapazität

Mit dem NetApp Keystone STaaS-Service können Sie zusätzlich zur zugesicherten Kapazität für einen Performance-Servicelevel zusätzliche Kapazität nutzen. Dies wird als Burst-Kapazitätsnutzung bezeichnet.

Beachten Sie folgende Punkte:

* Die maximale Burst-Kapazität wird in der Keystone-Bestellung vereinbart. Sie ist üblicherweise auf 20 % über der zugesicherten Kapazität pro Performance-Service-Level-Instanz oder pro AFX-Cluster festgelegt, mit zusätzlichen Optionen für Unified und Block-Optimized Storage, um Burst-Kapazitätsgrenzen von 40 % oder 60 % der zugesicherten Kapazität auszuwählen.
* Die Inanspruchnahme von Burst-Kapazität wird zum gleichen Tarif abgerechnet wie die zugesagte Kapazität entsprechend dem gewählten Datenspeichertyp (DST) und dem Leistungs-Servicelevel.
* Keystone STaaS-Dienste bieten eine Verzichtsfrist von 60 Tagen ab dem Startdatum.




== Rechnungskapazität

Monatliche Rechnung = (engagierte Kapazität [tib] * engagierte Rate [€/tib]) + (durchschnittliche tägliche bereitgestellte Burst-Kapazität [tib] * Burst-Rate [€/tib]). Die monatliche Abrechnung enthält eine Mindestgebühr, die sich auf die engagierte Kapazität basiert.

Die monatliche Rechnung variiert über die Mindestgebühr basierend auf dem täglichen durchschnittlichen Burst-Kapazitätsverbrauch.
