---
sidebar: sidebar 
permalink: concepts/supported-storage-services.html 
keywords: storage, service, service definition, keystone STaaS services, 
summary: Keystone StaaS-Services unterstützt ONTAP und StorageGRID. 
---
= Unterstützter Storage in Keystone
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Keystone STaaS-Dienste für Version 3 (v3) unterstützen einheitlichen, blockoptimierten und Objektspeicher von NetApp und Cloud Volumes ONTAP.

Jeder Speichertyp umfasst:

* *Unified Storage*: Umfasst sowohl Datei-, Block- als auch S3-Objektspeicher, verfügbar auf NetApp ONTAP AFF- und FAS-Systemen.
* *Blockoptimierter Speicher*: Beinhaltet Blockspeicher, der auf NetApp ONTAP ASA-Systemen verfügbar ist.
* *Objektspeicher*: Beinhaltet den auf NetApp StorageGRID-Systemen verfügbaren Objektspeicher.


Keystone STaaS bietet Standard- und optionale Services für Ihren Storage.

*Keystone STaaS Standard Services*: Standard-Services sind im Basisabonnement inbegriffen und werden nicht separat berechnet.

*Keystone STaaS Add-on-Services*: Diese sind optionale, kostenpflichtige Services, die zusätzlich zu den Standard-Keystone STaaS-Abonnementservices zusätzliche Dienstprogramme und Vorteile bieten.

Keystone STaaS-Dienste können gleichzeitig genutzt werden. Beispielsweise kann ein Cloud-Speicher-Abonnement die gleiche Laufzeit haben wie Abonnements für einheitlichen, blockoptimierten oder Objektspeicher. Während der Servicezeit eines vorhandenen Storage-Abonnements kann ein Cloud-Service an jedem Punkt inbegriffen sein. Wenn Sie jedoch ein bestehendes Abonnement für einheitlichen, blockoptimierten oder Objektspeicher nicht verlängern möchten, kann innerhalb der letzten 90 Tage des Abonnements kein weiteres Cloud-Speicher-Abonnement hinzugefügt werden.



== Dienste für einheitlichen, blockoptimierten und Objektspeicher

Keystone STaaS-Dienste für einheitliche, blockoptimierte und Objektspeicherung unterstützen mehrere Funktionen und Protokolle und werden in der folgenden Tabelle beschrieben:

|===
| Storage | Plattform | Protokolle | Unterstützte Funktionen 


 a| 
Unified Storage
 a| 
ONTAP
 a| 
NFS und CIFS
 a| 
Unterstützt alle ONTAP One-Funktionen



 a| 
Blockoptimierter Speicher
 a| 
ONTAP
 a| 
FC und iSCSI
 a| 
Unterstützt alle ONTAP One-Funktionen



 a| 
Objekt-Storage
 a| 
StorageGRID
 a| 
S3
 a| 
Unterstützt alle ONTAP One-Funktionen

|===
Weitere Informationen zu ONTAP One finden Sie unter link:https://docs.netapp.com/us-en/ontap/system-admin/manage-licenses-concept.html#licenses-included-with-ontap-one["Übersicht über die ONTAP-Lizenzierung"^] Und link:https://www.netapp.com/blog/ontap-one/["ONTAP One: Die volle Leistung von ONTAP, jetzt alles in einem"^] .



== Services für Cloud Storage

Keystone STaaS bietet Cloud-Storage-Services. Keystone STaaS unterstützt Cloud Volumes ONTAP-Datenmanagementfunktionen auf Amazon Web Services (AWS), Microsoft Azure und Google Cloud Platform.


NOTE: Die von Cloud Volumes ONTAP benötigten Hyperscale-basierten Computing-, Storage- und Netzwerk-Services werden von NetApp nicht als Bestandteil der Keystone STaaS-Abonnements bereitgestellt. Diese Abonnements müssen direkt von Hyperscale-Cloud-Service-Providern erworben werden.
