---
sidebar: sidebar 
permalink: concepts/support-services.html 
keywords: Keystone support, service request, support ticket 
summary: Verwenden Sie die NetApp Support-Website, um einen Supportfall zu erstellen oder Kontaktinformationen für Ihre Keystone-Abonnements zu finden. 
---
= Keystone hilft Ihnen dabei
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NetApp bietet Keystone-Kunden operative Dienstleistungen. Kunden erhalten einen dedizierten Keystone Success Manager (KSM), direkte Support-Kontaktoptionen und proaktives Monitoring durch die ITOM-Lösung.



== NetApp Support-Services

NetApp bietet Keystone-Kunden operative Dienstleistungen aus der Ferne an. Diese Dienstleistungen umfassen ein breites Spektrum an Speichermanagementaktivitäten, darunter Anlagen- und Konfigurationsmanagement, Kapazitäts- und Leistungsmanagement, Änderungsmanagement, Ereignis- und Störungsmanagement, Bearbeitung von Serviceanfragen und Berichtswesen.

.Keystone Success Manager
Ihr KSM arbeitet eng mit Ihnen an Ihren Keystone-Services zusammen und stellt wöchentliche oder monatliche Abrechnungs- und Betriebsberichte bereit. Die spezifischen Verantwortlichkeiten sind in Ihrer NetApp Keystone-Vereinbarung definiert.



== Kontaktieren Sie den Support

Sollten Sie ein Problem mit Ihrem Keystone-Abonnement haben, melden Sie sich beim link:https://support.netapp.com["NetApp Support Site"^] mit Ihren NSS-Zugangsdaten an, um einen Supportfall zu erstellen.

Falls Sie keinen NSS-Login besitzen, link:https://mysupport.netapp.com/site/user/registration["Registrieren Sie Ihr Konto"^] verwenden Sie die Seriennummer (SN) eines der Knoten in Ihrem Abonnement.

Eine Schritt-für-Schritt-Anleitung mit Screenshots finden Sie unter link:https://kb.netapp.com/nss/Support_Site/How_to_open_a_technical_support_case["Wie man einen technischen Supportfall eröffnet"^].

Wenn Sie lieber direkt mit einem Supportmitarbeiter sprechen möchten, rufen Sie eine der folgenden Nummern an:

* USA / Kanada: 888 463 8277
* Europa: 00 800 44 638277
* Indien: 000 800 100 8948
* Weitere globale Zahlen: link:https://www.netapp.com/company/contact-us/support/["https://www.netapp.com/company/contact-us/support/"^]




== Supportüberwachung

NetApp nutzt die ITOM-Überwachungslösung, um den Zustand Ihrer Produkte und abonnierten Dienste proaktiv zu überwachen und eine Verbindung zur NetApp Keystone-Umgebung zur Fehlerbehebung herzustellen.



== Zusätzliche Ressourcen

Weitere Informationen zu Keystone Services finden Sie unter:

* link:https://www.netapp.com/us/solutions/keystone/index.aspx["NetApp Keystone"^]
* link:https://docs.netapp.com["NetApp Produktdokumentation"^]


*Verwandte Informationen*

* link:https://kb.netapp.com/on-prem/ontap/OHW/OHW-KBs/How_to_Identify_Serial_Number_of_ONTAP_Platform["Wie man die Seriennummer der ONTAP Plattform ermittelt"^]
* link:https://kb.netapp.com/hybrid/StorageGRID/Maintenance/Which_serial_number_to_use_when_creating_StorageGRID_technical_support_case["Welche Seriennummer ist beim Erstellen eines StorageGRID Supportfalls zu verwenden?"^]

