---
sidebar: sidebar 
permalink: concepts/support-services.html 
keywords: Keystone support, service request, support ticket 
summary: Wenn Sie Hilfe benötigen, wenden Sie sich bitte an das NetApp Keystone Support-Team. 
---
= Keystone hilft Ihnen dabei
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Das NetApp Keystone Support-Team und der Keystone Success Manager (KSM) stellen Ihnen Service für Ihre Keystone Abonnements zur Verfügung. Bei Fragen wenden Sie sich bitte an das Keystone Supportteam.



== NetApp Keystone-Support

NetApp bietet NetApp Keystone Kunden Remote operative Services. Diese Services umfassen Betriebsdisziplinen zu Storage Management-Aktivitäten. Zu diesen Services gehören Asset- und Konfigurationsmanagement, Kapazitäts- und Performance-Management, Änderungsmanagement, Ereignisse, Vorfall- und Problemmanagement, Bearbeitung von Serviceanfragen und Berichterstellung. NetApp weist bei Bedarf einen Zustand der Kontrolle und unterstützende Nachweise nach.



== Weitere Informationen

NetApp nutzt die ITOM Monitoring-Lösung, um proaktiv die NetApp Keystone Umgebung zu überwachen und zur Fehlerbehebung eine Verbindung mit ihr herzustellen.


NOTE: In einem von Partnern betriebenen Modell werden die Service-Anfragen des Mandanten und des Submandanten dem Service-Desk des Partners zugewiesen. Das Support-Tool des Partners ist möglicherweise mit der ITOM Lösung integriert.

Weitere Informationen zu Keystone Services finden Sie unter:

* NetApp Keystonehttps://www.netapp.com/us/solutions/keystone/index.aspx["https://www.netapp.com/us/solutions/keystone/index.aspx"^]
* NetApp Produktdokumentationhttps://docs.netapp.com["https://docs.netapp.com"^]




== Keystone-Support-Monitoring

Der NetApp Keystone Support überwacht den Zustand Ihrer Produkte und abonnierten Services, bietet Remote-Support und arbeitet mit Ihrem Keystone Success Manager zusammen.

.Keystone Success Manager
Der Keystone Success Manager (KSM) arbeitet bei Ihren Keystone Services eng mit Ihnen zusammen und aktualisiert Sie bei wöchentlichen oder monatlichen Abrechnungs- und Betriebsberichten. Die Verantwortlichkeiten werden in Ihrer NetApp Keystone-Vereinbarung festgelegt.



== Serviceanforderungen werden erstellt

Wenn Sie während des Onboarding Zugangsdaten für den Zugriff auf NetApp Keystone ServiceNow und die Verwendung von erhalten haben, können Sie über das Portal Serviceanfragen bei Problemen Ihrer Keystone Abonnements generieren:

https://netappkeystone.service-now.com/csm[]

Stellen Sie sicher, dass Sie die Systemdetails, Protokolle und zugehörigen Informationen bereit haben, bevor Sie die Serviceanfrage senden. Wenn Sie eine Service-Anfrage stellen, erhält das Keystone Support-Team das Support-Ticket und greift auf die Informationen zur Fehlerbehebung zu. Sie können Ihrem ServiceNow-Ticket folgen, um den Status und die Lösung zu erfahren.

Informationen zum Hinzufügen von Supportpaketen finden Sie unter link:../installation/monitor-health.html["Support Bundle generieren und sammeln"].

Falls Sie über einen offenen Fall/ein Ticket verfügen, der eskaliert werden muss, senden Sie eine E-Mail an eine der folgenden Adressen: keystone.services@netapp.com keystone.escalations@netapp.com
