---
sidebar: sidebar 
permalink: concepts/data-tiering.html 
keywords: add-on services, add-on, data tiering 
summary: Add-on, zusätzliche Service-Details, Daten-Tiering 
---
= Daten-Tiering
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Die Keystone Basis-Services umfassen standardmäßig Tiering-Funktionen für Ihre abonnierten Datei- und Block-Services, mit denen weniger häufig genutzte Daten identifiziert werden, und verschieben sie in einen Cold Storage, der im Besitz von NetApp ist, bereitgestellt und von NetApp gemanagt wird. Sie können Tiering als Add-on-Service nutzen, wenn Sie Ihre kalten Daten auf beliebigen Storage anderer Anbieter, wie z. B. jedem beliebigen Enterprise-Cloud-Storage, verschieben möchten.

Der Tiering-Add-on Service ist nur erforderlich, wenn Daten auf Storage anderer Anbieter verteilt werden, wie z. B. Amazon Web Services (AWS) S3, Azure Blob, Google Cloud Platform (GCP) und andere, unterstützte S3-kompatible Objekt-Storage von Drittanbietern.

Weitere Informationen über den Basis-Storage und den Cloud-Storage-Service finden Sie unter link:../concepts/supported-storage-services.html["Unterstützte Storage-Services"].

Informationen zu Service-Levels finden Sie unter link:../concepts/service-levels.html["Service-Level in Keystone"].

Die Tiering-Funktion nutzt die NetApp FabricPool Technologie, mit der Daten-Tiering auf kostengünstige Objekt-Storage Tiers entweder lokal oder extern durchgeführt werden können. Bei dieser Funktion werden selten genutzte Daten auf Grundlage der vereinbarten Services automatisch auf kostengünstigeren Storage verschoben – entweder vor Ort oder in der Cloud.

Der Add-on-Tiering-Service ermöglicht Tiering für den Extreme-, Premium-, Performance-, Standard- und Value-Tier zu einem Objektziel. Der Hot-Tier und der kalte Tier werden getrennt gemessen und in Rechnung gestellt.

Daten-Tiering kann jederzeit und ohne Preisänderung hinzugefügt werden und sorgt für mehr Flexibilität bei dem „Hot:Cold“-Verhältnis. Das Verhältnis der zu schichtigen häufig:kalten Daten ist nicht festgelegt und die Anzahl der physischen Tiered-Blöcke wird separat gemessen.

Weitere Informationen finden Sie in den folgenden Berechnungen:

Wenn das Ziel für Cold Storage Tier lautet:

* Wertebene (bis zu 500 tib), Objektebene (>500tib), vorhandenes SGWS Grid (kundeneigener) – Es fallen keine zusätzlichen Gebühren an, es ist Teil des Basis-Storage-Service.
* Public Cloud (AWS, Azure, Google) und jeder andere von Drittanbietern unterstützte Objekt-Storage – eine zusätzliche Gebühr für Datenkapazität, die als Out-Tier berechnet wird, ist kostenpflichtig.


Die mit dem Add-on-Tiering-Abonnement verbundenen Gebühren werden nicht einmalig berechnet. Die IT muss während des gesamten Laufzeit bezahlt werden, um die Tiering-Beziehung zwischen den On-Premises-Datei- und Block-Services und dem von Drittanbietern unterstützten Objekt-Storage-Ziel aufrechtzuerhalten.

Mit diesem Angebot können kalte Daten nur auf kostengünstigeren Ziel-Storage Tier und nicht die Kosten der Public-Cloud/Hyperscale-Infrastruktur Tier platziert werden.


NOTE: Hyperscale-basierte Computing- und Storage-Infrastrukturen stehen NetApp nicht als Teil Ihrer Keystone-Abonnements zur Verfügung. Sie müssen sie von einem Hyperscale Cloud-Service-Provider erwerben.
