---
sidebar: sidebar 
permalink: concepts/data-tiering.html 
keywords: add-on services, add-on, data tiering 
summary: Add-on, zusätzliche Service-Details, Daten-Tiering 
---
= Daten-Tiering
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Der NetApp Keystone (Keystone) Service umfasst eine Tiering-Funktion für abonnierte Datei- und Block-Services, mit der selten genutzte Daten identifiziert und in einem Cold Storage verschoben werden, der sich im Besitz von NetApp befindet, bereitgestellt und gemanagt wird.

Sie können diese zusätzlichen Services als Teil Ihres Keystone Abonnements abonnieren. Weitere Informationen über den Basis-Storage und den Cloud-Storage-Service finden Sie unter link:../concepts/supported-storage-services.html["Unterstützte Storage-Services"]

Informationen zu Service-Levels finden Sie unter link:../concepts/service-levels.html["Service-Level in Keystone"]


NOTE: Daten-Tiering zu einem NetApp Storage-Ziel ist standardmäßig in Datei- und Block-Storage-Service-Tiers enthalten. Der Add-on Service ist nur erforderlich, wenn Daten Storage anderer Anbieter wie AWS S3, Azure Blob und EMC ECS per Tiering verteilt werden.

Die Tiering-Funktion nutzt die NetApp FabricPool Technologie, mit der Daten-Tiering auf kostengünstige Objekt-Storage Tiers entweder lokal oder extern durchgeführt werden können. Bei dieser Funktion werden selten genutzte Daten auf Grundlage der vereinbarten Services automatisch in einen kostengünstigeren Storage verschoben – entweder vor Ort oder in der Cloud.

Der Tiering-Service ermöglicht Tiering vom Extreme, Premium, Performance, Standard und Value Tier zu einem Objektziel. Der Hot-Tier und der kalte Tier werden getrennt gemessen und in Rechnung gestellt. Daten-Tiering kann jederzeit und ohne Preisänderung hinzugefügt werden und erhöht die Flexibilität im Verhältnis „heiße“, kalte Daten:

Gehen Sie die folgenden Berechnungen durch, um das besser zu verstehen:

Wenn das Ziel für Cold Storage Tier lautet:

* Wert Tier (bis zu 500 tib), Objekt-Tier (>500tib), vorhandenes SGWS Grid (Kundenbesitz) – Es entstehen keine zusätzlichen Gebühren, und es ist Teil des Basis-Storage-Service.
* Public Cloud (AWS, Azure, Google) und jeder andere von Drittanbietern unterstützte Objekt-Storage – eine zusätzliche Gebühr für Datenkapazität, die als Out-Tier berechnet wird, ist kostenpflichtig.


Für das Add-on-Tiering-Abonnement fallen keine Gebühren an, die einmalige Gebühr erhoben werden. Die Lösung muss für die gesamte Laufzeit bezahlt werden, um die Tiering-Beziehung zwischen den Keystone On-Premises-Datei- und Block-Services und dem von Drittanbietern unterstützten Objekt-Storage-Ziel aufrechtzuerhalten.

Mit diesem Angebot können kalte Daten nur auf kostengünstigeren Ziel-Storage Tier und nicht die Kosten der Public-Cloud/Hyperscale-Infrastruktur Tier platziert werden.


NOTE: Hyperscale-basierte Computing- und Storage-Infrastrukturen stehen NetApp nicht als Teil Ihrer Keystone-Abonnements zur Verfügung. Sie müssen sie bei einem Hyperscale Cloud-Service-Provider erwerben.
