---
sidebar: sidebar 
permalink: concepts/usps-v2.html 
keywords: netapp, keystone, US citizen support, USPS, Keystone Success Manager, USPS support 
summary: In den USA ist Protected Support ein Add-on-Service, der die Bereitstellung und den Support von laufenden Keystone Services durch US-Bürger auf US-amerikanischem Boden ermöglicht. 
---
= Erfahren Sie mehr über USPS
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
US Protected Support (USPS) ist ein Add-On-Angebot für NetApp Keystone-Abonnements. Sie erhalten damit das Recht, die laufenden Keystone Services von US-Staatsbürgern auf US-amerikanischem Boden bereitzustellen und zu unterstützen.

Lesen Sie die folgenden Abschnitte, um zu erfahren, welche Elemente Ihrer Abonnements von diesem Add-on-Service gebunden sind und unter den Bedingungen der NetApp Keystone-Vereinbarung zur Verfügung gestellt werden.Fußnote:haftungsausschluss1[die hier beschriebenen Services und Angebote unterliegen einer vollständig ausgeführten Keystone-Vereinbarung und unterliegen diesen Einschränkungen.]



== NetApp USPS-Überwachung

Das NetApp Keystone Supportteam überwacht den Zustand Ihrer Produkte und abonnierten Services, bietet Remote-Support und arbeitet mit Ihrem Keystone Success Manager zusammen. Alle Mitarbeiter, die die Produkte im Zusammenhang mit den jeweiligen Keystone Abonnementbestellungen überwachen, sind aus S Bürger, die auf US-Boden tätig sind.



== Keystone Success Manager

Der Keystone Success Manager (KSM) ist ein USA US-Bürger ist tätig Bereitgestellt. Deren Verantwortlichkeiten werden in Ihrer NetApp Keystone-Vereinbarung festgelegt.



== Implementierungsaktivitäten

Sofern verfügbar, werden die Implementierungs- und Installationsaktivitäten vor Ort oder per Remote-Zugriff von US-amerikanischen Unternehmen durchgeführt US-Bürger Bereitgestellt. Fußnote:Haftungsausschluss[die Verfügbarkeit eines geeigneten Personals für Aktivitäten vor Ort hängt vom geografischen Standort ab, an dem die Keystone Systeme implementiert werden.]



== Unterstützung

Sofern verfügbar, werden die notwendigen Fehlerbehebungs- und Support-Aktivitäten vor Ort von US-amerikanischen durchgeführt US-Bürger Bereitgestellt. Fußnote:Haftungsausschluss[]
