---
sidebar: sidebar 
permalink: installation/addl-req.html 
keywords: keystone unified manager prerequisites, aiqum config keystone 
summary: Voraussetzungen für keystone Unified Manager 
---
= Zusätzliche Voraussetzungen für ONTAP und StorageGRID
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Sie sollten einige zusätzliche Voraussetzungen für ONTAP und StorageGRID erfüllen. Stellen Sie sicher, dass Sie zusätzlich zu den Systemanforderungen für Linux/VMware vSphere diese spezifischen Voraussetzungen erfüllt haben. Klicken Sie auf die gewünschte Registerkarte, um mehr zu erfahren.

[role="tabbed-block"]
====
.ONTAP
--
Führen Sie für die Installation von Keystone Collector in ONTAP die folgenden Schritte als Voraussetzungen aus:

. Stellen Sie sicher, dass ein Active IQ Unified Manager-Server (Unified Manager) mit Unified Manager 9.7 oder höher konfiguriert ist. Informationen zum Installieren von Unified Manager finden Sie unter den folgenden Links:
+
** https://["Installation von Unified Manager auf VMware vSphere Systemen"^]
** https://["Installation von Unified Manager auf Linux Systemen"^]


. Stellen Sie sicher, dass das ONTAP-Cluster zu Unified Manager hinzugefügt wurde. Informationen zum Hinzufügen von Clustern finden Sie unter https://["Hinzufügen von Clustern"^].
. Erstellen Sie Unified Manager Benutzer mit spezifischen Rollen für die Erfassung von Nutzungs- und Performance-Daten. Führen Sie diese Schritte aus. Informationen zu Benutzerrollen finden Sie unter https://["Definitionen von Benutzerrollen"^].
+
.. Melden Sie sich bei der Unified Manager-Web-Benutzeroberfläche mit den Standardanmeldeinformationen des Anwendungsadministrators an, die während der Installation generiert werden. Siehe https://["Zugriff auf die Web-Benutzeroberfläche von Unified Manager"^].
.. Erstellen Sie mit ein Servicekonto für Keystone Collector `Operator` Benutzerrolle. Die Keystone Collector Service-APIs verwenden dieses Servicekonto für die Kommunikation mit Unified Manager und die Erfassung von Nutzungsdaten. Siehe https://["Benutzer hinzufügen"^].
.. Erstellen Sie ein `Database` Benutzerkonto, mit `Report Schema` Rolle: Dieser Benutzer ist für die Erfassung von Leistungsdaten erforderlich. Siehe https://["Erstellen eines Datenbankbenutzers"^].


. Aktivieren Sie API Gateway in Unified Manager. Keystone Collector verwendet die API-Gateway-Funktion zur Kommunikation mit ONTAP-Clustern. Sie können das API-Gateway entweder über die Web-UI oder durch Ausführen einiger Befehle über die Unified Manager-CLI aktivieren.
+
.Web-UI
Um das API-Gateway über die Web-Benutzeroberfläche von Unified Manager zu aktivieren, melden Sie sich bei der Web-UI von Unified Manager an und aktivieren Sie das API-Gateway. Weitere Informationen finden Sie unter https://["Aktivieren des API-Gateways"^].

+
.CLI
Um API Gateway über die Unified Manager CLI zu aktivieren, gehen Sie wie folgt vor:

+
.. Starten Sie auf dem Unified Manager-Server eine SSH-Session und melden Sie sich bei der Unified Manager CLI an.
`um cli login -u _<umadmin>_`Informationen zu CLI-Befehlen finden Sie unter https://["Unterstützte CLI-Befehle von Unified Manager"^].
.. Überprüfen Sie, ob das API-Gateway bereits aktiviert ist.
`um option list api.gateway.enabled`A `true` Wert gibt an, dass das API-Gateway aktiviert ist.
.. Wenn der zurückgegebene Wert ist `false`, Führen Sie diesen Befehl aus:
`um option set api.gateway.enabled=true`
.. Starten Sie den Unified Manager Server neu:
+
*** Linux https://["Neustart Von Unified Manager"^].
*** VMware vSphere: https://["Starten Sie die Virtual Machine von Unified Manager neu"^].






--
.StorageGRID
--
Die folgenden Konfigurationen sind für die Installation von Keystone Collector auf StorageGRID erforderlich.

* StorageGRID `11.4.0` Oder höher sollte installiert werden. Informationen zum Aktualisieren von StorageGRID finden Sie unter link:https://docs.netapp.com/us-en/storagegrid-116/upgrade/index.html["Upgrade der StorageGRID Software: Übersicht"^].
* Für die Erfassung von Nutzungsdaten sollte ein lokales StorageGRID-Administratorbenutzerkonto erstellt werden. Dieses Servicekonto wird vom Keystone Collector Service für die Kommunikation mit StorageGRID über Administrator-Node-APIs verwendet.
+
.Schritte
.. Melden Sie sich beim Grid Manager an. Siehe https://["Melden Sie sich beim Grid Manager an"^].
.. Erstellen Sie eine lokale Administratorgruppe mit `Access mode: Read-only`. Siehe https://["Erstellen einer Admin-Gruppe"^].
.. Fügen Sie die folgenden Berechtigungen hinzu:
+
*** Mandantenkonten
*** Wartung
*** Abfrage Von Kennzahlen


.. Erstellen Sie einen Keystone Service-Account-Benutzer und verknüpfen Sie ihn mit der Administratorgruppe. Siehe https://["Benutzer managen"].




--
====