---
sidebar: sidebar 
permalink: installation/asup-config.html 
keywords: ASUP, AutoSupport configuration 
summary: Konfiguration von AutoSupport zur Integration von Keystone Daten in die täglichen Support-Bundles, die von ONTAP Clustern gesendet werden 
---
= AutoSupport für Keystone konfigurieren
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Bei Verwendung des AutoSupport Telemetrie-Mechanismus berechnet Keystone die Nutzung auf Basis der AutoSupport Telemetriedaten. Um die erforderliche Granularität zu erreichen, sollten Sie AutoSupport so konfigurieren, dass Keystone Daten in die täglich von den ONTAP Clustern gesendeten Support-Bundles integriert werden.

.Über diese Aufgabe
Beachten Sie Folgendes, bevor Sie AutoSupport für die Einbeziehung von Keystone Daten konfigurieren.

* Sie bearbeiten die AutoSupport Telemetrieoptionen mithilfe der ONTAP CLI. Informationen zum Verwalten von AutoSupport-Services und der Administratorrolle des Systems (Clusters) finden Sie unter https://docs.netapp.com/us-en/ontap/system-admin/manage-autosupport-concept.html["AutoSupport managen – Übersicht"^] Und https://docs.netapp.com/us-en/ontap/system-admin/cluster-svm-administrators-concept.html["Cluster- und SVM-Administratoren"^].
* Sie integrieren die Subsysteme in die täglichen und wöchentlichen AutoSupport Bundles, um eine präzise Datenerfassung für Keystone zu gewährleisten. Informationen zu AutoSupport-Subsystemen finden Sie unter https://docs.netapp.com/us-en/ontap/system-admin/autosupport-subsystem-collection-reference.html["Was sind AutoSupport-Subsysteme"^].


.Schritte
. Melden Sie sich als Systemadministrator über SSH beim Keystone ONTAP-Cluster an. Weitere Informationen finden Sie unter https://docs.netapp.com/us-en/ontap/system-admin/access-cluster-ssh-task.html["Greifen Sie über SSH auf das Cluster zu"^].
. Ändern Sie den Protokollinhalt.
+
** Führen Sie diesen Befehl aus, um den täglichen Protokollinhalt zu ändern:
+
[source]
----
autosupport trigger modify -node * -autosupport-message management.log -basic-additional wafl,performance,snapshot,platform,object_store_server,san,raid,snapmirror -troubleshooting-additional wafl
----
** Führen Sie diesen Befehl aus, um den wöchentlichen Protokollinhalt zu ändern:
+
[source]
----
autosupport trigger modify -autosupport-message weekly -troubleshooting-additional wafl -node *
----
+
Weitere Informationen zu diesem Befehl finden Sie unter https://docs.netapp.com/us-en/ontap-cli-9131/system-node-autosupport-trigger-modify.html["System-Node AutoSupport löst Modify aus"^].




