---
sidebar: sidebar 
permalink: installation/linux-installation.html 
keywords: Linux installation Keystone, Linux Collector installation 
summary: Installieren Sie die Keystone Collector-Software aus dem YUM-Software-Repository. 
---
= Installieren Sie Keystone Collector auf Linux Systemen
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Sie können die Keystone Collector-Software auf einem Linux-Server mit einem RPM oder einem Debian-Paket installieren. Führen Sie die Installationsschritte je nach Linux-Distribution aus.

[role="tabbed-block"]
====
.RPM wird verwendet
--
. SSH auf den Keystone Collector Server und erhöhen auf `root` Berechtigung.
. Importieren Sie die öffentliche Keystone -Signatur:
`# rpm --import https://keystone.netapp.com/repo1/RPM-GPG-NetApp-Keystone-20251020`
. Stellen Sie sicher, dass das richtige öffentliche Zertifikat importiert wurde, indem Sie den Fingerabdruck für die Keystone Billing Platform in der RPM-Datenbank überprüfen:
`# rpm -qa gpg-pubkey --qf '%{Description}'|gpg --show-keys --fingerprint` Der korrekte Fingerabdruck sieht so aus:
`9297 0DB6 0867 22E7 7646 E400 4493 5CBB C9E9 FEDC`
. Laden Sie die `keystonerepo.rpm` Datei:
`curl -O https://keystone.netapp.com/repo1/keystonerepo.rpm`
. Überprüfen Sie die Echtheit der Datei:
`rpm --checksig -v keystonerepo.rpm` Eine Signatur für eine authentische Datei sieht folgendermaßen aus:
`Header V4 RSA/SHA512 Signature, key ID c9e9fedc: OK`
. Installieren Sie die YUM-Software-Repository-Datei:
`# yum install keystonerepo.rpm`
. Wenn Keystone Repo installiert ist, installieren Sie das Keystone-Collector-Paket über den YUM-Paketmanager:
+
`# yum install keystone-collector`

+
Führen Sie für Red Hat Enterprise Linux 9 den folgenden Befehl aus, um das Keystone-Collector-Paket zu installieren: 
`# yum install keystone-collector-rhel9`



--
.Debian Verwenden
--
. SSH zum Keystone Collector Server und Zugriff auf `root` Berechtigungen.
`sudo su`
. Laden Sie die Datei herunter `keystone-sw-repo.deb`:
`curl -O https://keystone.netapp.com/downloads/keystone-sw-repo.deb`
. Keystone-Software-Repository-Datei installieren:
`# dpkg -i keystone-sw-repo.deb`
. Paketliste aktualisieren:
`# apt-get update`
. Installieren Sie beim Installieren des Keystone-Repo das Keystone-Collector-Paket:
`# apt-get install keystone-collector`


--
====

NOTE: Nach Abschluss der Installation können Sie das Dienstprogramm „Keystone Collector Management Terminal User Interface (TUI)“ verwenden, um die Konfigurations- und Überwachungsaktivitäten durchzuführen. Sie können verschiedene Tastaturbedienungen wie die Eingabetaste und die Pfeiltasten verwenden, um die Optionen auszuwählen und durch diese TUI zu navigieren. Siehe link:../installation/configuration.html["Konfigurieren Sie Keystone Collector"] Und link:../installation/monitor-health.html["Systemzustand überwachen"] Zur Information.
