---
sidebar: sidebar 
permalink: installation/linux-installation.html 
keywords: Linux installation Keystone, Linux Collector installation 
summary: Installieren Sie die Keystone Collector-Software aus dem YUM-Software-Repository. 
---
= Installieren Sie Keystone Collector auf Linux Systemen
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Sie können die Keystone Collector-Software auf einem Linux-Server mit einem RPM oder einem Debian-Paket installieren. Führen Sie die Installationsschritte je nach Linux-Distribution aus.

[role="tabbed-block"]
====
.RPM wird verwendet
--
. SSH auf den Keystone Collector Server und erhöhen auf `root` Berechtigung.
. Importieren Sie die öffentliche Keystone-Signatur:
`# rpm --import https://keystone.netapp.com/repo/RPM-GPG-NetApp-Keystone-20221101`
. Vergewissern Sie sich, dass das korrekte öffentliche Zertifikat importiert wurde, indem Sie den Fingerabdruck für die Keystone Billing Platform in der RPM-Datenbank überprüfen:
`# rpm -qa gpg-pubkey --qf '%{Description}'|gpg --show-keys --fingerprint` Der korrekte Fingerabdruck sieht folgendermaßen aus:
`90B3 83AF E07B 658A 6058 5B4E 76C2 45E4 33B6 C17D`
. Laden Sie die herunter `keystonerepo.rpm` Datei:
`curl -O https://keystone.netapp.com/repo/keystonerepo.rpm`
. Überprüfen Sie die Authentizität der Datei:
`rpm --checksig -v keystonerepo.rpm`Eine Signatur für eine authentische Datei sieht wie folgt aus:
`Header V4 RSA/SHA512 Signature, key ID 33b6c17d: OK`
. Installieren Sie die YUM-Software-Repository-Datei:
`# yum install keystonerepo.rpm`
. Wenn Keystone Repo installiert ist, installieren Sie das Keystone-Collector-Paket über den YUM-Paketmanager:
`# yum install keystone-collector`


--
.Debian Verwenden
--
. SSH zum Keystone Collector Server und Zugriff auf `root` Berechtigungen.
`sudo su`
. Laden Sie die Datei herunter `keystone-sw-repo.deb`:
`curl -O https://keystone.netapp.com/downloads/keystone-sw-repo.deb`
. Keystone-Software-Repository-Datei installieren:
`# dpkg -i keystone-sw-repo.deb`
. Paketliste aktualisieren:
`# apt-get update`
. Installieren Sie beim Installieren des Keystone-Repo das Keystone-Collector-Paket:
`# apt-get install keystone-collector`


--
====

NOTE: Nach Abschluss der Installation können Sie das Dienstprogramm „Keystone Collector Management Terminal User Interface (TUI)“ verwenden, um die Konfigurations- und Überwachungsaktivitäten durchzuführen. Sie können verschiedene Tastaturbedienungen wie die Eingabetaste und die Pfeiltasten verwenden, um die Optionen auszuwählen und durch diese TUI zu navigieren. Siehe link:../installation/configuration.html["Konfigurieren Sie Keystone Collector"] Und link:../installation/monitor-health.html["Systemzustand überwachen"] Zur Information.
