---
sidebar: sidebar 
permalink: installation/validation.html 
keywords: validate, validation 
summary: Das Keystone Repository ist so konfiguriert, dass die Integrität der Keystone Software automatisch validiert wird. 
---
= Automatische Validierung der Keystone Software
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Das Keystone Repository ist so konfiguriert, dass die Integrität der Keystone Software automatisch überprüft wird, sodass an Ihrem Standort nur gültige und authentische Software installiert wird.

Die in bereitgestellte Keystone YUM Repository-Client-Konfiguration `keystonerepo.rpm` verwendet die erzwungene GPG-Prüfung (`gpgcheck=1`) für alle Software, die über dieses Repository heruntergeladen wird. Alle RPM, die über das Keystone-Repository heruntergeladen werden, das die Signaturvalidierung fehlschlägt, wird nicht installiert. Diese Funktion wird in der Funktion für die automatische Aktualisierung nach Zeitplan von Keystone Collector verwendet, um sicherzustellen, dass nur gültige und authentische Software an Ihrem Standort installiert wird.
