---
sidebar: sidebar 
permalink: installation/vapp-prereqs.html 
keywords: prerequisites, VMware vSphere, vApp 
summary: Ihr VMware vSphere System muss mehrere Anforderungen erfüllen, bevor Sie Keystone Collector installieren können. 
---
= Anforderungen an die virtuelle Infrastruktur
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Ihr VMware vSphere System muss mehrere Anforderungen erfüllen, bevor Sie Keystone Collector installieren können.

.Voraussetzungen für die Keystone Collector-Server-VM:
* Betriebssystem: VMware vCenter Server und ESXi 6.7 oder höher
* Kern: 1 CPU
* RAM: 2 GB RAM
* Festplattenspeicher: 20 GB vDisk




== Andere Anforderungen

Stellen Sie sicher, dass die folgenden allgemeinen Anforderungen erfüllt sind:



=== Netzwerkanforderungen

Die Netzwerkanforderungen von Keystone Collector sind in der folgenden Tabelle aufgeführt.


NOTE: Keystone Collector erfordert Internetverbindung. Sie können Internet-Konnektivität durch direktes Routing über Standard-Gateway (über NAT) oder über HTTP Proxy bereitstellen. Beide Varianten werden hier beschrieben.

|===


| Quelle | Ziel | Service | Protokoll und Ports | Kategorie | Zweck 


 a| 
Keystone Collector (für Keystone ONTAP)
 a| 
Active IQ Unified Manager (Unified Manager)
 a| 
HTTPS
 a| 
TCP 443
 a| 
Obligatorisch (bei Verwendung von Keystone ONTAP)
 a| 
Erfassung der Nutzungsmetriken von Keystone Collector für ONTAP



 a| 
Keystone Collector (für Keystone StorageGRID)
 a| 
StorageGRID-Administratorknoten
 a| 
HTTPS
 a| 
TCP 443
 a| 
Obligatorisch (bei Verwendung von Keystone StorageGRID)
 a| 
Erfassung der Nutzungsmetriken von Keystone Collector für StorageGRID



 a| 
Keystone Collector (allgemein)
 a| 
Internet (gemäß URL-Anforderungen, die später angegeben werden)
 a| 
HTTPS
 a| 
TCP 80, TCP 443
 a| 
Obligatorisch (Internetverbindung)
 a| 
Keystone Collector, OS-Updates und Uploads von Metriken



 a| 
Keystone Collector (allgemein)
 a| 
HTTP-Proxy des Kunden
 a| 
HTTP-Proxy
 a| 
Proxy-Port Des Kunden
 a| 
Obligatorisch (Internetverbindung)
 a| 
Keystone Collector, OS-Updates und Uploads von Metriken



 a| 
Keystone Collector (allgemein)
 a| 
DNS-Server des Kunden
 a| 
DNS
 a| 
TCP/UDP 53
 a| 
Obligatorisch
 a| 
DNS-Auflösung



 a| 
Keystone Collector (allgemein)
 a| 
NTP-Server von Kunden
 a| 
NTP
 a| 
UDP 123
 a| 
Obligatorisch
 a| 
Zeitsynchronisierung



 a| 
Keystone Collector (für Keystone ONTAP)
 a| 
Unified Manager
 a| 
MYSQL
 a| 
TCP 3306
 a| 
Optionale Funktionen
 a| 
Sammlung von Performance-Kennzahlen für Keystone Collector



 a| 
Keystone Collector (allgemein)
 a| 
Kundenüberwachungssystem
 a| 
HTTPS
 a| 
TCP 7777
 a| 
Optionale Funktionen
 a| 
Statusberichte für Keystone Collector



 a| 
Operations Workstations des Kunden
 a| 
Keystone Collector
 a| 
SSH
 a| 
TCP 22
 a| 
Vereinfachtes
 a| 
Zugriff auf die Keystone Collector-Verwaltung



 a| 
NetApp ONTAP-Cluster- und Node-Management-Adressen
 a| 
Keystone Collector
 a| 
HTTP_8000, PING
 a| 
TCP 8000, ICMP Echo Request/Reply
 a| 
Optionale Funktionen
 a| 
Webserver für ONTAP-Firmware-Updates

|===

NOTE: Der Standardport für MySQL, 3306, ist während einer Neuinstallation von Unified Manager nur auf localhost beschränkt, was die Erfassung von Leistungsmetriken für Keystone Collector verhindert. Weitere Informationen finden Sie unter link:addl-req.html["ONTAP-Anforderungen"].



=== URL-Zugriff

Keystone Collector benötigt Zugriff auf die folgenden Internet-Hosts:

|===


| Adresse | Grund 


 a| 
https://keystone.netapp.com[]
 a| 
Keystone Collector Software-Updates und Nutzungsberichte



 a| 
https://support.netapp.com[]
 a| 
NetApp HQ für Rechnungsinformationen und AutoSupport-Lieferungen

|===