---
sidebar: sidebar 
permalink: release-notes/fixed-issues.html 
keywords: fixed issues 
summary: Probleme in verschiedenen Versionen von Keystone STaaS behoben 
---
= Probleme wurden behoben
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Probleme, die in früheren Versionen der NetApp Keystone STaaS Services gefunden wurden, wurden in späteren Versionen behoben. Dies sind die Korrekturen.

[cols="3*"]
|===
| Problembeschreibung | Nach dem Fix | Behoben in Freigabe 


 a| 
Für AutoSupport-Abonnements sind auf der Registerkarte *Assets* keine Informationen verfügbar.
 a| 
Fest
 a| 
März 14, 2024



 a| 
Wenn sowohl MetroCluster als auch FabricPool in einer Umgebung aktiviert wurden, in der die Tarifen für Tiering und Objekt-Storage gelten, könnten die Service-Level für die gespiegelten Volumes (sowohl konstituierende Volumes als auch FabricPool Volumes) falsch abgeleitet werden.
 a| 
Auf Spiegelungsvolumes werden die korrekten Service-Level angewendet.
 a| 
Februar 29, 2024



 a| 
Bei einigen Abonnements mit einem einzelnen Servicelevel oder Tarifplan fehlte in der CSV-Ausgabe der *Volumes*-Tab-Berichte die Spalte AQoS Compliance.
 a| 
Die Spalte „Compliance“ wird in den Berichten angezeigt.
 a| 
Februar 29, 2024



 a| 
In einigen MetroCluster-Umgebungen wurde gelegentlich eine Anomalie in den IOPS-Dichtediagrammen auf der Registerkarte *Performance* erkannt. Dies ist auf die ungenaue Zuordnung von Volumes zu Service-Levels zurückzuführen.
 a| 
Die Diagramme werden korrekt angezeigt.
 a| 
Februar 29, 2024



 a| 
Die Verwendungsanzeige für einen Burst-Verbrauchsdatensatz wurde gelb angezeigt.
 a| 
Die Anzeige erscheint rot.
 a| 
Dezember 13, 2023



 a| 
Der Datumsbereich und die Daten in den Registerkarten Kapazitätstrend, Aktuelle Nutzung und Leistung wurden nicht in die UTC-Zeitzone konvertiert.
 a| 
Der Datumsbereich für Abfrage und Daten in allen Registerkarten wird in UTC-Zeit (Serverzeitzone) angezeigt. Die UTC-Zeitzone wird auch für jedes Datumsfeld auf den Registerkarten angezeigt.
 a| 
Dezember 13, 2023



 a| 
Das Start- und Enddatum zwischen den Registerkarten und den heruntergeladenen CSV-Berichten stimmt nicht überein.
 a| 
Behoben.
 a| 
Dezember 13, 2023

|===