---
sidebar: sidebar 
permalink: release-notes/fixed-issues.html 
keywords: fixed issues 
summary: Probleme, die in früheren Versionen der NetApp Keystone STaaS Services gefunden wurden, wurden in späteren Versionen behoben. 
---
= Fehler in Keystone STaaS behoben
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Probleme, die in früheren Versionen der NetApp Keystone STaaS Services gefunden wurden, wurden in späteren Versionen behoben.

[cols="3*"]
|===
| Problembeschreibung | Nach dem Fix | Behoben in Freigabe 


 a| 
Abonnements werden im Digital Advisor Dashboard fälschlicherweise als *Über dem Burst-Limit* angezeigt, obwohl der Verbrauch innerhalb der zulässigen Burst-Limits liegt.
 a| 
Fest
 a| 
08.12.2025



 a| 
Fehlende Burst-Schwellenwertlinie in Verbrauchstrenddiagrammen für Abonnements, die mit einer MetroCluster -Konfiguration im Digital Advisor Dashboard konfiguriert wurden, zeigt einen falschen Status *Über Burst-Grenze* an.
 a| 
Fest
 a| 
28.08.2025



 a| 
Auf der Registerkarte *Assets* sind Assets für StorageGRID nicht sichtbar.
 a| 
Fest
 a| 
1 2025-06-19



 a| 
Für das Service-Level „Advance Data-Protect“ zeigt das Diagramm auf der Registerkarte „Verbrauchstrend“ eine Aufteilung für primäre und gespiegelte Sites.
 a| 
Das Diagramm zeigt keine Aufteilung mehr für primäre und gespiegelte Sites.
 a| 
1 2025-06-19



 a| 
Wenn der vorhandene Keystone Collector, der mit einem Debian-Paket installiert wurde, versucht, einen HTTP-Proxy zu konfigurieren oder Unified Manager über die Management-TUI Keystone Collector zu aktivieren, reagiert die TUI nicht mehr.
 a| 
Fest
 a| 
1 2025-05-19



 a| 
Keystone Collector für StorageGRID kann aufgrund fehlender allgemeiner Einstellungen nicht richtig konfiguriert werden.
 a| 
Fest
 a| 
1 2025-05-12



 a| 
Keystone Collector erfasst keine Nutzungsdaten für ONTAP-Cluster mit Versionen unter 9.11.
 a| 
Fest
 a| 
1 2025-04-30



 a| 
Die Verbrauchswerte für verknüpfte Abonnements zeigen falsche negative Zahlen an, was dazu führt, dass die gesamte gebuchte Nutzung ungenau hoch angezeigt wird.
 a| 
Fest
 a| 
1 2025-04-14



 a| 
Historische Daten können auf der Registerkarte *Verbrauchstrend* für Service-Levels für einige Abonnements nicht angezeigt werden.
 a| 
Fest
 a| 
1 2025-04-14



 a| 
Fehlende Option *Keystone Subscriptions* von *Watchlist* und die Option *Subscription Number* von *Reports* auf dem Digital Advisor Dashboard.
 a| 
Fest
 a| 
1 2025-03-19



 a| 
Einige Keystone-Abonnements von *Watchlist* fehlen, nachdem Sie die Watchlist im Digital Advisor-Dashboard erstellt oder geändert haben.
 a| 
Fest
 a| 
1 2025-03-19



 a| 
Historische Daten können nicht auf der Registerkarte *Verbrauchstrend* für Service-Level angezeigt werden, die mit einem Abonnement verbunden sind, das abgelaufen ist und mit derselben Tracking-ID, aber unterschiedlichen Service-Levels erneuert wurde.
 a| 
Fest
 a| 
1 2025-03-19



 a| 
Berichte für Abonnements können nicht erstellt werden, wenn mehr als 10-12 Abonnements auf der Registerkarte *Abonnements* auf der Seite *Keystone Abonnements* ausgewählt werden.
 a| 
Fest
 a| 
1 2025-01-08



 a| 
Die Unterregisterkarte *Volume Summary* auf der Registerkarte *Volumes & Objekte* wird für StorageGRID-Abonnements nicht geladen.
 a| 
Fest
 a| 
1 2024-11-21



 a| 
Das Feld *von Datum* zur Auswahl des Datumsbereichs zeigt standardmäßig ein künftiges Datum an, wenn Sie zur Registerkarte *Verbrauchstrend* navigieren.
 a| 
Fest
 a| 
1 2024-09-04



 a| 
Die Management-TUI für Keystone Collector reagiert nicht mehr, wenn AQoS-Richtlinien eingerichtet werden.
 a| 
Fest
 a| 
August 07, 2024



 a| 
In den Nutzungsdiagrammen werden Daten angezeigt, die über den angegebenen Zeitraum eines Tages hinausgehen, wenn das dem aktuellen Tag entsprechende Datum sowohl als Start- als auch als Enddatum für den Vormonat aus der Option *Kapazitätstrends* auf der Registerkarte *Kapazitätstrends* ausgewählt wird.
 a| 
Die Verwendungsdiagramme zeigen nun die Daten für den angegebenen Zeitraum eines Tages korrekt an.
 a| 
27. Juni 2024



 a| 
Für die Servicelevel *CVO Primary* und *CVO Secondary* auf der Registerkarte *Capacity Trend* für Abonnements, die nicht mit einer MetroCluster-Konfiguration konfiguriert sind, sind keine historischen aufgelaufenen Burst-Daten verfügbar.
 a| 
Fest
 a| 
21. Juni 2024



 a| 
Falsche Anzeige des verbrauchten Objektspeichers auf der Registerkarte *Volume-Details* für AutoSupport-Abonnements.
 a| 
Der verbrauchte Wert für Objekt-Storage wird jetzt korrekt angezeigt.
 a| 
21. Juni 2024



 a| 
Informationen auf Cluster-Ebene auf der Registerkarte *Assets* für AutoSupport-Abonnements, die mit einer MetroCluster-Konfiguration konfiguriert sind, können nicht angezeigt werden.
 a| 
Fest
 a| 
21. Juni 2024



 a| 
Falsche Platzierung von Keystone-Daten in CSV-Berichten, wenn die Spalte *Account Name* in CSV-Berichten, die auf der Registerkarte *Capacity Trend* generiert wird, einen Kontonamen mit einem Komma enthält `(,)`.
 a| 
Keystone Daten werden in CSV-Berichten korrekt ausgerichtet.
 a| 
Mai 29, 2024



 a| 
Zeigen Sie die aufgelaufene Burst-Nutzung auf der Registerkarte *Capacity Trend* an, auch wenn der Verbrauch unter der gebuchten Kapazität liegt.
 a| 
Fest
 a| 
Mai 29, 2024



 a| 
Falscher QuickInfo-Text für das Index-Symbol *Aktueller Burst* im Register *Kapazitätstrend*.
 a| 
Zeigt den korrekten QuickInfo-Text „_die Menge der aktuell verbrauchten Burst-Kapazität an. Hinweis: Dies gilt für den aktuellen Abrechnungszeitraum, nicht für den ausgewählten Datumsbereich._“
 a| 
März 28, 2024



 a| 
Informationen zu nicht konformen AQoS-Volumes und MetroCluster-Partnern stehen für AutoSupport-Abonnements nicht zur Verfügung, wenn Keystone Daten 24 Stunden lang nicht vorhanden sind.
 a| 
Fest
 a| 
März 28, 2024



 a| 
Gelegentliche Diskrepanz bei der Anzahl der nicht-konformen AQoS-Volumes, die auf den Registerkarten *Volume Summary* und *Volume Details* aufgeführt sind, wenn zwei Service-Levels einem Volume zugewiesen sind, das AQoS-Compliance nur für ein Service-Level erfüllt.
 a| 
Fest
 a| 
März 28, 2024



 a| 
Für AutoSupport-Abonnements sind auf der Registerkarte *Assets* keine Informationen verfügbar.
 a| 
Fest
 a| 
März 14, 2024



 a| 
Wenn sowohl MetroCluster als auch FabricPool in einer Umgebung aktiviert wurden, in der die Tarifen für Tiering und Objekt-Storage gelten, könnten die Service-Level für die gespiegelten Volumes (sowohl konstituierende Volumes als auch FabricPool Volumes) falsch abgeleitet werden.
 a| 
Auf Spiegelungsvolumes werden die korrekten Service-Level angewendet.
 a| 
Februar 29, 2024



 a| 
Bei einigen Abonnements mit einem einzelnen Servicelevel oder Tarifplan fehlte in der CSV-Ausgabe der *Volumes*-Tab-Berichte die Spalte AQoS Compliance.
 a| 
Die Spalte „Compliance“ wird in den Berichten angezeigt.
 a| 
Februar 29, 2024



 a| 
In einigen MetroCluster-Umgebungen wurde gelegentlich eine Anomalie in den IOPS-Dichtediagrammen auf der Registerkarte *Performance* erkannt. Dies ist auf die ungenaue Zuordnung von Volumes zu Service-Levels zurückzuführen.
 a| 
Die Diagramme werden korrekt angezeigt.
 a| 
Februar 29, 2024



 a| 
Die Verwendungsanzeige für einen Burst-Verbrauchsdatensatz wurde gelb angezeigt.
 a| 
Die Anzeige erscheint rot.
 a| 
Dezember 13, 2023



 a| 
Der Datumsbereich und die Daten in den Registerkarten Kapazitätstrend, Aktuelle Nutzung und Leistung wurden nicht in die UTC-Zeitzone konvertiert.
 a| 
Der Datumsbereich für Abfrage und Daten in allen Registerkarten wird in UTC-Zeit (Serverzeitzone) angezeigt. Die UTC-Zeitzone wird auch für jedes Datumsfeld auf den Registerkarten angezeigt.
 a| 
Dezember 13, 2023



 a| 
Das Start- und Enddatum zwischen den Registerkarten und den heruntergeladenen CSV-Berichten stimmt nicht überein.
 a| 
Behoben.
 a| 
Dezember 13, 2023

|===