---
sidebar: sidebar 
permalink: release-notes/known-issues.html 
keywords: netapp, keystone, release notes, known issues 
summary: Bekannte Probleme identifizieren Probleme, die eine effektive Nutzung der Keystone Abonnementservices verhindern könnten. 
---
= Bekannte Probleme
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Bekannte Probleme identifizieren Probleme, die eine effektive Nutzung der Keystone Abonnementservices verhindern könnten.

Die folgenden bekannten Probleme werden in NetApp Keystone STaaS gemeldet:

[cols="3*"]
|===
| Bekanntes Problem | Beschreibung | Behelfslösung 


 a| 
Volume-Details für primäre und verknüpfte Abonnements nicht verfügbar
 a| 
Die Registerkarte *Volume Summary* zeigt Null für die Gesamtanzahl der Volumes, den QoS-Compliance-Status, die Anzahl der geschützten Volumes und die insgesamt verbrauchte Kapazität für primäre und verknüpfte sekundäre Abonnements an.
 a| 
Keine



 a| 
Berichte für Abonnements können nicht erstellt werden
 a| 
Wenn auf der Seite *Keystone Abonnements* mehr als 10-12 Abonnements ausgewählt sind, kann der Bericht nicht generiert werden, wenn Sie auf die Schaltfläche *CSV herunterladen* mit der Option *Daten für jeden Service-Level einfügen* klicken.
 a| 
Keine

|===