---
sidebar: sidebar 
permalink: release-notes/known-issues.html 
keywords: netapp, keystone, release notes, known issues 
summary: Bekannte Probleme identifizieren Probleme, die eine effektive Nutzung der Keystone Abonnementservices verhindern könnten. 
---
= Bekannte Probleme in Keystone STaaS
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Bekannte Probleme identifizieren Probleme, die eine effektive Nutzung der Keystone Abonnementservices verhindern könnten.

Die folgenden bekannten Probleme werden in NetApp Keystone STaaS gemeldet:

[cols="3*"]
|===
| Bekanntes Problem | Beschreibung | Behelfslösung 


 a| 
Anzeige des falschen QoS-Richtlinientyps
 a| 
Auf der Registerkarte *Volume Details* wird in der Spalte *QoS Policy Type* _QoS_ angezeigt, wenn keine QoS-Richtlinie angewendet wird, und in der Spalte Compliant wird _Not set_ angezeigt, was zu einer Inkonsistenz im angezeigten QoS-Richtlinienstatus führt.
 a| 
Keine



 a| 
Volume-Details für primäre und verknüpfte Abonnements nicht verfügbar
 a| 
Die Registerkarte *Volume Summary* zeigt Null für die Gesamtanzahl der Volumes, den QoS-Compliance-Status, die Anzahl der geschützten Volumes und die insgesamt verbrauchte Kapazität für primäre und verknüpfte sekundäre Abonnements an.
 a| 
Keine

|===