---
sidebar: sidebar 
permalink: release-notes/known-issues.html 
keywords: netapp, keystone, release notes, known issues 
summary: Bekannte Probleme in der NetApp Service Engine 
---
= Bekannte Probleme in der NetApp Service Engine
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Die folgenden bekannten Probleme wurden in NetApp Keystone STaaS gemeldet. Bei der Provisionierung oder Verwendung des von Ihren Keystone Abonnements gemanagten Storage können diese Probleme auftreten.

[cols="3*"]
|===
| Bekanntes Problem | Beschreibung | Behelfslösung 


 a| 
Falsches Service-Level für Spiegelungs-Volumes abgeleitet.
 a| 
Wenn sowohl MetroCluster als auch FabricPool in einer Umgebung aktiviert werden, in der die Tarifen für Tiering und Objekt-Storage anwendbar sind, sind die Service-Level für die gespiegelten Volumes (zusammengehörige und FabricPool Volumes) möglicherweise falsch.
 a| 
Keine.



 a| 
Teilweise sichtbare Links und Symbole auf der Registerkarte *Abonnements*.
 a| 
Einige Links und Icons, wie z.B. der Link zur Registerkarte *Current Usage* und die Tooltips einiger Spalten sind teilweise sichtbar.
 a| 
Keine Behelfslösung erforderlich. Die Links funktionieren wie erwartet.

|===