---
sidebar: sidebar 
permalink: release-notes/known-issues.html 
keywords: netapp, keystone, release notes, known issues 
summary: Bekannte Probleme in Keystone STaaS 
---
= Bekannte Probleme in Keystone STaaS
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Bekannte Probleme identifizieren Probleme, die eine effektive Nutzung der Keystone Abonnementservices verhindern könnten.

Die folgenden bekannten Probleme wurden in NetApp Keystone STaaS gemeldet.

[cols="3*"]
|===
| Bekanntes Problem | Beschreibung | Behelfslösung 


 a| 
Erweiterte Datenanzeige für die Tagesauswahl im Register *Kapazitätstrends*.
 a| 
Wenn das heutige Datum sowohl als Start- als auch Enddatum für den Vormonat über die Option *Kapazitätstrends* auf der Registerkarte *Kapazitätstrends* ausgewählt ist, werden in den Nutzungsdiagrammen Daten für einen Zeitraum angezeigt, der vom ausgewählten Startdatum bis zum aktuellen Datum reicht. statt Daten für den angegebenen eintägigen Zeitraum zu zeigen.
 a| 
Keine



 a| 
Historische anfallende Burst-Daten sind für Service-Level nicht verfügbar.
 a| 
Die historischen aufgelaufenen Burst-Nutzungsdaten für die Servicelevel *CVO Primary* und *CVO Secondary* auf der Registerkarte *Capacity Trend* stehen für Abonnements, die nicht mit einer MetroCluster-Konfiguration konfiguriert sind, nicht zur Verfügung.
 a| 
Keine



 a| 
Falsche Anzeige des Werts des verbrauchten Objektspeichers bei AutoSupport-Abonnements.
 a| 
Wenn die AutoSupport Telemetrie zum Erfassen von Keystone Daten verwendet wird, wird der auf der Registerkarte *Volume-Details* aufgeführte Wert für Objektspeicher bei Abonnements mit Datei-, Block- und Objekt-Services nicht korrekt angezeigt.
 a| 
Die richtigen Informationen finden Sie im verbrauchten Wert für den Objektspeicher, der auf der Registerkarte *Aktuelle Nutzung* aufgeführt ist.



 a| 
Informationen auf Cluster-Ebene können nicht auf der Registerkarte *Assets* angezeigt werden.
 a| 
Für AutoSupport-Abonnements, die mit einer MetroCluster-Konfiguration konfiguriert sind, sind keine Details auf der Registerkarte *Assets* verfügbar.
 a| 
Keine

|===