---
sidebar: sidebar 
permalink: release-notes/known-issues.html 
keywords: netapp, keystone, release notes, known issues 
summary: Bekannte Probleme in Keystone STaaS 
---
= Bekannte Probleme in Keystone STaaS
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Bekannte Probleme identifizieren Probleme, die eine effektive Nutzung der Keystone Abonnementservices verhindern könnten.

Die folgenden bekannten Probleme wurden in NetApp Keystone STaaS gemeldet.

[cols="3*"]
|===
| Bekanntes Problem | Beschreibung | Behelfslösung 


 a| 
Gelegentliche Diskrepanz bei der Anzahl der nicht kompatiblen AQoS-Volumes im Register *Volumes*.
 a| 
Wenn einem Volume zwei Service-Level zugewiesen sind, die AQoS-Compliance nur für einen Service-Level erfüllen, kann die Anzahl der nicht-konformen AQoS-Volumes auf den Registerkarten *Volume Summary* und *Volume Details* abweichen.
 a| 
Keine



 a| 
*Assets*-Registerkarte für AutoSupport-Abonnements nicht ausgefüllt.
 a| 
Wenn die AutoSupport Telemetrie zum Erfassen von Keystone Daten für eine Abonnementnummer verwendet wird, werden auf der Registerkarte „*Assets“ keine Informationen abgerufen.
 a| 
Keine



 a| 
Falsche Darstellung der QuickInfo.
 a| 
Der Tooltip für das Index-Symbol *Aktuelle Burst* wird im Register *Kapazitätstrend* falsch angezeigt.
 a| 
Lesen Sie den korrekten QuickInfo-Text „_die Menge der Burst-Kapazität, die derzeit verbraucht wird. Hinweis: Dies gilt für den aktuellen Abrechnungszeitraum, nicht für den ausgewählten Datumsbereich._“

|===