---
sidebar: sidebar 
permalink: release-notes/whats-new.html 
keywords: 'new features, release notes, enhancements, what"s new' 
summary: Neue Funktionen und Verbesserungen bei Keystone STaaS. 
---
= Neuerungen bei Keystone STaaS
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp bietet Ihnen neue und erweiterte Funktionen in jeder neuen Version der Keystone STaaS Services.



== Neue Funktionen und Verbesserungen für 29. Februar 2024

Im Dashboard von Active IQ Digital Advisor (auch als digitaler Berater bekannt) und im Bildschirm *Keystone Abonnements* für diese Version wurden verschiedene Verbesserungen vorgenommen:



=== Hinzufügen der Registerkarte „Assets“

Der Bildschirm *Keystone Subscriptions* enthält jetzt die Registerkarte *Assets*. Auf dieser neuen Registerkarte werden basierend auf Ihren Abonnements Informationen auf Cluster-Ebene angezeigt. Weitere Informationen finden Sie unter link:../integrations/assets-tab.html["Registerkarte „Assets“"^].



=== Verbesserungen an der Registerkarte Volumes & Objekte

Um Ihre ONTAP-Systemvolumes besser zu machen, wurden zwei neue Tabulatortasten, *Volume Summary* und *Volume Details*, auf der Registerkarte *Volumes* hinzugefügt. Die Registerkarte *Volume Summary* bietet eine Gesamtanzahl der Volumes, die Ihren abonnierten Service-Levels zugeordnet sind, einschließlich des AQoS-Compliance-Status und der Kapazitätsinformationen. Die Registerkarte *Volume Details* listet alle Volumes und ihre Besonderheiten auf. Weitere Informationen finden Sie unter link:../integrations/volumes-objects-tab.html["Registerkarte Volumes  Objekte"^].



=== Verbesserte Suchfunktionen auf Digital Advisor

Die Suchparameter auf dem *Digital Advisor*-Bildschirm enthalten nun die für Keystone Abonnements erstellten Keystone Abonnementnummern und Watchlisten. Sie können die ersten drei Zeichen einer Abonnementnummer oder eines Watchlist-Namens eingeben. Weitere Informationen finden Sie unter link:../integrations/keystone-aiq.html["Das Keystone Dashboard finden Sie im Active IQ Digital Advisor"^].



=== Zeitstempel der Verbrauchsdaten anzeigen

Sie können den Zeitstempel der Verbrauchsdaten (in UTC) auf dem alten Dashboard des Widgets *Keystone Abonnements* anzeigen.



== Neue Funktionen und Verbesserungen für 13. Februar 2024

Die folgende Verbesserung wurde auf dem Bildschirm *Keystone Abonnements* von Active IQ Digital Advisor (auch als digitaler Berater bekannt) vorgenommen.



=== Möglichkeit, Abonnements anzuzeigen, die mit einem primären Abonnement verknüpft sind

Bei einigen Ihrer primären Abonnements können sekundäre verknüpfte Abonnements vorhanden sein. In diesem Fall wird die primäre Abonnementnummer weiterhin in der Spalte *Abonnementnummer* angezeigt, während die verknüpften Abonnementnummern in einer neuen Spalte *verknüpfte Abonnements* auf der Registerkarte *Abonnements* aufgeführt werden. Die Spalte *Verknüpfte Abonnements* steht Ihnen nur dann zur Verfügung, wenn Sie mit Abonnements verknüpft sind, und Sie können Informationsmeldungen sehen, die Sie darüber informieren.



== Neue Funktionen und Verbesserungen für den 11. Januar 2024

Erfahren Sie, was in dieser Version neu ist.

Die folgenden Verbesserungen wurden auf dem Bildschirm *Keystone Abonnements* von Active IQ Digital Advisor (auch als digitaler Berater bekannt) vorgenommen.



=== Die Rechnungsdaten wurden für aufgelaufene Burst zurückgegeben

Die Bezeichnungen für *aufgelaufene Burst* werden nun auf der Registerkarte *Kapazitätstrend* in *fakturierte aufgelaufene Burst* geändert. Wenn Sie diese Option auswählen, können Sie die monatlichen Diagramme für die berechneten aufgelaufenen Burst-Daten anzeigen. Weitere Informationen finden Sie unter link:../integrations/aiq-keystone-details.html#view-invoiced-accrued-burst["Anzeigen der angefallenen Burst-Rechnung"^].



=== Details des aufgelaufenen Verbrauchs für spezifische Tarifpläne

Wenn Sie ein Abonnement mit Tarifen mit _Null_ gebuchter Kapazität haben, können Sie die Details des aufgelaufenen Verbrauchs auf der Registerkarte *Kapazitätstrend* anzeigen. Bei Auswahl der Option *fakturierter aufgelaufener Verbrauch* können Sie die monatlichen Diagramme für die berechneten aufgelaufenen Verbrauchsdaten anzeigen.



== Neue Funktionen und Verbesserungen für den 15. Dezember 2023

Erfahren Sie, was in dieser Version neu ist.



=== Möglichkeit zur Suche nach Watchlisten

Die Unterstützung für Watchlisten im digitalen Berater von Active IQ (auch als digitaler Berater bekannt) wurde auf Keystone Systeme erweitert. Sie können jetzt die Details der Abonnements für mehrere Kunden anzeigen, indem Sie mit Watchlisten suchen. Weitere Informationen zur Verwendung von Watchlisten in Keystone STaaS finden Sie unter link:../integrations/keystone-aiq.html#search-by-using-keystone-watchlists["Nutzen Sie die Keystone Watchlisten, um Ihre Suche zu starten"^].



=== Datum in UTC-Zeitzone umgewandelt

Die auf den Registerkarten des Bildschirms *Keystone Abonnements* von Active IQ Digital Advisor zurückgegebenen Daten werden in UTC-Zeit (Server-Zeitzone) angezeigt. Wenn Sie ein Datum für die Abfrage eingeben, wird es automatisch als UTC-Zeit betrachtet. Weitere Informationen finden Sie unter link:../integrations/aiq-keystone-details.html["Keystone Abonnement-Dashboard und Berichterstellung"^].
